### ISSUE TITLE
(mini.clue) overriding default keymap descriptions

### ISSUE THREAD

**Issue by fh2ctm** [echasnovski/mini.nvim#1090] opened 2024-07-27 20:51 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

When a key binding has a description, custom clues defined in `config.clues` are ignored. For example, the key combo bound to `MiniSplitjoin.toggle()` will always have its default description "Toggle arguments" no matter what I set the custom clue to. 

Would it be good to allow overriding of default descriptions?

**Comment by echasnovski** [comment] 2024-07-28 11:32
This behavior is [by design](https://github.com/echasnovski/mini.nvim/blob/e24ec1fcf885990fec1a993fe8304a033fd1806d/doc/mini-clue.txt#L79-L82). As suggested in the help, use [`MiniClue.set_mapping_desc()`](https://github.com/echasnovski/mini.nvim/blob/e24ec1fcf885990fec1a993fe8304a033fd1806d/doc/mini-clue.txt#L624) to override description of existing mapping.

Closing as not planned.

**Closed by echasnovski** 2024-07-28 11:32 UTC
Labels: feature-request, mini.clue
