### ISSUE TITLE
Lsp snippets complete

### ISSUE THREAD

**Issue by basilgood** [echasnovski/mini.nvim#193] opened 2023-01-11 09:37 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

Hi! I really like this plugin.
It is simple and effective.
It's fast and has everything I need except for one thing:
- lsp snippets completion.

If cssls or cssmodules_ls is active, the server snippets it delivers expand but do
 not stop at the placeholder.

https://user-images.githubusercontent.com/16057481/211754871-ed79d63c-bffe-4417-98dc-6a3b3a13046d.mp4

This is my minimal config:
``` lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/paqs/start/paq-nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.system({'git', 'clone', '--depth=1', 'https://github.com/savq/paq-nvim.git', install_path})
end

require('paq')({
  'savq/paq-nvim',
  'echasnovski/mini.completion',
  'neovim/nvim-lspconfig',
  'williamboman/mason.nvim',
})

-- completion
require('mini.completion').setup({
  lsp_completion = {
    source_func = 'omnifunc',
    auto_setup = false,
  },
})
vim.keymap.set('i', '<Tab>', [[pumvisible() ? "\<C-n>" : "\<Tab>"]], { remap = true, expr = true })
vim.keymap.set('i', '<S-Tab>', [[pumvisible() ? "\<C-p>" : "\<S-Tab>"]], { remap = true, expr = true })

-- lsp
local lspconfig = require('lspconfig')
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
local on_attach = function(_, bufnr)
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.MiniCompletion.completefunc_lsp')
end

require('mason').setup()

local servers = { 'tsserver', 'cssls', 'cssmodules_ls', 'html' }
for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup({
    on_attach = on_attach,
    capabilities = capabilities,
    init_options = { usePlaceholders = true },
  })
end
```
Without mini.completion using omnifunc ```<C-x><C-o>```
and this setting: ```vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")```
it works.
My request is if you can help me achieve this result with mini completion plugin.
Thank you very much for your beautiful work.

**Comment by echasnovski** [comment] 2023-01-11 10:38
Thanks for the issue!

Sorry, but this is [not supported](https://github.com/echasnovski/mini.nvim/blob/e33b9a7d7214b5c743b79082b6b89dca78620030/doc/mini-completion.txt#L41-L42) and, probably, won't be supported until there is a 'mini.snippets' module. The main reason is because it is hard to implement this functionality right.

Seems like the reason why you see this in your setup is because you LSP server (`cssls` or `cssmodules_ls`) doesn't mark these completion items as "Snippet", using "Property" instead. All completion suggestions that are marked by LSP server as "Snippet" are filtered out in 'mini.completion' (with default settings).

> Without mini.completion using omnifunc `<C-x><C-o>` and this setting: `vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")` it works.

I am not sure what you mean here by "it works". I tried it with 'sumneko_lua' and it does indeed suggest "Snippet" entries which don't expand properly. You'd need snippet engine for that (like [L3MON4D3/LuaSnip](https://github.com/L3MON4D3/LuaSnip).

**Comment by basilgood** [comment] 2023-01-11 12:49
Thank you for quick response.
If I change in the above minimal init config:
``` lua
--local on_attach = function(_, bufnr)
--  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.MiniCompletion.completefunc_lsp')
--end
local on_attach = function()
  vim.opt_local.omnifunc = 'v:lua.vim.lsp.omnifunc'
end
```
I can get suggestions with ```<C-x><C-o>``` and expand them with ```<CR>``` properly.


https://user-images.githubusercontent.com/16057481/211809853-1fd7de15-88ab-44e1-b289-6fe71b610ab5.mp4

**Comment by echasnovski** [comment] 2023-01-11 13:14
Hmm... This might be due to (not so recently) added built-in [snippet parsing using `vim.lsp.util.parse_snippet()`](https://github.com/neovim/neovim/blob/80a02d1cef9bd4880e5952d3d0328dac5c7457ad/runtime/lua/vim/lsp/util.lua#L645).

I am hesitant to add this, as snippets are not currently supported at all. I'll think about it.

**Comment by basilgood** [comment] 2023-01-11 14:22
Ok! Thanks again for :heart: mini plugins. If you want you can close issue.

**Comment by echasnovski** [comment] 2023-01-12 12:59
Yes, I think I'll close this, as 'mini.completion' is not designed (yet, maybe?) to support snippets and this example does seem to come from a misbehaved LSP server (returning snippet-like completion entry as "Property").

**Closed by echasnovski** 2023-01-12 12:59 UTC
Labels: feature-request, mini.completion

**Comment by GitMurf** [comment] 2024-03-25 08:12
@echasnovski thank you for your amazing work. Checking in on this as I just started using mini.completion. But I am a bit confused as every LSP I have tried so far when selecting a function will provide placeholder "snippet" locations for function parameters / arguments. Most notably Lua and TypeScript.

Am I doing something wrong or is this expected and I need to manually go remove / fill in each parameter replacing the `(${1:param}, ...)` everytime I select a function with mini.completion?

![image](https://github.com/echasnovski/mini.nvim/assets/64155612/4435e346-8d1b-4664-b27d-30fe10f0a64d)

Is there a way that I could at least just finish the function and not have the placeholders added at all? even if for `foo(a, b, c)` if I select `foo` if it just actually returns `foo` or `foo()` without any parameters that would be much better than needing to delete everytime.

I have luasnip installed as well but cannot get it to work with it either. Maybe I am just doing something wrong? Thanks again for great work :-)

**Comment by GitMurf** [comment] 2024-03-25 21:04
@echasnovski as I am diving into this I believe this could be a windows issue and compatibility with the required `jsregexp` from luarocks.

See here from luasnip: https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#transformations

See here from kickstart where they essentially say that they could not figure out how to make it windows compatible: https://github.com/nvim-lua/kickstart.nvim/pull/611#issuecomment-1925905046

And here is an issue in luasnip repo about windows: https://github.com/L3MON4D3/LuaSnip/issues/986

This all being said, what options do I have assuming we are stuck with the function parameter snippet syntax coming through? is there a callback/hook we can utilize on selection of a completion item where I could either parse myself, or just clear out the function (params) and just return function() or function? Honestly the parsing should be quite simple for `function(${n:name}, ${n:name})` as can just take what is between `:xyz}` which will be the parameter names and just end up with function(abc, xyz) which is much easier to deal with to replace after accepting completion.

@echasnovski thoughts?

**Comment by echasnovski** [comment] 2024-03-25 21:11
I am not sure how LuaSnip is relevant here, as 'mini.completion' does not integrate with *any* snippet engines (right now).

So if this result is from 'mini.completion', then it has to come from LSP server. And currently I am not sure what config can reproduce this issue (preferably on Linux, as I don't have access to Windows).

**Comment by GitMurf** [comment] 2024-03-25 21:39
> I am not sure how LuaSnip is relevant here, as 'mini.completion' does not integrate with _any_ snippet engines (right now).

I was under the assumption that LuaSnip actually hooked itself into the LSP and essentially "intercepted" and did something with handling of LSP function snippets. But that is likely a poor assumption.

**Comment by GitMurf** [comment] 2024-03-25 21:45
@echasnovski maybe it would help if I knew what it is supposed to look like simply with Lua as the LSP source when you are autocompleting lets say `vim.api.nvim_buf_set_option()` (since that was the example I used in the screenshot above. Here is a quick video showing how it looks on my end to make sure everything else appears as expected (to validate I am not doing / expecting something else weird).

https://github.com/echasnovski/mini.nvim/assets/64155612/021ecf98-4c4c-422b-801a-4cb2e7e85459

**Comment by echasnovski** [comment] 2024-03-26 09:53
> I was under the assumption that LuaSnip actually hooked itself into the LSP and essentially "intercepted" and did something with handling of LSP function snippets. But that is likely a poor assumption.

I don't think it does that.

> @echasnovski maybe it would help if I knew what it is supposed to look like simply with Lua as the LSP source when you are autocompleting lets say `vim.api.nvim_buf_set_option()` (since that was the example I used in the screenshot above.

It should work more or less the same but without adding parenthesis (with their contents) when navigating through the completion suggestions.

For this to be more productive, at least some reproducible setup (config and exact steps) would indeed help.

**Comment by GitMurf** [comment] 2024-03-27 22:15
@echasnovski is it sufficient to tell you i am on windows 11, using nightly nvim and can reproduce with kickstart? I believe you know tj and i'm sure are familiar with the project? I cloned this in a fresh nvim: https://github.com/nvim-lua/kickstart.nvim

And then simply disabled nvim-cmp and added mini.completion with the default setup config.

Here is a branch straight from kickstart with just 2 commits to disable cmp and add mini.completion: https://github.com/GitMurf/kickstart.nvim/tree/2024_03/mini.completion-troubleshoot

**Comment by echasnovski** [comment] 2024-03-30 13:08
Sorry it took so long to look at.

A quick search for "completion" in the 'init.lua' showed me that `lua-language-server` is [configured that way](https://github.com/GitMurf/kickstart.nvim/blob/d04271f8144ae3601d1883396c744c803c7a79b5/init.lua#L561) in the Kickstart. I was finally able to reproduce this by also setting `Lua.completion.callSnippet = 'Replace'` in my config. Removing those lines should fix the issue.

**Comment by GitMurf** [comment] 2024-03-31 17:13
> A quick search for "completion" in the 'init.lua' showed me that `lua-language-server` is [configured that way](https://github.com/GitMurf/kickstart.nvim/blob/d04271f8144ae3601d1883396c744c803c7a79b5/init.lua#L561) in the Kickstart. I was finally able to reproduce this by also setting `Lua.completion.callSnippet = 'Replace'` in my config. Removing those lines should fix the issue.

Thanks for investigating! Makes sense. But the weird thing is my typescript lsp is doing the same thing and I did not change any configuration for it. Any ideas of why typescript may be? Could it be doing the "replace" out of the box?

**Comment by echasnovski** [comment] 2024-03-31 17:32
> Thanks for investigating! Makes sense. But the weird thing is my typescript lsp is doing the same thing and I did not change any configuration for it. Any ideas of why typescript may be? Could it be doing the "replace" out of the box?

Typescript language server is a bit of a mystery to me, to be honest. I think I saw an instance or two when completion item was declared as not having "Snippet" kind but expanded into a snippet.

All in all, I am fairly certain that this is an issue with LSP server (either how it is set up or its internals) and not 'mini.completion' itself.
