### ISSUE TITLE
Resizing windows with mouse is slow

### ISSUE THREAD

**Issue by anuramat** [echasnovski/mini.nvim#739] opened 2024-03-08 21:55 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

resizing windows with mouse (by dragging the bar between windows) is slow
not sure if this is even fixable, but I haven't found an issue for this

### Neovim version

0.9.5

### Steps to reproduce

1. `nvim -u init.lua`
2. :vsplit
3. resize the windows
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"echasnovski/mini.animate",
		version = "master",
		config = true,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Expected behavior

resizing is fast

### Actual behavior

resizing is slow

**Comment by echasnovski** [comment] 2024-03-09 09:09
By default, 'mini.animate' implements resizing animation (for example, type `<C-w>|` in vertical split and then `<C-w>=`). This also applies to resizing with mouse.

If I use mouse in an attempt for a quick (almost instant) resize, then it seems that Neovim registers it as a single resize and applies animation (although it might depend on the terminal emulator). If I move mouse slightly slower, then border more or less follows the mouse.

If you don't like this effect, either adjust [timing of resizing](https://github.com/echasnovski/mini.nvim/blob/c3b37f4afb933141a750b60b86fb6ef6b50d0e61/doc/mini-animate.txt#L360-L361) (for your use case linear easing with `unit = 'step'` and duration about 10 might be a better alternative) or disable `resize` animation completely.

Closing as an intended behavior with 'mini.animate'.

**Closed by echasnovski** 2024-03-09 09:09 UTC
Labels: bug, mini.animate
