### ISSUE TITLE
Mini.jump bug: t skips matches at first column 

### ISSUE THREAD

**Issue by FreebeJan** [echasnovski/mini.nvim#113] opened 2022-08-18 13:27 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.jump

### Description

In the below example file, when hitting t) on the second line, I would intuitively expect the cursor to move to he last character in line 2 as the next occurence of ) is the first char of line 3. However the cursor moves to the space before ) on line 5

### Neovim version

0.7.2

### Steps to reproduce

```
(
  t "closing parentheses" will skip line 3 and jump right to line 5 col 15
)

Something something )
```
2Gt)

### Expected behavior

Put cursor at end of line 2

### Actual behavior

Put cursor before the next match that is not on first column

**Comment by echasnovski** [comment] 2022-08-18 13:44
Thanks for the issue!

This is by design, as `till` is meant to be understood as "just before/after the match instead of exactly on target" which is initially didn't include several lines into consideration.

All search logic is done with built-in `search()` function and Vim patterns. If I'll be able to achieve your outcome with them, this will be fixed. Otherwise, in my opinion, it will introduce too much complexity for relatively small gain.

As a side note: outcome of this use case is a little bit more complex than "put cursor at end of line 2". In Normal mode - yes, in Visual and Operator-pending - probably more reasonable would be to put one line to the right (on "new line character") to allow decreasing line count. Which is another complexity factor.

**Comment by FreebeJan** [comment] 2022-08-19 08:18
Thank you for the response!
I agree with you that it should be the newline character for visual and operator-pending.

**Closed** 2022-08-23 06:20 UTC
Labels: feature-request, mini.jump

**Comment by echasnovski** [comment] 2022-08-23 06:25
Thanks for the issue! It should be primarily solved on latest `main` by allowing putting cursor past the end of line.

Not without some issues (like with `T` and target being last character in line cursor is placed *on* the target if can't be positioned to the right of it), but it does seem like a more coherent behavior. In fact, it is now aligned with 'clever-f' (from which final solution to this issue was taken).

**Comment by FreebeJan** [comment] 2022-08-23 09:40
I have been testing it the past hour or two. It works like a charm 👍
