### ISSUE TITLE
Session autowrite is not working

### ISSUE THREAD

**Issue by siddhantac** [echasnovski/mini.nvim#427] opened 2023-07-24 03:47 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

Session is not automatically written when quitting Neovim.

### Neovim version

v0.9.1

### Steps to reproduce

1. `NVIM_APPNAME=nvim-debug nvim`
2. Open any file
3. Quit nvim
4. `NVIM_APPNAME=nvim-debug nvim`

**init.lua**
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local lazy = require("lazy")

lazy.setup({
    'echasnovski/mini.nvim',
    version = '*',
    config = function()
        require("mini.sessions").setup()
        require('mini.starter').setup()
    end,
}, { })
```

### Expected behavior

Expected to see a list of sessions in mini.starter or when running `lua require("mini.sessions").select()`

## Starter
<img width="1284" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/66236925/ab647084-4fb7-4ba5-b3d8-455eed0c2564">

## Running `select()`
<img width="1283" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/66236925/3d8652da-942c-4151-8a78-bb4ea79dc345">

**Comment by echasnovski** [comment] 2023-07-24 04:26
`config.autowrite = true` (which is default) means that [**current** session will be written before closing Neovim](https://github.com/echasnovski/mini.nvim/blob/aac602e097b99a06bc84e43356f080eb6256dd21/doc/mini-sessions.txt#L80). In your example there is no loaded/read session. Try these steps:
- Execute `:lua MiniSessions.write('my_session')` after opening Neovim, which will also make 'my_session' the current one.
- Make some changes, like open a few buffers.
- Close Neovim.
- Open Neovim. The session 'my_session' should be listed.
- Load 'my_session' session. It should show changes you made before closing Neovim.

Closing as it is working as intended.

**Closed by echasnovski** 2023-07-24 04:26 UTC
Labels: mini.sessions

**Comment by devendr4** [comment] 2023-09-11 17:27
@echasnovski is it possible to automatically create a session after closing Neovim if it doesn't exist in the first place?

**Comment by echasnovski** [comment] 2023-09-11 17:45
> @echasnovski is it possible to automatically create a session before closing Neovim if it doesn't exist in the first place?

Not sure I understand the question. Do you want to create a session if Neovim currently is not in a session? It is possible by creating an autocommand on `VimLeavePre` and disabling `autowrite`. Like this:

```lua
require('mini.sessions').setup({ autowrite = false })

local autowrite = function()
  local session_name
  -- ~rite session with default name even if not currently in session
  if vim.v.this_session == '' then session_name = 'default' end
  MiniSessions.write(session_name, { force = true })
end
vim.api.nvim_create_autocmd('VimLeavePre', { callback = autowrite, desc = 'Autowrite session' })
```
