### ISSUE TITLE
mini.starter sends notifications about Starter buffers whilst using other plugins

### ISSUE THREAD

**Issue by jackwoodside** [echasnovski/mini.nvim#230] opened 2023-02-17 11:29 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

starter

### Description

When moving to the above director in nvim-tree, mini.starter sends a notification saying "`buf_id` in `refresh()` is not an identifier of valid Starter buffer". This occurs whether starter is open or not.

### Neovim version

0.8.1

### Steps to reproduce

1. Run `nvim -nu minimal.lua`.
2. Run `:NvimTreeToggle`.
3. Move up and press enter to move up a directory.

minimal.lua:
```
local root = vim.fn.fnamemodify("./.minimal", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup({
	{
		"echasnovski/mini.starter",
		config = function()
			local starter = require("mini.starter")
			starter.setup({
				items = { starter.sections.recent_files(10, true) },
			})
		end,
	},
	{
		"nvim-tree/nvim-tree.lua",
		config = function()
			require("nvim-tree").setup()
		end,
	},
}, {
	root = root .. "/plugins",
})
```

### Actual behavior

A notification is sent by mini.starter saying "`buf_id` in `refresh()` is not an identifier of valid Starter buffer". This does not occur with the default mini.starter setup, the `items` line in the given `minimal.lua` is required to reproduce the issue.

**Comment by echasnovski** [comment] 2023-02-17 11:44
Thanks for the issue! Can reproduce.

This seems to be because of [this `DirChanged` autocommand](https://github.com/echasnovski/mini.nvim/blob/369f16f29559cb15931d3d5acfcf253969f74066/lua/mini/starter.lua#L524) (which also has some other issues).

I'll look into it.

**Comment by echasnovski** [comment] 2023-02-23 15:34
Should be fixed in `main` branch.

**Closed** 2023-02-23 15:34 UTC
Labels: bug, mini.starter
