### ISSUE TITLE
Statusline virtcol display doesn't respect neovim `positive count` requirement

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#1094] opened 2024-07-29 18:21 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Statusline

### Description

Hello o/.

Neovim requires `positive count` which is currently not respected by the virtcol display (perhaps by design?) in Mini.Statusline `location` section:

![image](https://github.com/user-attachments/assets/7315a83f-fcd6-4abc-b587-81b060cee062)

For the sake of this example, if you, e.g., type d0 to delete the empty line, Neovim will return an error, instead expecting d1.

![image](https://github.com/user-attachments/assets/ad699a26-da20-47df-a77a-5e14f952fdd9)

One way to solve this is to set the minimum value to `1`:

```lua
MiniStatusline.section_location = function(args)
  -- Use virtual column number to allow update when past last column
  if MiniStatusline.is_truncated(args.trunc_width) then return '%l│%2v' end

  -- Use `virtcol()` to correctly handle multi-byte characters
  return string.format('%%l|%%L│%%2v|%-2d', math.max(vim.fn.virtcol("$") - 1, 1))
end
```

![image](https://github.com/user-attachments/assets/b0c632ec-f462-4fb3-93d0-a4e993555551)

**Comment by echasnovski** [comment] 2024-07-29 19:19
Thanks for the issue!

This is indeed intentional and allows to differentiate truly empty line and a line with one character (possibly whitespace).

Closing as behavior is by design.

------

> Neovim requires `positive count` which is currently not respected by the virtcol display (perhaps by design?) in Mini.Statusline `location` section:

I am not sure how total number of columns in the current line is related to count.

> For the sake of this example, if you, e.g., type d0 to delete the empty line, Neovim will return an error, instead expecting d1.

I can not reproduce. The `d0` executes `d` with `0` motion with no errors. The `d1` requires a motion/textobject after typing it.

**Closed by echasnovski** 2024-07-29 19:19 UTC
Labels: feature-request, mini.statusline

**Comment by wroyca** [comment] 2024-07-29 19:25
> I can not reproduce. The `d0` executes `d` with `0` motion with no errors. The `d1` requires a motion/textobject after typing it.

I should have specified that it must be run from the command line - My bad!

**Comment by echasnovski** [comment] 2024-07-29 19:30
> I should have specified that it must be run from the command line - My bad!

Ah, then it surely doesn't have anything to do with 0 being used as number of columns in current line. Because `:d` operates on lines and uses `{count}` as number of lines.
