### ISSUE TITLE
`vi{` highlights text within brackets that the cursor is not inside

### ISSUE THREAD

**Issue by thomasschafer** [echasnovski/mini.nvim#790] opened 2024-04-09 16:03 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

`vi{` along with `vi[` (and possibly other commands) move the cursor ahead and select a block that the cursor is not inside, rather than highlighting the block that the cursor is within. This is more easily explained with a screen recording:

https://github.com/echasnovski/mini.nvim/assets/54135831/4d889de9-2257-4ed7-a099-1ced74b3f662

Is this a bug? If not, is there some way for me to use the default Neovim/Vim behaviour while still using this plugin?

### Neovim version

0.9.5

### Steps to reproduce

Run the following commands to create a minimal installation of `mini.ai` and an example file to test the behaviour described:
```sh
cat >> minimal.lua << EOF
local mini_path = "./mini-ai"

if not vim.loop.fs_stat(mini_path) then
  vim.cmd('echo "Installing mini.ai..." | redraw')
  local clone_cmd = {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/echasnovski/mini.ai.git",
    mini_path,
  }
  vim.fn.system(clone_cmd)
  vim.cmd('echo "Installation finished" | redraw')
end

require("mini-ai/lua/mini/ai").setup({})
EOF
```

```sh
cat >> test.txt << EOF
foo = {
  bar: 1, 
  qux: { a: 2 },
  baz: 3
}
EOF
```

```sh
nvim -nu minimal.lua test.txt
```
Neovim will open. Move your cursor to `qux` and type `vi{` in normal mode. The block highlighted will be ` a: 2 `.

Then, run

```
nvim --clean test.txt
```

to open the same file without `mini.ai`, and repeat the process of moving to `qux` and typing `vi{`. The highlighted block will go from `bar: 1` to `baz: 3`.

### Actual behavior

See screen recording above

**Comment by echasnovski** [comment] 2024-04-09 16:24
> `vi{` along with `vi[` (and possibly other commands) move the cursor ahead and select a block that the cursor is not inside, rather than highlighting the block that the cursor is within. This is more easily explained with a screen recording:
> 
> Is this a bug?

No, it is not. It is a [documented behavior](https://github.com/echasnovski/mini.nvim/blob/32b2db5ef9066f3d7ca375ea1ccc0fc44090727d/doc/mini-ai.txt#L424-L427) of first searching inside current line and only then inside neighborhood. As default search method is `'cover_or_next'`, it first searches for covering `{}` in current line. As there is none, 'mini.ai' tries to search for "next" `{}` in current line and finds it.

If you don't want for `a` / `i` textobjects from 'mini.ai' to be searched in the direction "next" and selected only if inside of them, use `search_method = 'cover'`. With a setup like this:

```lua
require('mini.ai').setup({ search_method = 'cover' })
```

With this setup, `vi{` will select the block you expect, while `vin{` can be used to select a "next" region (the `{ a: 2 }` in this example).

Closing as duplicate of #392, #123, and #116.

**Closed by echasnovski** 2024-04-09 16:24 UTC
Labels: question, mini.ai

**Comment by thomasschafer** [comment] 2024-04-09 16:29
Thanks so much, and apologies for not finding those existing issues describing the same question. I really appreciate your help and your work on these plugins!

**Comment by echasnovski** [comment] 2024-04-09 16:44
> Thanks so much, and apologies for not finding those existing issues describing the same question. I really appreciate your help and your work on these plugins!

No problem. Although I appreciate searching through issues first, I understand that they might appear as not exactly like problem at hand or are hard to find.

Mentioning all duplicates is done for tracking purposes. Apologies if that comes off as any sort of blaming from me.

**Comment by echasnovski** [comment] 2024-04-29 16:09
> @echasnovski sorry to revive this thread, but I've been playing around with the options a little more - would you be open to adding a version of `cover_or_next` that first searches for a covering span and only looks ahead for a next span if no covering span exists, which would more closely match the default behaviour of Vim? Alternatively, would you be happy for me to contribute this in a PR?
> 
> No worries if not, just thought I'd check!

It already does that. The difference is that it first does that in current line first.

The suggested approach to resolving this is still the one from [this commit](https://github.com/echasnovski/mini.nvim/issues/790#issuecomment-2045602383). I.e. use `'serach_method = 'cover'` and use explicit variants `in`/`an`/`il`/`al` when you want next or previous match.

**Comment by thomasschafer** [comment] 2024-04-29 16:12
> It already does that. The difference is that it first does that in current line first.
> 
> The suggested approach to resolving this is still the one from [this commit](https://github.com/echasnovski/mini.nvim/issues/790#issuecomment-2045602383). I.e. use `'serach_method = 'cover'` and use explicit variants `in`/`an`/`il`/`al` when you want next or previous match.

Fair enough - thank you again!
