### ISSUE TITLE
mini.files doesn't open when file is deleted

### ISSUE THREAD

**Issue by flexagoon** [echasnovski/mini.nvim#1247] opened 2024-09-26 15:30 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When trying to open mini.files in a file that doesn't exist, it throws an error and doesn't open.

### Neovim version

0.11.0-dev+785-g44afd0744

### Steps to reproduce

1. Open any file
2. `:!rm %`
3. Try to open mini.files

### Expected behavior

It should open the parent directory of the file that was deleted, for example if you deleted `~/.config/foo` and it should just open `~/.config`

### Actual behavior

It throws an error and doesn't open

**Comment by echasnovski** [comment] 2024-09-26 15:58
This is by design: anchor path for `MiniFiles.open()` should be a present path on disk. There is no fallbacks. Use explicit call [which includes directory](https://github.com/echasnovski/mini.nvim/blob/64e95aa77587d04f97a5579b2106a82a08a7d968/doc/mini-files.txt#L694-L708).

Duplicate of #840 and #848.

**Closed by echasnovski** 2024-09-26 15:58 UTC
Labels: duplicate, mini.files
