### ISSUE TITLE
mini.bracketed (or mini.operators): Add newline before/after current line

### ISSUE THREAD

**Issue by sebastianst** [echasnovski/mini.nvim#587] opened 2023-11-25 11:13 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bracketed, mini.operators

### Description

`mini.bracketed` seems to provide most functionality of tpope's `vim-unimpaired`. I'm still missing the `[<space>` and `]<space>` commands to insert a new line before or after the current line. Given the scope of `mini.bracketed`, these mappings might fit better into `mini.operators`. Are these bindings already available somewhere? Or is it planned to add them?

**Comment by echasnovski** [comment] 2023-11-25 13:15
Thanks for the suggestion!

This is a part of ['mini.basics'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-basics.md) under [`go` and `gO`](https://github.com/echasnovski/mini.nvim/blob/baf17e6472b0968661dce5daa372251e934da39f/doc/mini-basics.txt#L234-L235). Also, unlike 'vim-unimpaired', it is dot-repeatable out of the box.

Closing as duplicate of #375.

**Closed by echasnovski** 2023-11-25 13:15 UTC
Labels: feature-request, mini.basics, mini.bracketed

**Comment by sebastianst** [comment] 2023-11-27 16:00
Thanks @echasnovski this works! Seems I didn't search well enough 🙏🏻
