### ISSUE TITLE
Completion performance regression

### ISSUE THREAD

**Issue by KAAtheWiseGit** [echasnovski/mini.nvim#904] opened 2024-05-23 08:46 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

`mini.completion`

### Description

Yesterday I've upgraded my distribution, which included updating Neovim from 0.9.4 to 0.10.0.  This seems to have caused an issue with the Mini completions.  Now, wherever I type, there is subtle lagging going on, with the cursor jumping from where it should be to the end of the `-- INSERT --` note and back.  It does so very rapidly, causing flashing and typing latency.

### Neovim version

0.10.0

### Steps to reproduce

1. `nvim -nu minimal.lua`

    ```
    local package_path = vim.fn.stdpath("data") .. "/site"
    local mini_path = package_path .. "/pack/deps/start/mini.nvim"
    if not vim.loop.fs_stat(mini_path) then
    	vim.cmd("echo \"Installing `mini.nvim`\" | redraw")
    	local clone_cmd = {
    		"git", "clone", "--filter=blob:none",
    		"--branch", "stable",
    		"https://github.com/echasnovski/mini.nvim", mini_path
    	}
    	vim.fn.system(clone_cmd)
    	vim.cmd("packadd mini.nvim | helptags ALL")
    end
    
    require("mini.deps").setup { path = { package = package_path } }
    local add, now, later = MiniDeps.add, MiniDeps.now, MiniDeps.later
    
    now(function()
    	local completion = require("mini.completion")
    	completion.setup({
    		fallback_action = nil,
    	})
    end)
    ```

2. Start typing.  The cursor will flicker.

### Actual behavior

I tried recording it with asciinema.  Locally the flickering is present, but when I upload the cursor morphs into the block one and the flickering is no longer visible.

**Comment by echasnovski** [comment] 2024-05-23 08:55
Thanks for the issue!

Do you use GUI (like Neovide)? Because I can not reproduce this in plain TUI.

Also, I'd recommend disabling that '--INSERT--' mode messages as it look not needed with mode indicator in statusline. Could you try adding `vim.o.showmode = false` to the config and see if this fixes the issue?

**Comment by KAAtheWiseGit** [comment] 2024-05-23 09:34
@echasnovski nope, plain Neovim TUI.  It's a weird bug, I honestly don't have high hopes of tracking it down.  Since there was a full system upgrade, it could've been the terminal, etc.

Oh, scratch that, disabling the mode message fixed the flickering!  The latency part is weird, though.  I have a _feeling_ that it's still slower, but I can't objectively measure it.  So, it might all be just in my head.

**Comment by echasnovski** [comment] 2024-05-23 09:42
Ok, closing then. if there is a reliable reproducible example with `vim.o.showmode = true` I *might* look into it, but I'd go as a general suggestion to disable 'showmode' ('mini.basics' already does that).

**Closed by echasnovski** 2024-05-23 09:42 UTC
Labels: mini.completion, needs-repro
