### ISSUE TITLE
Ability to disable indentscope per filetype/buftype

### ISSUE THREAD

**Issue by ibhagwan** [echasnovski/mini.nvim#85] opened 2022-05-26 18:13 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

indentscope

### Description

Hi again @echasnovski,

Obviously I can workaround that with autocommands and `b:miniindentscope_disable` but I think it would be nice to have an option to disable the plugin for certain filetypes (e.g. `fzf`, `NvimTree`, etc) and buftypes (e.g. `nofile`, `terminal`).

Indent-blankline, for example, supports exclusions with both `filetype_exclude` and `buftype_exclude`

**Comment by echasnovski** [comment] 2022-05-26 18:59
Duplicate of #52.

At the moment I plan to support disabling only through `{g,b}:mini*_disable`. To make it easier for users, there is a [section in documentation with common situations](https://github.com/echasnovski/mini.nvim/blob/75477368c63e3dee65b2a39e6050391ef521f0b8/doc/mini.txt#L143-L184).

**Closed by echasnovski** 2022-05-26 18:59 UTC
Labels: feature-request, mini.indentscope

**Comment by ibhagwan** [comment] 2022-05-26 19:08
> Duplicate of #52.
> 
> At the moment I plan to support disabling only through `{g,b}:mini*_disable`. To make it easier for users, there is a [section in documentation with common situations](https://github.com/echasnovski/mini.nvim/blob/75477368c63e3dee65b2a39e6050391ef521f0b8/doc/mini.txt#L143-L184).

Oops, I missed that, ty @echasnovski for the quick response.
