### ISSUE TITLE
mini.ai module doesn't behave nicely with html

### ISSUE THREAD

**Issue by lucax88x** [echasnovski/mini.nvim#420] opened 2023-07-15 10:17 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

it doesn't recognize html tags correctly.

instead of 

### Neovim version

v0.10.0-dev-672+g33e1a8cd7 (nightly)

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

If you have a simple html, like

```html
    <div id="root">
      <p></p>
      <div></div>
    </div>
```

if you try to perform operations on the root div, like `dit` it should delete all the content of the root div.

### Expected behavior

```html
    <div id="root">
    </div>
```

### Actual behavior

 it's gonna delete until the internal div (so matching the first ending div, instead of HIS ending dif) and you end up having

```html
    <div id="root"></div>
    </div>
```

**Comment by echasnovski** [comment] 2023-07-15 10:32
'mini.ai' uses Lua patterns to search for the target region. This will inevitably result into false positives. It is a [known issue which won't be resolved'](https://github.com/echasnovski/mini.nvim/blob/2b37c5e1d2a3f62ba4060a819f17d8d976018928/doc/mini-ai.txt#L43-L45).

Tags is a main source of such false positives. In particular, I couldn't find a way to make it work with nested similar tags, like `<div>`s in your example. My suggestion would be to use tree-sitter grammar to properly parse structure and textobjects to have relevant queries. See [this comment](https://github.com/echasnovski/mini.nvim/issues/110#issuecomment-1212277863) for more information.

This is a duplicate of #156 and #304.

**Closed by echasnovski** 2023-07-15 10:32 UTC
Labels: mini.ai
