### ISSUE TITLE
mini.test window doesn't close

### ISSUE THREAD

**Issue by will-lynas** [echasnovski/mini.nvim#1216] opened 2024-09-14 09:20 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.test

### Description

https://github.com/user-attachments/assets/e4452431-56ef-484b-99d7-6d957e82bbc3

Leaving mini.test floating window removes the background but not the text, and does not close the window.

### Neovim version

0.10.1

### Steps to reproduce

- mini.test version 0.13.0
- `MiniTest.run`
- Leave the mini test window

### Expected behavior

The window closes

### Actual behavior

The window remains open, but the background disappears

**Comment by echasnovski** [comment] 2024-09-14 09:34
Thanks for the issue!

How do you do the "Leave the mini test window" step? If it is a `<C-w>p` or `<C-w>w` (or similar), then it is expected as the window is not closed with that. To close the window, press `q`.

I'd guess that it appears that "... window removes the background but not the text" due to color scheme.

**Comment by will-lynas** [comment] 2024-09-14 09:43
Yeah, with `<C-w>w`. I'm actually using [alexghergh/nvim-tmux-navigation](https://github.com/alexghergh/nvim-tmux-navigation) but I guess it amounts to the same thing.

I didn't realise this was intended. A lot of the plugins I use close popups if they lose focus. What's the use case for them staying open?

**Comment by echasnovski** [comment] 2024-09-14 10:07
> What's the use case for them staying open?

Mostly two things:
- Robustly tracking lost focus for a window is not trivial. The best "easy" approach is to have it tracked inside autocommand for `WinLeave`, but there is no way to create autocommand local to a window, only buffer. There is now a 'winfixbuf' option to probably make these window-buffer a one-to-one relation, but it was introduced relatively recently (in 0.10.0).
- The window [can be configured](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-test.txt#L646-L650) to open in a regular split. Having window closed after lost focus in this case is not a good idea (because regular split is probably used to be more persistent). And in turn, having different behavior for custom and default windows also doesn't seem like a good idea.

You can have this set up by tweaking the default `buffer` reporter like this:

```lua
local test = require('mini.test')
local win_config = {
  relative = 'editor',
  width = math.floor(0.618 * vim.o.columns),
  height = math.floor(0.618 * vim.o.lines),
  row = math.floor(0.191 * vim.o.lines),
  col = math.floor(0.191 * vim.o.columns),
}
local reporter = test.gen_reporter.buffer({
  window = function()
    local win_id = vim.api.nvim_open_win(0, true, win_config)
    local au_opts = { once = true, callback = function() pcall(vim.api.nvim_win_close, win_id, true) end }
    vim.api.nvim_create_autocmd('WinEnter', au_opts)
  end,
})
test.setup({ execute = { reporter = reporter } })
```

Closing as an expected behavior.

**Closed by echasnovski** 2024-09-14 10:07 UTC
Labels: mini.test, needs-repro
