### ISSUE TITLE
Line operations

### ISSUE THREAD

**Issue by suliatis** [echasnovski/mini.nvim#734] opened 2024-03-07 09:00 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bracketed

### Description

The one keymap pair I miss from `vim-unimpaired`, compared to `mini.bracketed` are `[<Space>` and `]<Space>` to add lines above and below the current line. I using this a lot and wondering if you open to accept a PR for this.

For clarity here is the corresponding documentation from vim-unimpaired:

```
LINE OPERATIONS                                 *unimpaired-lines*

                                                *[<Space>*
[<Space>                Add [count] blank lines above the cursor.

                                                *]<Space>*
]<Space>                Add [count] blank lines below the cursor.
```

**Comment by echasnovski** [comment] 2024-03-07 09:03
Thanks for the suggestion!

This is a part of ['mini.basics'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-basics.md) under [`go` and `gO`](https://github.com/echasnovski/mini.nvim/blob/70d8a16399ca6df759d20bea302d6dfd710a1df8/doc/mini-basics.txt#L234-L235). Also, unlike 'vim-unimpaired', it is dot-repeatable out of the box.

Closing as duplicate of #587 and #375.

**Closed by echasnovski** 2024-03-07 09:03 UTC
Labels: feature-request, mini.bracketed

**Comment by suliatis** [comment] 2024-03-07 09:07
Oh I didn't know about that. I will checkout. Thanks.
