### ISSUE TITLE
mini.splitjoin: Does not work properly for Nix lists

### ISSUE THREAD

**Issue by mrjones2014** [echasnovski/mini.nvim#386] opened 2023-06-24 18:48 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.splitjoin

### Description

Nix lists are a little unique in that they don't use comma separators, just spaces, e.g:

```nix
{ pkgs, ... }: {
  home.packages = with pkgs; [ cachix xclip signal-desktop qbittorrent ];
}
```

### Neovim version

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Steps to reproduce

1. In a Nix file with contents like so:

```nix
{ pkgs, ... }: {
  home.packages = with pkgs; [ cachix xclip signal-desktop qbittorrent ];
}
```
2. Try to split the list onto multiple lines with `mini.splitjoin`

### Expected behavior

The resulting code should be this:

```nix
{ pkgs, ... }: {
  home.packages = with pkgs; [
    cachix
    xclip
    signal-desktop
    qbittorrent
  ];
}
```

### Actual behavior

The actual resulting code looks like this:

```nix
{ pkgs, ... }: {
  home.packages = with pkgs; [
    cachix xclip signal-desktop qbittorrent
  ];
}
```

**Comment by echasnovski** [comment] 2023-06-25 07:43
Thanks for the issue!

'mini.splitjoin' is customizable for what it considers to be an argument and what action it will perform before/after split/join. Here is [documentation of available `config` settings](https://github.com/echasnovski/mini.nvim/blob/445f73cff53987432cb9eea41c4dc25e4a4c3c04/doc/mini-splitjoin.txt#L107).

This can also be [customized per filetype](https://github.com/echasnovski/mini.nvim/blob/445f73cff53987432cb9eea41c4dc25e4a4c3c04/doc/mini-splitjoin.txt#L58-L60). In your case I suggest creating file 'after/ftplugin/nix.lua' in your config directory which creates proper `vim.b.minisplitjoin_config`.

After some trial and error, here is something that seems to work good enough:

```lua
if _G.MiniSplitjoin ~= nil then
  -- Pad square brackets with single space after join
  local pad_brackets = MiniSplitjoin.gen_hook.pad_brackets({ brackets = { '%b[]' } })

  vim.b.minisplitjoin_config = {
    detect = { separator = '[^[]%f[ ] +' },
    join = { hooks_post = { pad_brackets } },
  }
end
```

It would have been shorter if there were no padding inside `[]` because 'mini.splitjoin' treats first space as separator too.
If you need it to work not only with square brackets, then some hackery here might be needed.

Closing as not a bug.

**Closed by echasnovski** 2023-06-25 07:43 UTC
Labels: mini.splitjoin

**Comment by mrjones2014** [comment] 2023-06-25 11:59
Perfect thanks!

**Comment by mrjones2014** [comment] 2023-06-29 13:33
@echasnovski this seems to break splitjoin for Nix attribute sets 🙁 🤔 

e.g. if I have this, where `|` before `programs` represents my cursor position:

```nix
{ pkgs, ... }: { |programs.librewolf = { enable = true; }; }
```

it turns into this:

```nix
{ pkgs, ... }: {
  p
  rograms.librewolf
  =
  { enable = true; };
}
```

Any way to fix that with a treesitter query or something? The default behavior of `mini.splitjoin` works for Nix attribute sets but not Nix lists.

**Comment by echasnovski** [comment] 2023-06-29 14:27
> Any way to fix that with a treesitter query or something? The default behavior of `mini.splitjoin` works for Nix attribute sets but not Nix lists.

I don't think so. 'mini.splitjoin' is designed to have only one pattern to detect separator. In your original case it was space. It is possible to use `separator = '[ ;]'` but this won't work properly.

It is also designed to only work with Lua patterns, no tree-sitter integration is possible. If you want something more complex, there is [Wansmer/treesj](https://github.com/Wansmer/treesj) or [CKolkey/ts-node-action](https://github.com/CKolkey/ts-node-action).

**Comment by mrjones2014** [comment] 2023-06-29 14:50
Makes sense, thanks 👍
