### ISSUE TITLE
Problem with mini.ai inside/around tag (`it`/`at`)

### ISSUE THREAD

**Issue by amadanmath** [echasnovski/mini.nvim#735] opened 2024-03-07 11:50 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

The "tag" text object naively selects until it finds a matching closing tag, disregarding possible nesting. In this, it seems to be a regression over the native implementation of the tag text object, which works as expected (to the extent I tested it).

### Neovim version

NVIM v0.9.5

### Steps to reproduce

Using this `min-init.lua`:

```
local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "echasnovski/mini.ai",
    config = function(_, opts)
      require("mini.ai").setup(opts)
    end,
  },
}, { root = "/tmp/lazy" })
```

and this `test.html` sample file:

```
<div>
  <label>
    <div>
    </div>
  </label>
</div>
```

run NeoVim like this:

```
nvim --clean -u min-init.lua test.html
```

Sitting at the start of the file, press `vat`. An analogous problem can also be observed with `vit`.

### Expected behavior

I expect `vat` to select the whole file (around the outermost `<div>`). In fact, this is exactly the result NeoVim does by default. Running clean NeoVim:

```
nvim --clean -u none test.html
```

`vat` selects the following — correct — region:

```
<div>
  <label>
    <div>
    </div>
  </label>
</div>
```

Similarly, the expected selection for `vit` (also observed with clean NeoVim) is

```
  <label>
    <div>
    </div>
  </label>
```

### Actual behavior

The selection incorrectly ends after the _inner_ div is closed, resulting in a selection:

```
<div>
  <label>
    <div>
    </div>
```

In the same way, the `vit` selection ends up as:

```
  <label>
    <div>
```

**Comment by echasnovski** [comment] 2024-03-07 13:03
'mini.ai' uses Lua patterns to search for the target region. This will inevitably result into false positives. It is a [known issue which won't be resolved'](https://github.com/echasnovski/mini.nvim/blob/70d8a16399ca6df759d20bea302d6dfd710a1df8/doc/mini-ai.txt#L44-L45).

Tags is a main source of such false positives. In particular, I couldn't find a way to make it work with nested similar tags, like `<div>`s in your example. My suggestion would be to use tree-sitter grammar to properly parse structure and textobjects to have relevant queries. See [this comment](https://github.com/echasnovski/mini.nvim/issues/110#issuecomment-1212277863) for more information.

Closing as duplicate of #156, #304, and #420.

**Closed by echasnovski** 2024-03-07 13:03 UTC
Labels: duplicate, wontfix, mini.ai
