### ISSUE TITLE
add post write hook function for mini.session

### ISSUE THREAD

**Issue by edshamis** [echasnovski/mini.nvim#67] opened 2022-04-28 16:18 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.session

### Description

I'd like to convert absolute pathes to relative ones in session file to make it possible to share global sessions across devices

**Comment by echasnovski** [comment] 2022-04-29 15:06
I personally store session files in designated directory inside `~/.config/nvim`. That directory is git-ignored because: a) it is a major privacy issue to have possible file paths (even relative) out in the public; b) it is not that hard to reproduce session manually if you need to.

Not sure I remember a dedicated `SessionWrite(Post)` event. Quick googling didn't result into anything also. What I would do here depends on the exact use case:
- If you want to patch automatically, you could use a `VimLeavePre` event (which ['mini.sessions'](https://github.com/echasnovski/mini.nvim/blob/8c278019a68c80724ac05e55139b3a73d718dd75/lua/mini/sessions.lua#L81) itself is using). Make sure to create your autocommand *after* `require('mini.sessions').setup()`.
- If you call `MiniSessions.write()` manually, than write a wrapper which calls `MiniSessions.write()` and then makes your desired changes.
- A **very dirty** hack is to emulate hook by reassigning `MiniSessions.write()`. It *should* work for both previous cases. So something like this *should* work (not tested):
```lua
require('mini.sessions').setup()

_G.original_write = MiniSessions.write

MiniSessions.write = function(...)
  _G.original_write(...)
  -- Your code goes here
end
```

**Closed** 2022-04-30 14:52 UTC
Labels: feature-request, mini.sessions

**Comment by echasnovski** [comment] 2022-04-30 14:55
Thanks again for suggestion! Should be implemented in latest `main` branch. I opted into more complete set of hooks, so now you can use `MiniSessions.config.hooks.pre.write` for your case.

This ended up being very unbalanced though: relatively small implementation, quite large testing and documentation.

**Comment by edshamis** [comment] 2022-04-30 18:02
Wow thanks! I'll try it out
