### ISSUE TITLE
No fold error when opening session from mini.starter

### ISSUE THREAD

**Issue by JoseConseco** [echasnovski/mini.nvim#57] opened 2022-04-03 14:16 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.Sessions

### Description

![image](https://user-images.githubusercontent.com/13521338/161432212-bbd2afa2-586b-475c-b370-4486c3ca1e67.png)
I get this error from time to time.

### Neovim version

NVIM v0.7.0-dev+1129-g30c9c8815

### Steps to reproduce

1. Open session from mini starter
2. Sometimes no fold error will popup

### Actual behavior

Not sure is this is mini problem, since the line mentioned in error, has just  session so xxx command.

**Comment by echasnovski** [comment] 2022-04-03 15:21
Yeah, I am too getting it from time to time. I think I got those even when was using 'mhinz/vim-startify'. Fairly confident that this is an issue from Vim (not even Neovim), but never managed to create a stable reproducible example. If you (or any other) could do that, that would be awesome.

**Comment by echasnovski** [comment] 2022-05-09 15:33
I finally had time to investigate this. Turned out to be not *that* complicated.

Vim's session file itself causes this error when file with folds is edited outside session in a way that removes expected folds. At the moment I think it is a good idea to keep these error messages in the sake of being more explicit and reduce usage surprise when `MiniSessions.read()` behaves differently than `:source`.

Another issue here is that `MiniSession.read()` doesn't work properly when session file throws error (it stops sourcing script entirely, see #75), but there seems to be nothing I can do within this plugin (again, see #75).

Reproducible example:
- Open Neovim: `nvim --clean -u NONE`.
- `:set foldmethod=indent`.
- `:edit folded-file` and add lines `a`, `\ta`, `\ta`, `a`, `\ta`, `\ta` and save it with `:w`.
- Type `zM` to close all folds.
- Open first fold: `:2`, `zo`.
- `:mksession! tmp-session` 
- `:q`.  Now `tmp-session` file should contain line `2` followed by `normal! zo`. Which means it will try to go to line 2 and open fold there. If no such fold is found (like if lines in 'folded-file' are erased completely), it will throw `E490: No fold found`.
- `nvim --clean -u NONE folded-file`, erase all lines with `dG`, save and quit with `:x`.
- `nvim --clean -u NONE` and `:source tmp-session`. This will throw the error.

Closing, as this is not an error from 'mini.sessions'.

**Closed by echasnovski** 2022-05-09 15:33 UTC
Labels: bug, help wanted, mini.sessions

**Comment by JoseConseco** [comment] 2022-05-09 18:47
ok, thanks for the last example. This made everything clear.
