### ISSUE TITLE
mini.pairs: Triple quotes / backticks

### ISSUE THREAD

**Issue by keonly** [echasnovski/mini.nvim#1005] opened 2024-07-02 09:26 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pairs

### Description

When typing triple quotes / backticks (e.g., raw string in Python, code block in Markdown), mini.pairs writes only one quote / backtick behind the cursor.

mini.pairs seems to be understanding each symbol separately; when three symbols are entered, it adds one symbol after the first one, thinks the second symbol is the closing symbol for the first one, and adds one symbol after the third one.

### Neovim version

0.10.0

### Steps to reproduce

1. Open a file.
2. Enter insert mode.
3. Write three quotes / backticks.

### Expected behavior

Three quotes / backticks are generated behind the cursor.

### Actual behavior

Only one is generated behind the cursor.

https://github.com/echasnovski/mini.nvim/assets/70371393/970e09bf-edf4-4568-83de-dbd34be01b32

**Comment by echasnovski** [comment] 2024-07-02 10:26
Thanks for the issue!

This is an intended behavior because [pair can consist only from two characters](https://github.com/echasnovski/mini.nvim/blob/35422e90b0de232245e2b1d3b3737a7c419d377b/doc/mini-pairs.txt#L123) and customization can be done [only based on two-character cursor neighborhood](https://github.com/echasnovski/mini.nvim/blob/35422e90b0de232245e2b1d3b3737a7c419d377b/doc/mini-pairs.txt#L9-L10) . See #31 for more details.

Closing as duplicate.

**Closed by echasnovski** 2024-07-02 10:26 UTC
Labels: mini.pairs
