### ISSUE TITLE
mini.bufremove: vim.cmd('bprevious') throw errors about no listed buffer

### ISSUE THREAD

**Issue by towry** [echasnovski/mini.nvim#393] opened 2023-06-28 03:08 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.bufremove

### Description

```txt
E5108: Error executing lua: ...orkspace/git-repos/mini.bufremove/lua/mini/bufremove.lua:143: E
rror executing lua: vim/_editor.lua:402: nvim_exec2(): Vim(bprevious):E85: There is no listed 
buffer         
```

### Neovim version

NVIM v0.10.0-dev-1904+g3bf887f6e-Homebrew

### Steps to reproduce

No need.

https://github.com/echasnovski/mini.bufremove/blob/14805473144fffbd019d07e51bed2d176e065ee9/lua/mini/bufremove.lua#L157

Can be easily fixed by using `pcall`.

### Expected behavior

harmless error should be suppressed.

### Actual behavior

harmless error was thrown.

**Comment by echasnovski** [comment] 2023-06-28 04:35
Please, provide reproducible example instead of "No need". I've never encountered this error during around two years of usage.

**Comment by towry** [comment] 2023-06-28 05:58
@echasnovski 

```lua
vim.g.mapleader = ' '

local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { 'nvim-lua/plenary.nvim' },
  { 'stevearc/dressing.nvim', opts = {} },
  {
    "echasnovski/mini.starter",
    enabled = true,
    config = true,
  },
  {
    enabled = true,
    'echasnovski/mini.bufremove',
    keys = {
      {
        '<S-q>',
        function()
          require('mini.bufremove').wipeout(0)
          vim.cmd('q')
        end,
        desc = 'Close',
      }
    },
  }
  -- add any other pugins here
}

require('lazy').setup({
  spec = plugins,
  root = root .. '/plugins',
  defaults = {
    lazy = false,
  },
  state = root .. '/lazy/state.json',
  performance = {
    cache = {
      enabled = false,
    }
  }
})

-- add anything else here
vim.opt.termguicolors = true
vim.cmd([[colorscheme default]])
```

1. create `init.lua` with above content inside `/tmp/`.
2. cd `/tmp`
3. nvim -u init.lua
4. press key `<shift-q>` to trying close it.

**Comment by echasnovski** [comment] 2023-06-28 08:36
Yes, I can reproduce this when closing 'mini.starter' buffer right after opening Neovim. Not when closing buffer after opening Neovim without 'mini.starter', though.

This is a rather rare and unintended use case, but I'll see if adding `pcall()` here won't have side effects.

Meanwhile, using `pcall()` in the mapping for `wipeout()` can help here.

**Closed** 2023-06-29 13:11 UTC
Labels: bug, mini.bufremove

**Comment by echasnovski** [comment] 2023-06-29 13:18
This now should be resolved on latest `main`.
