### ISSUE TITLE
Mini.ai breaks `vim.on_key()` in combination with some other plugins

### ISSUE THREAD

**Issue by NStefan002** [echasnovski/mini.nvim#1105] opened 2024-08-01 21:01 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

This is an "I need information/help" type of issue rather than a "there's something wrong with your plugin" type.

Someone opened [this issue](https://github.com/NStefan002/screenkey.nvim/issues/36) in one of my plugin repositories. Personally, I don't use `mini.ai` and I don't know much about it or custom text objects, but when I installed it, I was able to consistently reproduce some strange behaviors.

When trying to display typed keys (caught by `vim.on_key()`) with `nvim-notify` or `screenkey.nvim`, after using some of the text objects defined by `mini.ai`, the `vim.on_key()` breaks without any error.

**Note:** An interesting thing is that `vim.on_key()` continues to work as it should when displaying keys in the Vim command line using `print()`. My guess is that this has something to do with scheduling via `vim.schedule` and/or `vim.schedule_wrap` as both `nvim-notify` and `screenkey.nvim` use that.

Do you have any idea what could be causing this, and is there a way to fix it (not necessarily in `mini.ai`)? If you don't have time or don't want to bother with this, please close this issue. Thanks!

### Neovim version

0.10.1

### Steps to reproduce

1. `nvim -nu repro.lua`
2. `:Screenkey toggle`
3. type anything 
4. use some `mini.ai` defined txtobjs like `di"`
5. type anything 

repro.lua:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
	{
		"echasnovski/mini.ai",
		config = function()
			require("mini.ai").setup()
		end,
	},
	{
		"NStefan002/screenkey.nvim",
		version = "*",
	},
	{
		"rcarriga/nvim-notify",
		config = function()
			local notify = require("notify")
			notify.setup({
				render = "default",
				stages = "slide",
				timeout = 7000,
			})
			-- use notify as a default way of showing notifications
			vim.notify = notify

			local notify_print = function(...)
				local print_safe_args = {}
				local _ = { ... }
				for i = 1, #_ do
					table.insert(print_safe_args, tostring(_[i]))
				end
				notify(table.concat(print_safe_args, " "), "info")
			end

			vim.on_key(function(key, typed)
				notify_print(key, typed)
			end, vim.api.nvim_create_namespace("w-notify"))

			vim.on_key(function(key, typed)
				print(key, typed)
			end, vim.api.nvim_create_namespace("wo-notify"))
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
```

### Expected behavior

`vim.on_key()` should continue working.

### Actual behavior

`vim.on_key()` stops working.

**Comment by echasnovski** [comment] 2024-08-02 14:41
Thanks for the detailed issue!

Yeah, I can reproduce with the provided config. I first thought that it has something to do with 'mini.ai' using `getcharstr()` to get a key, but my quick testing didn't confirm. Other than that, I can not see an obvious problem here. I'll have to take closer look.

**Comment by echasnovski** [comment] 2024-08-02 16:40
The 

> **Note:** An interesting thing is that `vim.on_key()` continues to work as it should when displaying keys in the Vim command line using `print()`. My guess is that this has something to do with scheduling via `vim.schedule` and/or `vim.schedule_wrap` as both `nvim-notify` and `screenkey.nvim` use that.

The guess is correct, but not in the right direction :) The core of the issue seems to be that both plugins don't use `vim.schedule()` *enough*.

Here is how this could've been debugged:
- Read `:h on_key()` to see a note: "• {fn} will be removed on error.". Make an educated guess that there is an error going on.
- Modify the code to call functions safely while logging results. Here is what my first pass did:
    ```lua
        -- Everything else is the same
        _G.log = {}
        vim.on_key(function(key, typed)
          table.insert(_G.log, { key = key, typed = typed, call = { pcall(notify_print, key, typed) } })
        end, vim.api.nvim_create_namespace("w-notify"))

        -- vim.on_key(function(key, typed)
        -- 	print(key, typed)
        --      table.insert(_G.log, )
        -- end, vim.api.nvim_create_namespace("wo-notify"))
    ```
- Start Neovim with the config and try to replicate a behavior. See that there is an entry in the `_G.log` (with `=_G.log`) with the following content: ` call = { false, "....repro/plugins/nvim-notify/lua/notify/render/default.lua:18: E565: Not allowed to change text or change window" }`.

So there indeed is an error which tells us that some action is being done when it should not be. And indeed the error goes away if function in `on_key()` is wrapped with `vim.schedule_wrap()`. Like so:

```lua
vim.on_key(
  vim.schedule_wrap(function(key, typed)
    notify_print(key, typed)
  end),
  vim.api.nvim_create_namespace("w-notify")
)
```

------

But why the error in the first place? Well, my initial guess was correct and it indeed has to do with `getcharstr()`. More precisely, when it is used inside expression mapping:
- Calling `getcharstr()` "blocks" Neovim until user presses a key.
- As it is inside "expression" mapping (see `:h :map-expression`), there should not be any editing done (there is a whole paragraph about that which starts with "Be very careful about side effects!").

You can reproduce the same behavior with the following mapping without 'mini.ai':

```lua
-- For example, press `d`, followed by `e` and then `w`.
-- It will act like `dw`
vim.keymap.set("o", "e", function() return vim.fn.getcharstr() end, { expr = true })
```

------

Closing as not an issue with 'mini.ai'.

**Closed by echasnovski** 2024-08-02 16:40 UTC
Labels: mini.ai

**Comment by NStefan002** [comment] 2024-08-02 20:37
Thank you for the help, great tips, and for your time!
