### ISSUE TITLE
[mini.animate] Text scrambled when pasting long line of text

### ISSUE THREAD

**Issue by nikolasetiawan** [echasnovski/mini.nvim#275] opened 2023-03-17 05:31 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

when pasting long line of text from global clipboard using cmd-v (in mac), the text line are all scrambled up.

Probably due to the cursor going all over the place while pasting in mac is 1 line at a time.

does not happen if pasting done through "+p

any way to fix this?

### Neovim version

0.8.3

### Steps to reproduce

1. open empty buffer
2. copy long text (100-200 lines)
3. paste using cmd-v

### Expected behavior

text pasted in order

### Actual behavior

text scrambled

**Comment by echasnovski** [comment] 2023-03-17 17:02
I can not reproduce this, unfortunately. I use EndeavourOS in `st` terminal and pasting with `Shift + Ctrl + v` work as expected.

Does this happen if you disable animation for scrolling? Like with `:lua MiniAnimate.config.scroll.enable = false`?

**Comment by echasnovski** [comment] 2023-03-20 11:57
> @echasnovski this does not happen when I disable scrolling animation with :lua MiniAnimate.config.scroll.enable = false.
> 
> is there a way to disable it temporarily when pasting?

There seems to be `vim.paste()` function almost just for this purpose. Try putting this code in your config:

```lua
local original_paste = vim.paste
vim.paste = function(...)
  local cache_enable_scroll = MiniAnimate.config.scroll.enable
  MiniAnimate.config.scroll.enable = false

  pcall(original_paste, ...)

  MiniAnimate.config.scroll.enable = cache_enable_scroll
end
```

**Comment by echasnovski** [comment] 2023-03-30 07:35
@nikolasetiawan, does this solution help you?

**Comment by nikolasetiawan** [comment] 2023-04-05 10:56
Thank you for finding a solution! But I am not entirely sure where to put this code in.

currently, my workaround is to paste long text using "+p, which skips animation entirely.
besides, I rarely encounter text long enough to show the bug.

**Comment by echasnovski** [comment] 2023-04-05 11:13
> Thank you for finding a solution! But I am not entirely sure where to put this code in.
> 
> currently, my workaround is to paste long text using "+p, which skips animation entirely. besides, I rarely encounter text long enough to show the bug.

You can put it anywhere in your Neovim config. On choice would be right after you call `require('mini.animate').setup()`.

I can not reproduce this, so can not close this without some verified solution or more details about how to reproduce this.

**Comment by nikolasetiawan** [comment] 2023-04-18 03:08
unfortunately did not work when I tried adding that to my config. I've got warning
```
Lua Diagnostics.: Duplicate field `paste`.
```
instead.

but I think you can close this since I've found the "+p workaround

**Comment by echasnovski** [comment] 2023-04-18 06:51
> unfortunately did not work when I tried adding that to my config. I've got warning
> 
> ```
> Lua Diagnostics.: Duplicate field `paste`.
> ```
> 
> instead.

It seems like a warning from LSP diagnostic. Did you try to actually add this and then run it?

> but I think you can close this since I've found the "+p workaround

Yeah, I think this should be closed. But mostly because I can't reproduce and overriding `vim.paste` looks like it should work.

**Closed by echasnovski** 2023-04-18 06:51 UTC
Labels: bug, mini.animate
