### ISSUE TITLE
mini.ai: `custom_textobjects` ignores captures that are triggered by a nested motion

### ISSUE THREAD

**Issue by westernwontons** [echasnovski/mini.nvim#754] opened 2024-03-19 16:28 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Take the following `custom_textobjects` config:

```lua
custom_textobjects = {
            xv = spec_treesitter { a = "@pair.value", i = "@pair.value" },
        }
```

Where the `@pair.value` looks like the following for Lua:

```scheme
(table_constructor
  (field
    value: [(string) (attribute) (identifier) (function_call) (function_definition)] @pair.value))
```

If the key (xv) is only a single character (tested with `x` and `v`), the capture is recognised and managed by mini.ai, otherwise not.

### Neovim version

NVIM v0.10.0-dev-2488+g5d4e1693c Build type: Release LuaJIT 2.1.1707061634

### Steps to reproduce

Attached tarball has the necessary files. Open with the following command:

NVIM_DATA_MINIMAL=/tmp/minimal NVIM_APP_NAME="nvim-minimal" nvim -u minimal.lua

Exit, then open `test.lua`

It contains the following:

```lua
local t = {
    key = "value",
    otherkey = {
        ["nested_table_key"] = "someotherstuff",
    },
}
```

Move your cursor onto "nested_table_key"
Type `viNxv`
It should select the "value" up above

Open minimal.lua and replace the 'xv' key in mini.ai setup with 'x'

When tried again, it selects "value" as expected.

[minimal.tar.gz](https://github.com/echasnovski/mini.nvim/files/14653530/minimal.tar.gz)

### Expected behavior

Two character capture triggers are recognised

### Actual behavior

Two character capture triggers are not recognised

**Comment by echasnovski** [comment] 2024-03-19 16:37
If I understand correctly, then the issue is about `custom_textobjects = { xv = {...} }` not working as custom textobject. This is an expected behavior because [only single character](https://github.com/echasnovski/mini.nvim/blob/9968f6e221ae7bdac57a910c5bf2026186aa023c/doc/mini-ai.txt#L37-L41) can to be a textobject identifier.

Closing as not an issue.

**Closed by echasnovski** 2024-03-19 16:37 UTC
Labels: mini.ai

**Comment by westernwontons** [comment] 2024-03-19 16:46
Would it be possible to convert the issue into a feature request then? I'd be happy to hack something together!

**Comment by echasnovski** [comment] 2024-03-19 17:00
> Would it be possible to convert the issue into a feature request then? I'd be happy to hack something together!

Sorry, no. There is no good way to implement this feature under current design.

The main issue here is that it should be allowed to spend any amount of time to enter textobject identifier. If that is the case, then if more than one character for textobject identifier is allowed, then there should be a mechanism to know when a single character (majority of cases) is the target. Which itself implies that there should be at least an extra keystroke to tell 'mini.ai' that current input is the final textobject id, and that is bad.

**Comment by westernwontons** [comment] 2024-03-19 17:06
Understood
