### ISSUE TITLE
Git highlights are excessively saturated with randomhues

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#538] opened 2023-10-23 22:13 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

hues

### Description

Git highlights are excessively saturated with randomhues, which clash with the overall colorscheme due to poor contrast.

### Neovim version

0.9.2

### Steps to reproduce

```diff
cat <<EOF > minimal.patch
-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue dignissim tristique.
+Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue dignissim tristique.
EOF
```

1. `nvim -nu minimal.patch`
2. `vim.cmd [[colorscheme randomhue]]`

### Expected behavior

Highlight that adhere to randomhue / mini.hues colorspace.

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/de2a4064-89a8-46e9-bfab-9b7254504c59)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/ab8df6ac-46bd-47c0-a098-7dae14892292)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/6aab88a8-fda6-4729-aaab-3748cf43b73b)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/ba2f08f8-57f6-4e06-88e1-a1878413d503)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/66afc303-d4ef-48f0-98bc-6d79265c881b)

**Comment by echasnovski** [comment] 2023-10-24 07:03
Thanks for the creating this!

This is by design. The diff highlight groups [have colored backgrounds](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L663-L665) which [are](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L347) [computed](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L353) [to have](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L356) same lightness as background and same chroma as text. Having different lightness would make it stand out in a more unnatural way (subjectively) than different chroma. Having smaller chroma would make them too indistinguishable to background in most cases.

What would be your preferred way of coloring those?

**Comment by wroyca** [comment] 2023-10-24 12:01
> Thanks for the creating this!
> 
> This is by design. The diff highlight groups [have colored backgrounds](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L663-L665) which [are](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L347) [computed](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L353) [to have](https://github.com/echasnovski/mini.nvim/blob/66e3cdceaba8c0cd089d6f42cb95e04355718f7a/lua/mini/hues.lua#L356) same lightness as background and same chroma as text. Having different lightness would make it stand out in a more unnatural way (subjectively) than different chroma. Having smaller chroma would make them too indistinguishable to background in most cases.
> 
> What would be your preferred way of coloring those?

Great question! But, it's also quite subjective. I believe diff should be considered just as important as code itself. This means that, in general, using brighter and more "eye-catching" colors for the foreground against a dimmer background seems to strike the right balance. A prime illustration of this can be found in Neogit README:

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/f88977de-bffe-4c52-b8f6-7334f1db95c5)

**Comment by echasnovski** [comment] 2023-10-24 12:16
Well, yes, it is a bit subjective. The 'mini.base16' takes similar approach on what you describe. However, during work on 'mini.hues' I took into account pointers from #240. That is, use background to differentiate diff parts so as to see the code highlighting. I think I like it better.

Besides, they can be customized manually. Granted, not quite easy with 'randomhue', but possible. For example, by linking to `DiagnosticOk`, `DiagnosticWarn`, and `DiagnosticError`.

Thanks again for the suggestion, but I am going to close this as not planned.

**Closed by echasnovski** 2023-10-24 12:16 UTC
Labels: feature-request, mini.hues

**Comment by wroyca** [comment] 2023-10-24 12:29
> Well, yes, it is a bit subjective. The 'mini.base16' takes similar approach on what you describe. However, during work on 'mini.hues' I took into account pointers from #240. That is, use background to differentiate diff parts so as to see the code highlighting. I think I like it better.
> 
> Besides, they can be customized manually. Granted, not quite easy with 'randomhue', but possible. For example, by linking to `DiagnosticOk`, `DiagnosticWarn`, and `DiagnosticError`.
> 
> Thanks again for the suggestion, but I am going to close this as not planned.

Fair enough - That said, would you be open to having an option to use either base16-style diff highlight or 'tokyonight'-ish style? This would make the transition from base16 to randomhue less less jarring overall

**Comment by echasnovski** [comment] 2023-10-24 12:34
> Fair enough - That said, would you be open to having an option to use either base16-style diff highlight or 'tokyonight'-ish style? This would make the transition from base16 to randomhue less jarring overall

Sorry, but no. Color schemes need only so much configuration and I feel that 'mini.hues' already reached its limit. The best suggestion from me here is to manually change those highlight groups (ideally, inside an autocommand for `ColorScheme` before calling `require('mini.hues').setup()`)

**Comment by wroyca** [comment] 2023-10-24 12:43
Here we go:

```lua
vim.api.nvim_create_autocmd("colorscheme", {
  pattern = "*",
  callback = function()
    -- single-color foreground; see discussions at:
    -- https://github.com/echasnovski/mini.nvim/issues/538
    vim.schedule(function ()
      vim.cmd[[highlight! link DiffAdd    DiagnosticOk]]
      vim.cmd[[highlight! link DiffChange DiagnosticWarn]]
      vim.cmd[[highlight! link DiffDelete DiagnosticError]]
    end)
  end
})
```
