### ISSUE TITLE
mini move selection lua command not working

### ISSUE THREAD

**Issue by DeepReef11** [echasnovski/mini.nvim#816] opened 2024-04-16 12:13 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

move

### Description

The following command doesn't work with a selection
lua MiniMove.move_selection("up")

I was able to get move_line working fine

### Neovim version

0.9.5

### Steps to reproduce

1. v to select
2. type :lua MiniMove.move_selection("up")
3. Nothing happen

### Expected behavior

Selection move up.

### Actual behavior

Nothing

**Comment by echasnovski** [comment] 2024-04-16 12:41
This is because when executed interactively from Command line, it is not in Visual mode already. Both `MiniMove.move_selection()` and `MiniMove.move_line()` are more oriented towards using it in mappings which don't change mode. Like [it is done in 'mini.move'](https://github.com/echasnovski/mini.nvim/blob/decd729b784c4f6cb775da335f3c8eecb846250c/lua/mini/move.lua#L422-L430).

Closing as expected behavior.

------

Is there any particular reason you wanted to use that interactively?

**Closed by echasnovski** 2024-04-16 12:41 UTC
Labels: question, mini.move

**Comment by DeepReef11** [comment] 2024-04-16 12:47
I'm trying to add arrow keybinding (and keep hjkl).

**Comment by echasnovski** [comment] 2024-04-16 13:36
> `vim.keymap.set('n', '<M-Up>', '<cmd>lua MiniMove.move_selection("up")<cr>', { desc = 'MiniMove line' })`

This should be Visual mode mapping, not Normal. Replace `'n'` with `'x'` and it should work.

**Comment by DeepReef11** [comment] 2024-04-16 14:26
Right! My mistake. Thanks a lot! 

I'm leaving this here in case someone is looking for the same binding:
```
      require('mini.move').setup()
      vim.keymap.set('x', '<M-Up>', '<cmd>lua MiniMove.move_selection("up")<cr>', { desc = 'MiniMove selection' })
      vim.keymap.set('x', '<M-Down>', '<cmd>lua MiniMove.move_selection("down")<cr>', { desc = 'MiniMove selection' })
      vim.keymap.set('x', '<M-Left>', '<cmd>lua MiniMove.move_selection("left")<cr>', { desc = 'MiniMove selection' })
      vim.keymap.set('x', '<M-Right>', '<cmd>lua MiniMove.move_selection("right")<cr>', { desc = 'MiniMove selection' })
      vim.keymap.set('n', '<M-Up>', '<cmd>lua MiniMove.move_line("up")<cr>', { desc = 'MiniMove line' })
      vim.keymap.set('n', '<M-Down>', '<cmd>lua MiniMove.move_line("down")<cr>', { desc = 'MiniMove line' })
      vim.keymap.set('n', '<M-Left>', '<cmd>lua MiniMove.move_line("left")<cr>', { desc = 'MiniMove line' })
      vim.keymap.set('n', '<M-Right>', '<cmd>lua MiniMove.move_line("right")<cr>', { desc = 'MiniMove line' })
```
