### ISSUE TITLE
Mini.AI breaks smart quote aliases from nvim.surround

### ISSUE THREAD

**Issue by pBorak** [echasnovski/mini.nvim#163] opened 2022-11-20 10:54 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini-ai

### Description

Hey first and foremost thank you for this great plugin. 
I have noticed that after adding `mini.ai` change and deleting surrounding quotes with `nvim.surround` [smart aliasing](https://github.com/kylechui/nvim-surround/blob/main/doc/nvim-surround.txt#L205) has stopped working and now it fails with 
```
(mini.ai) No textobject "a`" found covering region within 50 lines and `search_method = 'cover_or_next'`.
```

### Neovim version

0.8

### Steps to reproduce

1. Place the cursor inside the quote.
2. Hit either `csq`/`dsq` to change/delete quotes.

### Expected behavior

It should either change or delete surrounding quotes.

### Actual behavior

It fails with the following error:
```
(mini.ai) No textobject "a`" found covering region within 50 lines and `search_method = 'cover_or_next'`.
```

https://user-images.githubusercontent.com/45797239/202898288-a2ed675a-f68b-414f-b926-ac43912fe529.mov

**Comment by echasnovski** [comment] 2022-11-20 12:06
Thanks for the issue and positive feedback!

I don't think it is *broken* per se. The ``(mini.ai) No textobject "a`" found...`` is not an error but a message indicating that `` a` `` textobject is not found. This message is there to indicate that failure to find might be due to configuration (small neighborhood or not suitable search method) and not text itself. See #135.

Here is video of actually using it (with `cmdheight=1` and without 'noice.nvim'):

https://user-images.githubusercontent.com/24854248/202900904-2c750f6d-e7bf-42d7-a71d-1ae000db474f.mp4

This message is shown because 'nvim-surround' relies on `a` textobjects to find surrounding. So for `q` alias, it seems to try `a'`, `a"`, and `` a` `` consecutively. If some is not found, 'mini.ai' will show message.

Sorry, but I am not sure how to help here, to be honest. 'nvim-surround' heavily relies on usage of `a` textobject and I am not inclined to universally disable these messages. Here are possible options:
- Open same issue in 'nvim-surround' in hope that it can be fixed on its side (for example, by using `` silent normal va` `` to select textobject).
- Wait until #146 is implemented and disable all 'mini.ai' messages altogether.
- Use [mini.surround](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-surround.md) ;)

**Closed by echasnovski** 2022-11-20 12:06 UTC
Labels: bug

**Comment by pBorak** [comment] 2022-11-21 08:50
@echasnovski 
I need a bit more explanation because I think you misunderstood me a bit.
From your video, I can see you have different behavior than I do. So the whole issue wasn't about the message but broken behavior.
When you hit `csq'"`  - it changes quotes for you, when I do - it doesn't - that's what I intended to report. 
Going to dig a bit more to find out what it is.

**Comment by echasnovski** [comment] 2022-11-21 09:17
> @echasnovski I need a bit more explanation because I think you misunderstood me a bit. From your video, I can see you have different behavior than I do. So the whole issue wasn't about the message but broken behavior. When you hit `csq"` - it changes quotes for you, when I do - it doesn't - that's what I intended to report. Going to dig a bit more to find out what it is.

It probably is due to interference with some other plugin or Neovim setting. The usual approach to figuring it out is by disabling plugins in config until problem is gone. My initial guess would be that the problem is in either 'noice.nvim' or 'nvim-notify'.

I used all default config for 'mini.ai' and 'nvim-surround':
```lua
require('mini.ai').setup()
require('nvim-surround').setup()
```

**Comment by pBorak** [comment] 2022-11-21 09:33
Yep, you are completely right. `noice.nvim` introduces it.
If I disable it in `noice` it works correctly. Thanks for your help! ❤️ 
```
      {
        filter = {
          event = 'msg_show',
          kind = 'echomsg',
          find = 'No textobject',
        },
        opts = { skip = true },
      },

```

**Comment by echasnovski** [comment] 2023-02-24 16:54
Should be possible now to disable non-error messages with global/buffer-local variables. See [this comment](https://github.com/echasnovski/mini.nvim/pull/224#issuecomment-1444005833).
