### ISSUE TITLE
[mini.comment] textobject doesn't work for end-of-line comments

### ISSUE THREAD

**Issue by Bvngee** [echasnovski/mini.nvim#1431] opened 2024-12-26 10:47 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

I am aware that mini.comment is intentionally designed with linewise comments in mind and avoids dealing with inline block comments. However, it is very often that I'm working with some code and have a comment at the _end_ of a line that I want to use the mini.comment textobject on. I feel like this is within the scope of mini.comment, as they can be simply limited to the single line (you'd likely not have multiline linewise comments all at the end of code?)
Here's a video of what I'm talking about if it helps (I'm attempting `dgc`):

https://github.com/user-attachments/assets/8d546d63-5cc2-4dcd-843d-676b05f731ca

Thanks for your work on these amazing plugins :)

### Neovim version

0.9.5

### Steps to reproduce

1. use defaults of mini.comment
2. try `dgc` on a regular multi-line or full single-line comment
3. try `dgc` on a comment that's at the very end of a line of code/text
4. observe that only the first succeeds

### Expected behavior

the comment textobject (`gc` by default) should, at least by my first impression, cover both typical linewise comments and comments at the end of code / text.

### Actual behavior

the comment textobject only seems to work specifically for linewise comments that do NOT have code/text before them.

**Comment by Bvngee** [comment] 2024-12-26 10:55
Man, I just realized I completely forgot about the nvim 0.10 upstream commenting feature that was implemented based on mini.comment. I've just tested it though, and the textobject seems to behave in exactly the same way. So I think my question is still valid? Feel free to close this if its not.

**Comment by echasnovski** [comment] 2024-12-26 11:13
Thanks for the issue!

Having 'mini.comment' work on the "end of line" comments is indeed out of scope for 'mini.comment' because those comments are not linewise. Only "whole line" comments are in scope, mostly for reducing complexity. Otherwise detecting proper "end of line" comments is a significant challenge. For example, the comment leader can be inside a string or "end of line" comment itself, like this:

```lua
local a = '-- not a comment'
local b = "-- not a comment"
local c = [[-- not a comment]]
local d = 1 -- comment within -- comment
```

Unfortunately, I can also not reproduce the deletion of next line which follows the "end of line" comment which I can see from the screencast. Is it something that is indeed happening? If so, could you try reproducing it with only 'mini.comment' and possibly some other options that affect it?

**Comment by Bvngee** [comment] 2024-12-27 06:32
Hi, thanks for the quick response!

I see your point with the difficulty of implementing end-of-line comments, that makes sense.

> I can also not reproduce the deletion of next line which follows the "end of line" comment

I think what you're seeing is just the window scrolling horizontally when I move to the end of the line due to the small window size, not anything being deleted. Sorry for the confusion :P

I'm curious if you have any suggestions for how I _could_ accomplish this? I really love having access to the `gc` textobject but it just feels incomplete to not work on end-of-line comments. I tried adding a mini.ai treesitter textobject for `@comment.outer`, but that seems to work differently with multiple consecutive linewise comments (it only operates on the cursor's _current_ line, im guessing due to how the tree represents comments) and requires keybinds with a/i followed by a character instead of just gc. Or maybe I just deal with it instead, haha.

Also, slightly unrelated, is there anywhere I can see a comparison between nvim 0.10's built-in commenting vs mini.comment? I'm unsure based on the readme/help file if I'll need to keep this plugin around after I update.

Anyways, since this seems to be outside the scope of mini.comment, feel free to close this issue any time, and thanks for your help!

**Comment by echasnovski** [comment] 2024-12-27 12:35
> I'm curious if you have any suggestions for how I _could_ accomplish this?

Other than writing own textobject (almost) from scratch, I don't know about the way to achieve that relatively pain free.

> Also, slightly unrelated, is there anywhere I can see a comparison between nvim 0.10's built-in commenting vs mini.comment? I'm unsure based on the readme/help file if I'll need to keep this plugin around after I update.

Built-in commenting in Neovim>=0.10 is a toned down version of 'mini.comment', quite literally. The rule of thumb is if you use `require('mini.comment').setup()` (i.e. no configuration), then using built-in commenting might be just fine, because they are 99% the same. If you want/need extra configuration from 'mini.comment' (like custom commentstring, hooks, etc.), then 'mini.comment' is the way to go.

------

Closing this as the current way 'mini.comment' works (only for per line commenting) is intended and won't change.

**Closed by echasnovski** 2024-12-27 12:35 UTC
Labels: mini.comment, needs-repro

**Comment by llakala** [comment] 2025-06-26 04:17
> Other than writing own textobject (almost) from scratch, I don't know about the way to achieve that relatively pain free.

With only moderate amounts of pain, I was able to achieve a working implementation of this using `mini.ai`! It only triggers the new logic when necessary - in all other cases, it falls back to the `mini.comment` implementation.
```lua
require("mini.ai").setup({
  custom_textobjects = {
    c = function()
      local line = vim.api.nvim_get_current_line()

      -- Get the commentstring up until %s (including the space).
      local commentstr = vim.bo.commentstring:match("^(.*)%%s")
      -- Escape for use in regex. Did you know `-` has a meaning there? How
      -- awful!
      local escaped_commentstr = vim.pesc(commentstr)

      -- If the line has a comment that's only following whitespace, we can
      -- defer to mini.comment. We only have custom logic for EOL comments, since
      -- mini.comment doesn't implement logic for them
      if line:match("^%s*" .. escaped_commentstr) then
        require("mini.comment").textobject()
        return
      end

      local line_num = vim.fn.line(".")

      local from = {
        line = line_num,

        -- The index where the commentstring is found
        col = vim.fn.match(line, commentstr),
      }

      local to = {
        line = line_num,

      -- Actually not inclusive problems - for some reason, this returns 1 more
      -- than the last index. Maybe for calculating string length? Anyways,
      -- subtract 1.
        col = vim.fn.col("$") - 1,
      }

      return { from = from, to = to }
    end,
  },
})
```

It's not perfect - ideally, it would use a composed pattern and return the regex to match on directly. But it does seem to work in all my testing! If anyone has any improvements to it, feel free to share them.

(Oh, and if you want separate `dic` / `cic` behavior, that lets you change a comment without deleting the first commentstring, I'll share an implementation I wrote for that in #1837. Yes, it still handles EOL comments)

**Comment by echasnovski** [comment] 2025-06-26 07:53
> With only moderate amounts of pain, I was able to achieve a working implementation of this using `mini.ai`! It only triggers the new logic when necessary - in all other cases, it falls back to the `mini.comment` implementation.

Nice! There are couple of serious issues, though:
- There is no check that there is actually a match. If there isn't, then it will a region with `from.col = -1`, which is according to specification. There needs to be an actual check that there is a match and return `nil` otherwise.
- Using `vim.fn.match(line, commentstr)` still doesn't guarantee there is no issues with special characters (and `-` in Lua patterns is really useful, by the way). Like if `commentstr` contains `.`, for example.
- `vim.fn.match()` returns zero-based indexing, while 'mini.ai' expects one-based. Not sure why it would be working here.

The better approach would be something like `local match_col = line:find(escaped_commentstr)` and checking that it is not `nil`.

Couple of other observations:
- Of course, this doesn't work if a match occurs somewhere where comment is not parsed as comment (as [mentioned earlier](https://github.com/echasnovski/mini.nvim/issues/1431#issuecomment-2562474661)). Like in the string. But that is the limitation of pure pattern based approach.
- Instead of `vim.fn.col('$') - 1` it is possible to use `line:len()` (since there is already a current line stored in variable). And yes, `col('$')` does return "length of cursor line plus one", which is documented in `:h col()`. Mostly (I'd assume) because there is also a special "end-of-line" byte at the end and cursor can be positioned there (like in Insert and Visual modes).

**Comment by llakala** [comment] 2025-06-26 21:32
Thanks! `line:find` is working great. And yeah, I'm not very happy with issues where the comment is within a string. I think I could probably write some messy implementation to ignore the result if it was found within `'` or `"`, using some balanced logic, which would get rid of 99% of false positives. For now, though, it'll do for my personal config.
