### ISSUE TITLE
mini.clue: recording macro removes buffer local mapping

### ISSUE THREAD

**Issue by jemag** [echasnovski/mini.nvim#524] opened 2023-10-17 01:52 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

Recording a macro with mini.clue installed removes buffer local mapping for trigger.

### Neovim version

NVIM v0.10.0-dev-aa62579

### Steps to reproduce

1. Create following minimal config `repro.lua`:
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      { "nvim-tree/nvim-web-devicons" }, -- not strictly required, but recommended
      { "MunifTanjim/nui.nvim" },
    },
    config = function()
      require("neo-tree").setup({})
    end,
  },
  {
    "echasnovski/mini.clue",
    config = function()
      local miniclue = require("mini.clue")
      miniclue.setup({
        triggers = {
          -- Leader triggers
          { mode = "n", keys = "<Leader>" },
          { mode = "x", keys = "<Leader>" },
          { mode = "n", keys = "<localleader>" },
          { mode = "x", keys = "<localleader>" },
          { mode = "n", keys = "\\" },
          { mode = "x", keys = "\\" },
          { mode = "n", keys = "[" },
          { mode = "x", keys = "[" },
          { mode = "n", keys = "<cr>" },
          { mode = "x", keys = "<cr>" },
          { mode = "n", keys = "]" },
          { mode = "x", keys = "]" },

          -- Built-in completion
          { mode = "i", keys = "<C-x>" },

          -- `g` key
          { mode = "n", keys = "g" },
          { mode = "x", keys = "g" },

          -- Marks
          { mode = "n", keys = "'" },
          { mode = "n", keys = "`" },
          { mode = "x", keys = "'" },
          { mode = "x", keys = "`" },

          -- Registers
          { mode = "n", keys = '"' },
          { mode = "x", keys = '"' },
          { mode = "i", keys = "<C-r>" },
          { mode = "c", keys = "<C-r>" },

          -- Window commands
          { mode = "n", keys = "<C-w>" },

          -- `z` key
          { mode = "n", keys = "z" },
          { mode = "x", keys = "z" },
        },

        clues = {
          -- Enhance this by adding descriptions for <Leader> mapping groups
          miniclue.gen_clues.builtin_completion(),
          miniclue.gen_clues.g(),
          miniclue.gen_clues.marks(),
          miniclue.gen_clues.registers({
            show_contents = true,
          }),
          miniclue.gen_clues.windows(),
          miniclue.gen_clues.z(),
          { mode = "n", keys = "<leader>b", desc = "+buffer" },
          { mode = "n", keys = "<leader>d", desc = "+debug" },
          { mode = "n", keys = "<leader>ds", desc = "+step" },
          { mode = "n", keys = "<leader>dt", desc = "+telescope" },
          { mode = "n", keys = "<leader>du", desc = "+dap ui" },
          { mode = "n", keys = "<leader>f", desc = "+format" },
          { mode = "x", keys = "<leader>f", desc = "+format" },
          { mode = "n", keys = "<leader>g", desc = "+git" },
          { mode = "x", keys = "<leader>g", desc = "+git" },
          { mode = "n", keys = "<leader>h", desc = "+hunk" },
          { mode = "x", keys = "<leader>h", desc = "+hunk" },
          { mode = "n", keys = "<leader>i", desc = "+insert" },
          { mode = "x", keys = "<leader>i", desc = "+insert" },
          { mode = "n", keys = "<leader>l", desc = "+language" },
          { mode = "x", keys = "<leader>l", desc = "+language" },
          { mode = "n", keys = "<leader>m", desc = "+bookmarks" },
          { mode = "x", keys = "<leader>m", desc = "+bookmarks" },
          { mode = "n", keys = "<leader>n", desc = "+notes" },
          { mode = "x", keys = "<leader>n", desc = "+notes" },
          { mode = "n", keys = "<leader>o", desc = "+obsidian" },
          { mode = "n", keys = "<leader>r", desc = "+refactor" },
          { mode = "x", keys = "<leader>r", desc = "+refactor" },
          { mode = "n", keys = "<leader>s", desc = "+search" },
          { mode = "x", keys = "<leader>s", desc = "+search" },
          { mode = "n", keys = "<leader>sg", desc = "+git" },
          { mode = "x", keys = "<leader>sg", desc = "+git" },
          { mode = "n", keys = "<leader>t", desc = "+terminal" },
          { mode = "x", keys = "<leader>t", desc = "+terminal" },
          { mode = "n", keys = "<leader>u", desc = "+unique" },
          { mode = "x", keys = "<leader>u", desc = "+unique" },
          { mode = "n", keys = "<leader>w", desc = "+window" },
          { mode = "x", keys = "<leader>w", desc = "+window" },

          { mode = "n", keys = "<localleader>m", desc = "+misc" },
          { mode = "x", keys = "<localleader>m", desc = "+misc" },
          { mode = "n", keys = "<localleader>p", desc = "+project" },
          { mode = "x", keys = "<localleader>p", desc = "+project" },
          { mode = "n", keys = "<localleader>ps", desc = "+session" },
          { mode = "x", keys = "<localleader>ps", desc = "+session" },
          { mode = "n", keys = "<localleader>s", desc = "+misc search" },
          { mode = "x", keys = "<localleader>s", desc = "+misc search" },
          { mode = "n", keys = "<localleader>t", desc = "+project" },
          { mode = "x", keys = "<localleader>t", desc = "+project" },
        },
        window = {
          delay = 500,
          config = {
            width = "auto",
          },
        },
      })
      vim.api.nvim_create_autocmd("Filetype", {
        pattern = { "qf", "aerial", "TelescopePrompt", "neo-tree" },
        callback = function()
          vim.b.miniclue_disable = true
        end,
        desc = "Disable mini.clue triggers for various filetypes",
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

```
2. Open some project file with the minimal config, e.g. `nvim -u repro.lua main.go`
3. Ensure your cwd is a directory containing multiple files, otherwise use `:cd` to change to such directory
4. Open neo-tree with `:Neotree`
5. Check that buffer local `<cr>` mapping is there using `:verbose nmap <cr>`
6. Record some macro in your text buffer
7. Go back to neo-tree and notice that buffer local mapping for `<cr>` is gone with `:verbose nmap <cr>`. Pressing enter will now stop working to open anyfile

Here is a video showcasing the whole thing:

https://github.com/echasnovski/mini.nvim/assets/7985687/e8f15012-ca16-42e3-90eb-b7adfe9c4653

### Expected behavior

clue does not remove buffer local mappings

### Actual behavior

clue removes buffer local mappings

**Comment by echasnovski** [comment] 2023-10-17 11:21
Thanks for the issue!

At first I thought that this works as intended because you have `<CR>` as trigger, but at the last moment I've noticed that it should be disabled in neo-tree buffer. This is a prime example of why *minimal* reproduction example is crucial. So please try to cut reproduction steps down as much as possible. For example, here all triggers except for `{ mode = "n", keys = "<cr>" },`, all custom clues, and listing non-neo-tree filetypes in autocommand are irrelevant.

This is indeed a bug in `disable_all_triggers()` (which is called before starting to record a macro) in that it doesn't recognize disabled buffers and deletes all buffer-local mappings for configured triggers. As there is `<CR>` trigger, it deletes it too.

I'll fix it soon.

**Comment by jemag** [comment] 2023-10-17 13:31
Thanks for your help in fixing the issue.

You are right that I should have kept the configuration much more minimal. I will be more careful next time.

**Comment by echasnovski** [comment] 2023-10-17 14:44
Should be now fixed on the `main` branch.

**Closed** 2023-10-17 14:43 UTC
Labels: bug, mini.clue
