### ISSUE TITLE
Reveal cwd doesn't work for small max_number of windows

### ISSUE THREAD

**Issue by smilovanovic** [echasnovski/mini.nvim#781] opened 2024-04-04 16:39 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

files

### Description

When you limit maximum number of windows to some small number and open mini.files for the directory of current file which is nested on a level grater than the max number of windows is, binding for reveal_cwd (@) won't work.

### Neovim version

0.9.5

### Steps to reproduce

1. Set option `windows.max_number` to 2 and enable preview
2. Open mini.files for your current file which is deeply nested in the project hierarchy
3. Try to navigate to cwd using `mappings.reveal_cwd` binding (by default @)

### Expected behavior

mini.files opens cwd in focused window

### Actual behavior

mini.files does nothing and remains in the current directory

**Comment by echasnovski** [comment] 2024-04-04 18:51
Thanks for the issue!

I can reproduce, although I think this is an intended behavior. Revealing current working directory should not result into changing current focus.

I'll think about it.

**Comment by echasnovski** [comment] 2024-04-08 15:32
After looking at it again, I still think this is an intended behavior: revealing cwd should not change the focus. As there are only 2 windows enabled and the second one is preview, nothing is changed.

Closing as not planned.

**Closed by echasnovski** 2024-04-08 15:32 UTC
Labels: bug, mini.files
