### ISSUE TITLE
mini.indentscope: Add excluded_filetypes

### ISSUE THREAD

**Issue by name-tar-xz** [echasnovski/mini.nvim#535] opened 2023-10-21 20:28 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

An option to disable indentscope on certain filetypes where indentscope is not useful like lazy,mason,filetrees etc.

**Comment by echasnovski** [comment] 2023-10-22 11:14
Hi!

This is a duplicate of #167, #85, #52, and somewhat #423.

At the moment I plan to support disabling only through `{g,b}:mini*_disable`. To make it easier for users, there is a [section in documentation with common situations](https://github.com/echasnovski/mini.nvim/blob/75477368c63e3dee65b2a39e6050391ef521f0b8/doc/mini.txt#L143-L184).

**Closed by echasnovski** 2023-10-22 11:14 UTC
Labels: feature-request, mini.indentscope
