### ISSUE TITLE
mini.files dosent open in new (Not yet saved files)

### ISSUE THREAD

**Issue by d7omdev** [echasnovski/mini.nvim#1304] opened 2024-10-23 11:26 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Hi,

I encountered an issue when opening mini.files on a new or unsaved file. 

mini.files fails to open and throws the error mentioned below.

I suggest adding a dialog prompt that appears when the file is new or unsaved, with options like:

Prompt message: "Would you like to save the file before opening mini.
		If "Yes," the file is saved, and then mini.files opens as expected.
		If "No," mini.files opens without including the unsaved file.

Additionally, I'd be happy to attempt implementing this feature if you're open to it.

### Neovim version

v0.10.2

### Steps to reproduce

1. `nvim test.ts`
2. open mini.files

### Expected behavior

mini.files opening

### Actual behavior

The plugin fails to open and shows the following error:

![image](https://github.com/user-attachments/assets/d483da8c-4aa0-49c7-b9c9-7c76f4ca8a99)

**Comment by echasnovski** [comment] 2024-10-23 11:35
Thanks for the suggestion!

This is by design: anchor path for `MiniFiles.open()` should be a present path on disk. There is no fallbacks and there will be no dialog with suggestions. Either use explicit call [which includes directory](https://github.com/echasnovski/mini.nvim/blob/64e95aa77587d04f97a5579b2106a82a08a7d968/doc/mini-files.txt#L694-L708) or save file prior to opening 'mini.files' explorer.

Closing as duplicate of #1247, #840, and #848.

**Closed by echasnovski** 2024-10-23 11:35 UTC
Labels: duplicate, mini.files
