### ISSUE TITLE
Sessions autosave doesn't respect `directory`

### ISSUE THREAD

**Issue by savchenko** [echasnovski/mini.nvim#655] opened 2024-01-15 00:54 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

`autowrite = true` doesn't seem to use `directory` property.

### Neovim version

0.9.4

### Steps to reproduce

```lua
config = function ()
    require('mini.sessions').setup({

        directory = vim.fn.expand("$XDG_STATE_HOME") .. "/nvim/sessions/",
        file = 'autosession.vim',

        autoread = false,
        autowrite = true,

    })
```

### Expected behavior

Session is saved under `/home/USER/.local/state/nvim/sessions/autosession.vim`

### Actual behavior

Session is saved in the `$PWD`. `file` is respected though.

**Comment by echasnovski** [comment] 2024-01-15 13:56
With this setup `autowrite` is most certainly works as expected and respects `directory`.

What `autowrite = true` does is that it [saves **current** (a.k.a. loaded/read) session](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-sessions.txt#L80) before quitting Neovim. That is, it uses `MiniSessions.write(nil, { force = true })` which [writes to the `v:this_session` path](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-sessions.txt#L162-L163).

So if the observed behavior is that it is written session at '/home/USER/.local/state/nvim/sessions/autosession.vim', then that session was current just before quitting Neovim.

Generally, for `autowrite = true` to be useful there should be session either `read()` first or created/initiated with a call to `write()`. It is designed this way to not spam session files when Neovim is opened for quick editing.

Closing as (most certainly) not an issue with 'mini.sessions'.
______

I would also suggest using `vim.fn.stdpath('state')` instead of `vim.fn.expand('$XDG_STATE_HOME') .. '/nvim'` as it is more portable (doesn't require `XDG_STATE_HOME` to actually be defined) and concise.

**Closed by echasnovski** 2024-01-15 13:56 UTC
Labels: mini.sessions

**Comment by echasnovski** [comment] 2024-01-16 09:44
> After all, there seems to be a bug, just a different one :)

This is still not a bug. `write()` [accepts first argument as session **name**](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-sessions.txt#L162-L163) not a full path. The directory where it is written is [determined based on the name](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-sessions.txt#L153-L158).

The `config.file` option is specifically intended to be the [name for local sessions](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-sessions.txt#L86), meaning the ones which create session file in the current working directory. This (along with `autoread = true`) allows the workflow of automatically restoring session which was in the current directory.

------

If I understand correctly, the behavior that worked just fine is a "have single session be read during startup and written before closing Neovim". 'mini.sessions' is not specifically designed for this kind of workflow, but it can be replicated with the following setup:

```lua
function()
  require('mini.sessions').setup({
    autoread = true,
    directory = vim.fn.stdpath('state') .. '/sessions/',
  })
end
```

On first run there will be an error about no detected sessions (because there aren't any). Follow it with `:lua MiniSessions.write('autosession')` which should write a session file to `config.directory`. After that it should work as a single global session: it will be loaded during startup because it is the latest used session and written before closing Neovim because it is the current session.

**Comment by echasnovski** [comment] 2024-01-25 09:48
> For reasons unknown, even with `autowrite = true` I wasn't able to reliably reproduce this simple routine.

Reasons were already given: `autowrite = true` saves only if session (as in Neovim's/Vim's session) is in use at the moment of closing. This is determined by `vim.g.this_session` global variable.

To *always* save to same session before closing Neovim, make own autocommand. With something like this:
```lua
require('mini.sessions').setup({ autowrite = false })
local make_omnisession = function() MiniSessions.write('omnisession', { force = true }) end
vim.api.nvim_create_autocmd('VimLeavePre', { callback = make_omnisession, desc = 'Make omnisession' })
```

**Comment by mauromotion** [comment] 2024-03-05 17:17
I've been reading a couple of this issues and I believe there's a fundamental misunderstanding on this.

I find myself in a similar situation, whereas mini.sessions work, but not as I would expect. That's the workflow of the issue:

- Open some buffers in Neovim
- Save a new session with mini.sessions
- Close Neovim

- Reopen Neovim
- Load the saved session (it woks fine)
- While working it the "session" close some buffers, open some other
- Close Neovim

- Reopen and load the same session

At this point I can only restore the very first created version of said session, as in, when I closed and opened some buffers and then closed neovim, mini.sessions didn't overwrite the session's file with the new state.

I thought this plugin would keep track on the buffers I open and close on a certain "session" of work.

At least this is what I would expect.

**Comment by echasnovski** [comment] 2024-03-05 17:34
> * Load the saved session (it woks fine)
> 
> * While working it the "session" close some buffers, open some other
> 
> * Close Neovim
> 
> * Reopen and load the same session
>
> At this point I can only restore the very first created version of said session, as in, when I closed and opened some buffers and then closed neovim, mini.sessions didn't overwrite the session's file with the new state.

Yes, it does restore the state of session as it was prior to the last closing Neovim (i.e. after "close some buffers, open some other"). I've just double checked.

The option that controls if 'mini.sessions' automatically overrides current session file (that is, loaded with `MiniSessions.read()` or in other way that sets `vim.v.this_session`) is [`config.autowrite`](https://github.com/echasnovski/mini.nvim/blob/70d8a16399ca6df759d20bea302d6dfd710a1df8/doc/mini-sessions.txt#L80-L81). It is `true` by default so should work with default config. What config do you use?

**Comment by maskudo** [comment] 2025-02-17 06:13
@echasnovski is there a way to store the session file using an absolute path? 
```lua
local file = vim.fn.stdpath("state")
	.. vim.fn.fnamemodify(vim.fn.getcwd(), ":t")
	.. ".vim"
```
as the path doesn't work for example. It gets annoying having to ignore the file each time i create the session with gitignore

**Comment by echasnovski** [comment] 2025-02-17 09:44
> [@echasnovski](https://github.com/echasnovski) is there a way to store the session file using an absolute path?
> 
> local file = vim.fn.stdpath("state")
> 	.. vim.fn.fnamemodify(vim.fn.getcwd(), ":t")
> 	.. ".vim"
> 
> as the path doesn't work for example. It gets annoying having to ignore the file each time i create the session with gitignore

Yes. By storing global session named `vim.fn.fnamemodify(vim.fn.getcwd(), ":t") .. '.vim'`. So something like this:

```lua
require('mini.sessions').setup({
  directory = vim.fn.stdpath('state'),
  file = '',
})
```

And later execute `:lua MiniSessions.write(vim.fn.fnamemodify(vim.fn.getcwd(), ":t") .. '.vim')`.

The `config.file` is specifically for [local sessions](https://github.com/echasnovski/mini.nvim/blob/4dd209e4f03bacd46d6d87408b2529a8823112fb/doc/mini-sessions.txt#L18), i.e. for files inside current working directory.

**Comment by maskudo** [comment] 2025-02-17 10:22
> The `config.file` is specifically for [local sessions](https://github.com/echasnovski/mini.nvim/blob/4dd209e4f03bacd46d6d87408b2529a8823112fb/doc/mini-sessions.txt#L18), i.e. for files inside current working directory.

It would be helpful to store the local sessions out of the local directory to not pollute it. I could get away with storing the session in .git folder as its ignored but this feels dirty.

**Comment by echasnovski** [comment] 2025-02-17 10:34
> It would be helpful to store the local sessions out of the local directory to not pollute it.

Then it would not be local. Allowing relative path as `config.file` *might* be possible, but my suggestion for using global session for this still stands.
