### ISSUE TITLE
IndentScope: Hangs on long folds

### ISSUE THREAD

**Issue by SirWrexes** [echasnovski/mini.nvim#729] opened 2024-03-06 07:28 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

IndentScope

### Description

The animation tends to hang on large folds.
Say I have a 80 lines fold in the middle of the line's trajectory, and my cursor is currently under it.
The line goes up at normal speed, reaches the fold, there it hangs and we need to wait a bit and then it finally covers the fold's top line and then the rest of the current indent scope.

My guess is that it most likely ticks for every line in the fold, whether they are visible or not.
I'm not sure if Nvim's API exposes a way to detect if you're drawing inside a fold or not, but I believe it would make for a smoother and more seamless experience if it was possible to skip all invisible lines.
Even if that means re-drawing the line when a fold opens or closes; actually I think that's good because it updates you on the "new" visible indentation scope.

Note that I've noticed the issue after installing `nvim-ufo` and testing things out. Notwithstanding, it behaved exactly the same as with the minimal installation I provided. A fix should work universally.

### Neovim version

v0.9.5 (Release)

### Steps to reproduce

Save this as "reproduce.lua" and open it with "nvim -nu reproduce.lua reproduce.lua"
There's a dummy `if` statement at the end to see the issue in action.

```lua
---[[ Mini local installation of Lazy.nvim, taken from their bug report template ]]---

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",

  { -- INDENTSCOPE SETUP IS HERE
    "echasnovski/mini.indentscope",
    version = "*",

    -- Setting fold config here to be sure it's set before loading IndentScope 
    init = function ()
	vim.o.foldmethod = "marker"
	vim.o.foldlevel = 1
	vim.o.foldmarker = "--[[,--]]"
    end,

    opts = {
      draw = {
        priority = 50,
      },
    },
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")


if true then
  -- Place cursor on this line

  --[[ THIS IS A LONG EMPTY FOLD
  




























  

  













































  --]]

  -- Place cursor on this line
end
```

### Expected behavior

Ideally the line should seem uninterrupted, just jumping over the fold.

### Actual behavior

The line hangs for a period of time proportional to the fold, which can quickly end up problematic if you like/need to fold things around to reduce the visual noise when dealing with huge source files.

**Comment by echasnovski** [comment] 2024-03-06 08:42
Thanks for the issue!

This is somewhat intentional. The goal here is to show the actual text scope (actual text lines) and not visible scope (visible lines). It also helps visualizing if fold is large enough for animation to become noticeably delayed.

And also this approach has better performance. Otherwise it would indeed be needed to decide if the line is inside fold or not *on every line drawing*.

Closing as this is an intended behavior.

**Closed by echasnovski** 2024-03-06 08:42 UTC
Labels: mini.indentscope

**Comment by SirWrexes** [comment] 2024-03-08 17:40
Just a quick reply here about checking if a line is inside a fold.
I admit I haven't looked into your code yet, as I have a bunch of stuff on my plate myself.
However, out of curiosity I looked up if NeoVim's api had ways to check if a line is inside a fold, and it does, in a rather clever way even !

In case you haven't heard of those:
[`foldclosed()`](https://neovim.io/doc/user/builtin.html#foldclosed()) checks if a line is in a closed fold, returns `-1` if not, and the _number of the fold's first line_.
[`foldclosedend()`](https://neovim.io/doc/user/builtin.html#foldclosedend()), right under the previous one, does the same but giving your the _number of the last line_.
I assume the API has some way of making if efficient instead of just going the naive way, checking every single line every time.

Wouldn't that be a game changer to get an option to jump the folds ? I understand your reasoning though I'd love a way to make it look snappier, personally.

Thank you for your fast reaction~

**Comment by echasnovski** [comment] 2024-03-08 17:53
> However, out of curiosity I looked up if NeoVim's API had ways to check if a line is inside a fold, and it does, in a rather clever way even !
> 
> In case you haven't heard of those: [`foldclosed()`](https://neovim.io/doc/user/builtin.html#foldclosed()) checks if a line is in a closed fold, returns `-1` if not, and the _number of the fold's first line_ otherwise. [`foldclosedend()`](https://neovim.io/doc/user/builtin.html#foldclosedend()), right under the previous one, does the same but giving your the _number of the last line_. I assume the API has some way of making it efficient instead of just going the naive way, checking every single line every time.

Yes, I am aware about these functions and [even use them in other module](https://github.com/echasnovski/mini.nvim/blob/c3b37f4afb933141a750b60b86fb6ef6b50d0e61/lua/mini/animate.lua#L2097-L2111) when it is needed. Right now 'mini.indentscope' is written in a way which works line-by-line without skipping. Rewriting this would require either a lot of refactor or not clearly understandable code.

> Wouldn't that be a game changer to get an option to jump the folds ? I understand your reasoning though I'd love a way to make it look snappier, personally.

As I said earlier, delay in fold proportional to its size provides more value than skipping it entirely. And as modifying it (even behind an option) is not a trivial change, this will most certainly not going to happen.

**Comment by SirWrexes** [comment] 2024-03-08 20:23
> As I said earlier, delay in fold proportional to its size provides more value than skipping it entirely.  

This is also a matter of taste.
For me, I get _actively bothered_ by the lack of fluidity. Like I said: I understand the reasoning, but I have my personal reasons.  
But in the end you're the dev so I don't make the rules. 🫡

Either way, still an excellent little plugin, and I'm going to keep it anyway!
Have a good day~
