### ISSUE TITLE
(mini.files) FEATURE: add`:w` to sync changes rather than `=`

### ISSUE THREAD

**Issue by lordvidex** [echasnovski/mini.nvim#497] opened 2023-09-30 12:31 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

1. It is intuitive that `:w` should save changes in (neo)vim.
2. On the QWERTY layout `=` is farther to reach compared to the "write" combo keys.

Generally, I think that the `:w` command is more convenient and is the vim way.

**Comment by echasnovski** [comment] 2023-09-30 12:53
Thanks for the suggestion!

Closing as not planned and a duplicate of #391. See the reasoning there.

**Closed by echasnovski** 2023-09-30 12:53 UTC
Labels: duplicate, feature-request, mini.files
