### ISSUE TITLE
Mini.hipatterns causes large files to lock up after loading

### ISSUE THREAD

**Issue by domsch1988** [echasnovski/mini.nvim#1232] opened 2024-09-19 07:41 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.hipatterns

### Description

I'm experiencing an unresponsive neovim when opening large (multi Megabyte) Files with a mini.hipattern configuration

### Neovim version

0.10.1

### Steps to reproduce

This is my hipatterns definition:
``` lua
later(function()
    local hipatterns = require("mini.hipatterns")

    local censor_extmark_opts = function(_, match, _)
        local mask = string.rep("*", vim.fn.strchars(match))
        return {
            virt_text = { { mask, "Comment" } },
            virt_text_pos = "overlay",
            priority = 200,
            right_gravity = false,
        }
    end

    local password_table = {
        pattern = {
            "password: ()%S+()",
            "password_usr: ()%S+()",
            ".*_pw: ()%S+()",
            "password_.*: ()%S+()",
            "gpg_pass: ()%S+()",
            "passwd: ()%S+()",
        },
        group = "",
        extmark_opts = censor_extmark_opts,
    }

    hipatterns.setup({
        highlighters = {
            -- Highlight standalone 'FIXME', 'HACK', 'TODO', 'NOTE'
            fixme = { pattern = "%f[%w]()FIXME()%f[%W]", group = "MiniHipatternsFixme" },
            hack = { pattern = "%f[%w]()HACK()%f[%W]", group = "MiniHipatternsHack" },
            todo = { pattern = "%f[%w]()TODO()%f[%W]", group = "MiniHipatternsTodo" },
            note = { pattern = "%f[%w]()NOTE()%f[%W]", group = "MiniHipatternsNote" },

            -- Cloaking Passwords
            pw = password_table,

            -- Highlight hex color strings (`#rrggbb`) using that color
            hex_color = hipatterns.gen_highlighter.hex_color(),
        },
    })

    vim.keymap.set("n", "<leader>up", function()
        if next(hipatterns.config.highlighters.pw) == nil then
            hipatterns.config.highlighters.pw = password_table
        else
            hipatterns.config.highlighters.pw = {}
        end
        vim.cmd("edit")
    end, { desc = "Toggle Password Cloaking" })
end)
```

### Actual behavior

In particular the password cloaking, which i took from the examples in the docs, is causing large files to become unresponsive for quite some time after loading. I'm testing with a 7 MB Plaintext Logfile. Nvim and the file initially loads fast but the immediately becomes unresponsive for 30-40 seconds. After that, everything is fine. Commenting the `pw` highlighter makes this behavior go away.
Both the hex_color and Todo highlighters don't show this issue. So i'm not sure how to improve this code to remedy this.

**Comment by echasnovski** [comment] 2024-09-19 08:41
Thanks for the issue!

Indeed, I can reproduce. But going one step further to debug this revealed that the culprit here are `".*_pw: ()%S+()"` and `"password_.*: ()%S+()"` patterns (which are *not* present in 'mini.hipatterns' example). *Especially* the first pattern, as it results in quite slow pattern matching due to having `.*` which I guess makes it apply to every line in a slow manner.

This is easy to resolve by replacing the first pattern with `'_pw: ()%S+()'`, as starting it with `.*` does not have any effect. There still is small-ish lag with `"password_.*: ()%S+()"` present, but the only way to improve it is by removing two variable width chunks (i.e. `.*` and `%S+`).

------

Closing as "works as expected and is the result of slow-ish patterns".

------

Some more details:

- The initial parsing of the whole buffer is necessary because present (`nvim_buf_attach()`) interface allows recomputing only on *changed* lines. So computing result before the initial change is needed to show proper highlighting.
- There are already several places dedicated to making updating smoother, but making it smoother on "per line update basis" seems a bit too much. Currently it is on "per buffer-pattern" basis *after* debouncing.
- Ideally it would have been better to initially process only visible lines instead of all of them. Unfortunately, it seems to be impossible because "visible lines" is not a property of a buffer, but of a window. The only interface present is to "get top/bottom line of *current* *window*". Together with the fact that the same buffer can be present in multiple windows, this makes the current "process all lines at first" a reasonable compromise.

**Closed by echasnovski** 2024-09-19 08:41 UTC
Labels: mini.hipatterns

**Comment by domsch1988** [comment] 2024-09-19 08:44
Thanks for looking into this. I'm able to make my patterns more specific and will test for performance in the future.
