### ISSUE TITLE
mini.ai changes latest visual selection

### ISSUE THREAD

**Issue by simonmandlik** [echasnovski/mini.nvim#1095] opened 2024-07-30 06:04 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

`mini.ai`

### Description

When using e.g. an operator like `yi)`, this changes the latest visual selection (accessed by `gv`), even the only possible use of visual mode here is behind the scenes. This doesn't happen in clean neovim.

### Neovim version

0.10.0

### Steps to reproduce

`minimal.lua`:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        {
            "echasnovski/mini.ai",
            opts = {},
        },
    }
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})
```

**Comment by echasnovski** [comment] 2024-07-30 07:18
Thanks for the issue!

Yeah, can reproduce. I personally don't think this is a huge problem, but I'll take a look.

**Comment by echasnovski** [comment] 2024-07-30 09:35
I am afraid I am going to close this as "won't fix". For at least these reasons:
- The whole Operator-pending mode mapping situation is rather convoluted and limited to what Vim provides (from which Neovim "inherits" this part of code base).
- The [official suggestion](https://neovim.io/doc/user/map.html#omap-info) as to how make a textobject (selection which ignores starting cursor position) also doesn't preserve previous visual selection. You can try this with `vim.cmd('onoremap <silent> F :<C-U>normal! 0f(hviw<CR>')` (assuming 'mini.jump' is not loaded afterwards) and `yF` for in line `aa bb(cc)`.
- I tried several approaches of "save and restore" marks for previous visual selection, but none of them worked. The reason seems to be that the actual change of those marks happens [*after* the `<Cmd>...<CR>` in expression mapping](https://github.com/echasnovski/mini.nvim/blob/10426fc5bd38397c9a74d80cd4a6c55243fc78de/lua/mini/ai.lua#L1265) is executed (after `<CR>` to be more precise). Modifying that returned `<Cmd>...<CR>` to save and restore (like `<Cmd>lua <save>; <select><CR><Cmd>lua <restore><CR>`) breaks mappings for some unknown reason.

**Closed by echasnovski** 2024-07-30 09:35 UTC
Labels: bug, mini.ai

**Comment by simonmandlik** [comment] 2024-07-30 11:42
I see, thanks for trying anyway :)

It is a bit distractive in my workflow, but nothing major I couldn't live without
