### ISSUE TITLE
`mini.files` reopens deleted buffers as unlisted buffers

### ISSUE THREAD

**Issue by dlwhj** [echasnovski/mini.nvim#470] opened 2023-09-07 08:24 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Using the plugin together with `mini.tabline` and `mini.bufremove`, all installed and loaded using `lazy.nvim` package manager.

Closing a buffer using `MiniBufremove.delete()` or `:bd` either from a key mapping or direction execution from the command line, then reopening said buffer using `mini.files` results in the buffer not being registered as a listed buffer. Unsure if this is intended behavior or not. The buffer is displayed fine in the current window as the active buffer.

The main annoyance that occurs is with the tabline. The tabline displays incorrectly for the current buffer, as it continues to label it with the previous buffer (now "covered" by the new reopened buffer), despite showing the contents of the new reopened buffer. If the behavior is intended, will highly appreciate it if a solution can be shared for smoother integration ㅠㅠ.

### Neovim version

NVIM v0.9.1

### Steps to reproduce

1. Install `mini.files`, `mini.tabline`, and `mini.bufremove`, unconfigured.
2. Open multiple buffers.
3. Close a buffer, using `:bd` or `:lua MiniBufremove.delete()`.
4. Open the closed buffer using `mini.files`.

### Expected behavior

![expected](https://github.com/echasnovski/mini.nvim/assets/129026439/7d6a82c0-7454-4cea-a2f7-d49e245b158e)

### Actual behavior

![actual](https://github.com/echasnovski/mini.nvim/assets/129026439/cbf4492c-bdab-442e-810c-039b95615123)

**Comment by echasnovski** [comment] 2023-09-07 10:29
Thanks for taking time to create this!

Yes, this is an intended behavior. Opening a file first tries to look for an existing buffer for the target path. In case of both `MiniBufremove.bdelete()` and `:bdelete`, the file isn't *actually deleted* (it is removed from buffer list and some data related to it is cleared, see `:h :bdelete`), so it is reused by 'mini.files'. To verify that it is actually present after `:bd`, execute `:buffers!` instead of `:buffers`: that buffer should have `u` flag next to it meaning it is "unlisted". It is not made "listed" again solely because I can see people actually preferring for file explorer to not update existing buffers when not asked to.

To *actually delete* a buffer, use `MiniBufremove.wipeout()` or `:bw`.

Closing as this is by design.

**Comment by debugloop** [comment] 2023-10-11 10:54
I think this behaviour is not quite ideal: When using `gopls` (and possibly other LSPs) it has any buffer in the workspace with diagnostics open as an unlisted buffer. I can not properly open those and afaict there is no way to instruct mini.files to list them. I end up running `:e` every time.

I'd like to request an option to list previously unlisted buffers when opening from `mini.files`. I'm also open to work on this myself if you concur about the inclusion in principle but don't want to spend the time on it :)

**Comment by echasnovski** [comment] 2023-10-11 11:16
> I think this behaviour is not quite ideal: When using `gopls` (and possibly other LSPs) it has any buffer in the workspace with diagnostics open as an unlisted buffer. I can not properly open those and afaict there is no way to instruct mini.files to list them. I end up running `:e` every time.
> 
> I'd like to request an option to list previously unlisted buffers when opening from `mini.files`. I'm also open to work on this myself if you concur about the inclusion in principle but don't want to spend the time on it :)

This definitely won't be an extra plugin option. Maybe as an extra `ensure_listed_file` for `MiniFiles.go_in()`, though.

In the meantime, this effect is possible to achieve for 99% of cases with this approach:
```lua
local go_in_with_edit = function()
  local fs_entry = MiniFiles.get_fs_entry()
  if fs_entry.fs_type ~= 'file' then return MiniFiles.go_in() end
  vim.fn.win_execute(MiniFiles.get_target_window(), 'edit ' .. vim.fn.fnameescape(fs_entry.path))
end

vim.api.nvim_create_autocmd('User', {
  pattern = 'MiniFilesBufferCreate',
  callback = function(data)
    vim.keymap.set('n', 'l', go_in_with_edit, { buffer = data.buf, desc = 'Go in with edit' })
  end,
})
```

**Comment by echasnovski** [comment] 2023-10-11 11:17
As a matter of fact, I'll reopen this to indeed consider a possibility of adding `opts.ensure_listed` option to `MiniFiles.go_in()`.

**Comment by debugloop** [comment] 2023-10-11 17:15
Thanks for the quick feedback 🥇 I quickly tried your snippet but could not get it to work yet, I'll figure it out tomorrow when I have more time 👍🏻

**Closed** 2023-10-12 14:42 UTC
Labels: feature-request, mini.files

**Comment by echasnovski** [comment] 2023-10-12 14:45
@debugloop, @dlwhj, having heard about 'gopls' case I've updated `go_in` to reuse buffer only if it is listed. Otherwise, it uses `:edit` and makes it listed again. Thanks for bringing this up!
