### ISSUE TITLE
Active and modified tabs are confusing due to their very similar contrast

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#424] opened 2023-07-20 19:47 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

base16.lua tabline.lua

### Description

When using base16.lua and tabline.lua together, distinguishing between the active and modified tabs becomes quite perplexing due to their very similar contrast. What more is the modified state have a slightly higher contrast than the active one, adding to the confusion.

### Neovim version

NVIM v0.9.1

### Steps to reproduce

1. Enable base16.lua and tabline.lua.
2. Open multiple buffers.
3. Modify one buffer.
3. Switch to a different buffer.

### Expected behavior

More distinction between active and modified state, lower contrast and perhaps a  icon? 

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/4062a930-5977-4753-b635-d3998ced1ea1)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/22d8c783-f32a-4f28-b594-844c0e92800f)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/2bbf2584-6cd2-4d30-8ed6-135e8b2fe394)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/58af5898-a30a-4b2e-bd84-119c3f502618)

**Comment by echasnovski** [comment] 2023-07-21 07:16
Thanks for the issue!

There is not much that can be done here. Base16 has only 4 shades of background colors and 4 shades of foreground colors (or more like 2, because base06 and base07 are usually hardly distinguishable from white).

Highlight group for current tab [has regular foreground with visible background](https://github.com/echasnovski/mini.nvim/blob/78cf17f23dd5372154e1cc90dc3ae27da6368742/lua/mini/base16.lua#L715), while all highlight groups for modified tabs [use forground/background colors for background/foreground](https://github.com/echasnovski/mini.nvim/blob/78cf17f23dd5372154e1cc90dc3ae27da6368742/lua/mini/base16.lua#L718-L720) to make them stand out.

The reason you are not seeing much contrast is likely because there is not much contrast between light background (base01, base02) and dark foreground (base04).

I can suggest at least the following:
- Tweak those base background/foreground colors for more contrast.
- Redefine highlight groups of 'mini.tabline' to your liking after loading 'mini.base16'.

Closing as not a bug.

**Closed by echasnovski** 2023-07-21 07:16 UTC
Labels: question, mini.base16, mini.tabline
