### ISSUE TITLE
Mini.Pick E79: Cannot expand Wildcards // (Pick lsp)

### ISSUE THREAD

**Issue by rob32** [echasnovski/mini.nvim#1029] opened 2024-07-08 10:59 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

First of all, big thanks for all your work and the great plugins. I'm a big fan! :heart: 

I use my own nvim config with the help of lazy.nvim as plugin manager.

Actually, everything works perfectly, only 3-4 LSP keymaps for Mini.Pick are not "working".

No matter in which project and language, when I use one of the following keybindings I always get a "_E79 cannot expand wildcards_" error message

e.g.:

```
vim.keymap.set("n", "<leader>ci", "<cmd>Pick lsp scope='implementation'<CR>", { desc = "Implementations" })
vim.keymap.set("n", "<leader>cR", "<cmd>Pick lsp scope='references'<CR>", { desc = "References" })
vim.keymap.set("n", "<leader>cs", "<cmd>Pick lsp scope='document_symbol'<CR>", { desc = "Symbols buffer" })
```

Only after pressing a button the pick window pops up with the correct result.

Is this normal or am I missing something?

### Neovim version

0.10.0

### Steps to reproduce

`settings.lua`

_E79 cannot expand wildcards:_

```
vim.keymap.set("n", "<leader>ci", "<cmd>Pick lsp scope='implementation'<CR>", { desc = "Implementations" })
vim.keymap.set("n", "<leader>cR", "<cmd>Pick lsp scope='references'<CR>", { desc = "References" })
vim.keymap.set("n", "<leader>cs", "<cmd>Pick lsp scope='document_symbol'<CR>", { desc = "Symbols buffer" })
vim.keymap.set("n", "<leader>cS", "<cmd>Pick lsp scope='workspace_symbol'<CR>", { desc = "Symbols workspace" })
```

With this one there is no error message and the pick window appears directly:

```
vim.keymap.set("n", "<leader>cd", "<cmd>Pick diagnostic scope='current'<CR>", { desc = "Diagnostic buffer" })
vim.keymap.set("n", "<leader>cD", "<cmd>Pick diagnostic scope='all'<CR>", { desc = "Diagnostic workspace" })
```

### Expected behavior

That the pick window appears directly without pressing any keys.

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/49953458/17b78d53-4140-4de1-9f88-0cfa21ea520a)

**Comment by echasnovski** [comment] 2024-07-08 11:11
Thanks for the issue!

Unfortunately, I can not reproduce. Would you mind clarifying some details?

- Does running `:lua vim.lsp.buf.references()` work? It should be in the *same exact conditions* as when `:Pick lsp scope='references'` fails.
- With what languages and language servers did you see this behavior?

If the first question is negative (as in "`vim.lsp.buf.references()` works but `:Pick lsp scope='references'` does not), then I'd have to ask for a reproducible example. So that I can copy and investigate locally. You can use [the start of this 'mini.deps' example script](https://github.com/echasnovski/mini.nvim/blob/main/scripts/init-deps-example.lua) or the one from 'lazy.nvim' issues, whichever you're most comfortable with.

**Comment by rob32** [comment] 2024-07-08 13:08
Hey thanks for the super quick feedback.

Regarding point 1: "Does running `:lua vim.lsp.buf.references() `work"
-> Yes, this works without the E79:

![image](https://github.com/echasnovski/mini.nvim/assets/49953458/b44653d2-45f9-4af3-af9f-d3287adee468)

With `:Pick lsp scope='references'` i get the E79:
![image](https://github.com/echasnovski/mini.nvim/assets/49953458/633fce78-4bc2-465c-9687-e82186bd278d)

Only after I press space the window appears. Same result as with `:lua vim.lsp.buf.references()`:
![image](https://github.com/echasnovski/mini.nvim/assets/49953458/8abf8ba3-b05c-4d87-b628-aac78b951e64)

Regarding point 2: "With what languages and language servers did you see this behavior?"
-> lua_ls, basedpyright, phpactor, intelephense (lua/python/php)

---

While researching, I found a user who got the same error message but with a theme plugin. I think it was due to the fish shell (which I also use).

...

I hope I can upload a reproducible example this evening.

In any case, many thanks in advance :pray: 

PS: sorry for the bad example and the big screenshots above

**Comment by echasnovski** [comment] 2024-07-08 13:30
Interesting.

Based on [this comment](https://github.com/martineausimon/nvim-lilypond-suite/issues/19#issuecomment-1606021376), would you mind testing if `:Pick lsp scope="references"` (note double quotes instead of single quotes) works?

If it does work, could you, please, also execute `:=vim.fn.expandcmd("scope=''references")` (as this is what 'mini.pick' is doing in `:Pick` command) and see if it gives the `E79` error?

**Comment by rob32** [comment] 2024-07-08 16:38
`:Pick lsp scope="references"` works :+1: 

with `:=vim.fn.expandcmd("scope='references'")` I get the E79 again: 
![image](https://github.com/echasnovski/mini.nvim/assets/49953458/f75d8ec8-abcd-4dd9-9d77-8e4aafff3760)

**Comment by echasnovski** [comment] 2024-07-08 17:09
> `:Pick lsp scope="references"` works 👍
> 
> with `:=vim.fn.expandcmd("scope='references'")` I get the E79 again:

Great! Then I don't think it is a 'mini.pick' / 'mini.extra' issue. It is said that `:h expandcmd()` should work, but it seems to have issues with single quotes and Fish shell. This looks like an upstream Neovim problem.

If you want, opening an issue there mentioning that `:=vim.fn.expandcmd("scope='references'")` fails can be helpful. Although, this might be even a more upstream (Vim) issue.

Closing as an upstream issue.

**Closed by echasnovski** 2024-07-08 17:09 UTC
Labels: bug, needs-repro, mini.pick, mini.extra
