### ISSUE TITLE
Error executing lua when using bracketed's treesitter jumps 

### ISSUE THREAD

**Issue by nogweii** [echasnovski/mini.nvim#1142] opened 2024-08-13 06:00 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.bracketed

### Description

When in a Markdown file, pressing `]t` (or it's reverse) enough times, usually at the end of a line, will result in the mentioned error message. In other files, the same actions produce the error message `Cursor position outside buffer`, from the same line.

### Neovim version

0.10.1

### Steps to reproduce

I thought this was maybe related to the `conceal` feature but turning that off doesn't change the error. I'm not sure what the minimal reproducible example is. 😓

### Actual behavior

Stack trace:

```
E5108: Error executing lua .../.local/share/nvim/lazy/mini.nvim/lua/mini/bracketed.lua:928: Column value outside range

stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        .../.local/share/nvim/lazy/mini.nvim/lua/mini/bracketed.lua:928: in function 'treesitter'
        [string ":lua"]:1: in main chunk
```

**Comment by echasnovski** [comment] 2024-08-13 07:00
Thanks for the issue!

I can reproduce. The problem is indeed that treesitter returns some strange column. I'll take a look.

**Comment by echasnovski** [comment] 2024-08-13 17:47
This should now be fixed on latest `main`.

**Closed** 2024-08-13 17:47 UTC
Labels: bug, mini.bracketed
