### ISSUE TITLE
Disappearing text block when :set rightleft (mini.indentscope)

### ISSUE THREAD

**Issue by k1-end** [echasnovski/mini.nvim#774] opened 2024-03-28 20:40 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

If the buffer direction is set to right to left with `:set rightleft`, when the animation starts, the text disappears.

### Neovim version

0.9.4

### Steps to reproduce

1- open any file with some indentation and mini.align activated
2- :set rightleft
3- move the cursor to a new block of text
4. the block starts to disappear

### Actual behavior

indented blocks starts to disappear in rightleft mode.

**Comment by echasnovski** [comment] 2024-03-29 12:35
Thanks for the issue!

I indeed can reproduce on Neovim 0.9.5, but it seems to be fixed on current [Nightly version 0.10](https://github.com/neovim/neovim/releases/tag/nightly).

The reason this happens is the way the line is drawn to be more robust against left-right window scroll and it indeed implicitly assumes that there is an empty space to the left of it. As it is quite a fundamental implementation detail, I'm afraid my only suggestion would be to use Nightly for this (or wait until 0.10 release, which *should* be soon-ish enough).

Closing as fixed on latest Neovim version.

**Closed by echasnovski** 2024-03-29 12:35 UTC
Labels: bug, mini.indentscope, neovim-upstream
