### ISSUE TITLE
mini.surround can't work properly with tag <router-outlet>

### ISSUE THREAD

**Issue by ShIRannx** [echasnovski/mini.nvim#748] opened 2024-03-14 03:07 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

mini.surround can't work properly with tag ```<router-outlet>```

Additionally, when incorporating plugin actions like 'srtt,' the complexity further increases. For instance, in nvim.surround, the tag is going to visiual mode by <cst>, and only the target tag name should be typed.

### Neovim version

0.9.5

### Steps to reproduce

```<router-outlet>*<router-outlet>``` then `<srt>` do not work 

### Expected behavior

```<router-outlet>*<router-outlet>```  `<srt>`
(directly input the target tag name instead of type one more `<t>`)

### Actual behavior

no response

**Comment by echasnovski** [comment] 2024-03-14 09:32
In 'mini.surround' the built-in input surroundings are searched with Lua patterns (similar to regular expressions). [Tag surrounding is no exception](https://github.com/echasnovski/mini.nvim/blob/e025ee74705b04dd25a132a521c9c535dc78a8d8/doc/mini-surround.txt#L51-L53).

> mini.surround can't work properly with tag `<router-outlet>`

This is because tag name is only assumed to have alphanumeric characters, no punctuation. You can customize this at least with these approaches:
- Allow certain set of punctuation to be present in tag name with something like this:
    ```lua
    require('mini.surround').setup({
      custom_surroundings = {
        t = {
          -- Allow "_" and "-" in tag name
          input = { '<([%w_-]-)%f[^<%w_-][^<>]->.-</%1>', '^<.->().*()</[^/]->$' },
        },
      },
    })
    ```
- Use [tree-sitter based surrounding](https://github.com/echasnovski/mini.nvim/blob/e025ee74705b04dd25a132a521c9c535dc78a8d8/doc/mini-surround.txt#L732). This is the best option if you work in tag-related filetypes often and have tree-sitter enabled there. This requires investigation about which 'nvim-treesitter-textobjects' query corresponds to tags in the target filetype.

> Additionally, when incorporating plugin actions like 'srtt,' the complexity further increases. For instance, in nvim.surround, the tag is going to visiual mode by , and only the target tag name should be typed.

This is by design. See #397.

------

Closing as both "won't fix" and "duplicate".

**Closed by echasnovski** 2024-03-14 09:32 UTC
Labels: mini.surround
