### ISSUE TITLE
Missing border on mini.completion dropdown menu

### ISSUE THREAD

**Issue by GNOMES** [echasnovski/mini.nvim#1266] opened 2024-10-08 22:36 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

I currently have both Info and Signature set to 'single', as I like the break between my black background.

Should this also include the drop down menu itself, or can you only add borders to the "floating" window with information?

![Screenshot 2024-10-08 at 17 31 53](https://github.com/user-attachments/assets/beac77da-5324-41e1-9f39-0910ceaab013)

### Neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Steps to reproduce

Configure mini.completion with following config:

`return {
    'echasnovski/mini.completion',
    event = 'InsertEnter',
    version = false,
    config = function()
        require('mini.completion').setup {
            lsp_completion = { source_func = 'omnifunc', auto_setup = false },
            window = {
                info = { height = 25, width = 80, border = 'single' },
                signature = { height = 25, width = 80, border = 'single' },
            },
        }
    end
}`

### Expected behavior

the drop down menu with string options would have a border option

### Actual behavior

Currently with options in plugin there are no borders, so it blends into my background.

**Comment by echasnovski** [comment] 2024-10-09 10:09
Managing completion is done [with built-in tools as much as possible](https://github.com/echasnovski/mini.nvim/blob/a535342b6105a684f16114f598d44318e6a1d20f/doc/mini-completion.txt#L13-L14). The completion list in popup is done via built-in completion popup which (currently) can't have borders. There are plans to add it upstream though (see neovim/neovim#25541).

Closing as duplicate of #1168 and #741

**Closed by echasnovski** 2024-10-09 10:09 UTC
Labels: duplicate, mini.completion
