### ISSUE TITLE
[Mini.Files] Attempt to index a nil value error when press <Tab> or using bnext command with cursor in mini.files 

### ISSUE THREAD

**Issue by bnhtho** [echasnovski/mini.nvim#1235] opened 2024-09-20 09:02 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

It seems everytime switch buffer command by using `:bnext` comment when cursor still in Mini.files windows, it give `Attempt to index a nil value error` bug

### Neovim version

0.10.1

### Steps to reproduce

1 . Turn on mini.files command (:lua MiniFiles.open())
2. Open file by press `L` (default keybind) - Still normal 
3. Press `<tab>` or using `:bnext` command - Error happened

### Expected behavior

Work normally

### Actual behavior

Neovim give these error:
```bash
Error executing vim.schedule lua callback: ...hnb/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:1515: attempt to index a nil value              

stack traceback:  
...hnb/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:1515: in function 'explorer_update_cursors'                                                ...hnb/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:812: in function 'close'                                                                  
 ...hnb/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:1350: in function '' vim/_editor.lua: in function <vim/_editor.lua:0>                                                                                              
```
![image](https://github.com/user-attachments/assets/d87fb088-0cd7-4cb8-b56a-4cd28d815a90)

**Comment by echasnovski** [comment] 2024-09-20 09:10
Thanks for the issue!

That error is an expected behavior. The reason is that executing `:bnext` means that you want to show another buffer in *current* (i.e. from 'mini.files') window. This doesn't make much sense from workflow perspective.

Also, I can not reproduce the error from the screenshot as it is most certainly not from the latest 'mini.nvim' (line 1515 [does not contain any calls](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/lua/mini/files.lua#L1515)). On Neovim>=0.10 it should show something like "E1513: Cannot switch buffer. 'winfixbuf' is enabled". See #1173.

Closing as it is most certainly a fixed behavior.

**Closed by echasnovski** 2024-09-20 09:10 UTC
Labels: duplicate, mini.files
