### ISSUE TITLE
Inaccurate Neogit highlights with base16

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#388] opened 2023-06-26 00:44 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

base16

### Description

Neogit applies its own highlighting, which happens to conflict with Mini's base16 module. This becomes noticeable in certain instances, such as the diffview, where red markers are displayed with a black foreground. I discovered that modifying nvim's colorscheme after opening Neogit results in colors being completely absent - I believe that Mini is likely overriding highlights that Neogit relies upon? 

### Neovim version

NVIM v0.9.1

### Steps to reproduce

1. `nvim`
2. `Neogit`

```lua
return {
  "CKolkey/neogit",
  cmd = 'Neogit',
  dependencies = {
    "nvim-lua/plenary.nvim",
    "sindrets/diffview.nvim"
  },
  keys = {
    { "<Leader>ng", "<cmd>Neogit<CR>", desc = "Toggle Neogit" }
  },
  opts = {
    integrations = {
      diffview = true
    }
  }
}
```

### Expected behavior

Proper highlighting with Neogit, particularly in/with its diffview markers.

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/f79248c7-3599-441d-b6cb-21eac09265ff)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/e279507b-9011-45a8-adab-bcd0aaedcfb3)

**Comment by echasnovski** [comment] 2023-06-26 08:59
Thanks for the issue!

I don't use 'neogit.nvim' myself, so will take later a look.

**Comment by echasnovski** [comment] 2023-06-30 17:29
@wroyca, I've only now noticed that you use 'CKolkey/neogit' while 'mini.base16' explicitly states that it [supports 'TimUntersberger/neogit'](https://github.com/echasnovski/mini.nvim/blob/4fd0f9c72fb54696442c81a64c71514c95239148/doc/mini-base16.txt#L51). I can see that there are a lot of opened issues and PRs in 'TimUntersberger/neogit', but it doesn't look like a completely abandoned project.

There doesn't seem to be an issue with 'TimUntersberger/neogit'.

> I discovered that modifying nvim's colorscheme after opening Neogit results in colors being completely absent - I believe that Mini is likely overriding highlights that Neogit relies upon?

I think the issue is quite opposite. When you load color scheme, it usually does `highlight clear` to delete all highlight groups prior to it and then defines its own. 'mini.base16' (and 'mini.hues' for that matter) doesn't define own highlight groups and relies on good defaults from 'neogit' repo (which are good enough).

Commit which your pointed out in CKolkey/neogit#45 has changes which remove `highlight default link` calls to define default highlighting. This is the correct way for plugin to define own persistent defaults for highlighting.

So I'll close this issue as it doesn't exactly come from 'mini.base16' while suggesting at least these solutions:
- Make 'CKolkey/neogit' use proper `hi default link` calls to create default highlighting.
- Apply 'mini.base16' color scheme before loading 'CKolkey/neogit'.
- Use 'TimUntersberger/neogit'.

**Closed by echasnovski** 2023-06-30 17:29 UTC
Labels: bug, mini.base16

**Comment by CKolkey** [comment] 2023-07-13 20:08
Hi! Just a heads up, Neogit has moved to an organization, `NeogitOrg`. I just merged my fork and hopefully all the colors are being linked properly here: https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/hl.lua 😅 

If there is something I'm doing wrong, then I'm definitely keen to make it better :)

**Comment by echasnovski** [comment] 2023-07-14 16:20
Thanks, @CKolkey! Congrats on the merge!

I'll look into double checking 'neogit' integration and update the username.

**Comment by CKolkey** [comment] 2023-07-17 13:22
I think thats pretty good advice - the biggest headache from this massive update has been related to colors. Which, on the one hand, is pretty cool that that's the _biggest_ issue, but also... not what I was going for. 

I'll make a `HIGHLIGHTS.md` file in the repo to break down what everything is.

**Comment by echasnovski** [comment] 2023-07-17 13:26
Do you think going back to creating default links to built-in groups is not worth it (against your vision)?

**Comment by CKolkey** [comment] 2023-07-17 20:44
> Do you think going back to creating default links to built-in groups is not worth it (against your vision)?

No, I think its definitely worth it. There's some "fancy" stuff I'm trying to make work, like context-aware cursorline highlights, changing the highlight of the hunk/section the cursor is in, stuff like that, which means I need the extra groups, but... I think I just didn't know how to set them up properly 🤷🏼 

Hopefully https://github.com/NeogitOrg/neogit/pull/617 fixes things for everyone :)
