### ISSUE TITLE
[ai] Covering match not found when using `cover_or_next`

### ISSUE THREAD

**Issue by beardedsakimonkey** [echasnovski/mini.nvim#123] opened 2022-08-30 02:31 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

ai

### Description

when executing an `inside` or `around` command with mini.ai configured with a `search_method` of `cover_or_next`, the next pair is chosen instead of the covering pair. This happens when the closing delimiter of the covering pair is on another line.

### Neovim version

0.7.0

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:lua require("mini.ai").setup({search_method = "cover_or_next"})`
3. Type the following in an empty buffer
```
(if (blah)
)
```
4. Put your cursor at the first column of the first line
5. `dab`

### Expected behavior

The whole thing should be deleted and you should be left with an empty buffer.  (this is the behavior of native `dab`)

### Actual behavior

The `next` match gets deleted
```
(if 
)
```

**Comment by echasnovski** [comment] 2022-08-30 06:28
This is [by design](https://github.com/echasnovski/mini.nvim/blob/085baefa6aca44526be621b15e7b688f996c2daf/doc/mini.txt#L727-L733). It is usually helpful if cursor is inside some big covering region but you want to select next. If you don't like it, you can set search method to `'cover'` and use "last"/"next" mappings to select previous/next textobject.

Truth be told, I a little bit regret this design decision after implementing "last"/"next" mappings, but originally they were not there. Also as you are not the first one to report this, I wonder how to make the note about this behavior more stand out.

Duplicate of #116.

**Closed by echasnovski** 2022-08-30 06:28 UTC
Labels: bug
