### ISSUE TITLE
(mini.files) Only show confirmation dialog on changes

### ISSUE THREAD

**Issue by smjonas** [echasnovski/mini.nvim#502] opened 2023-10-03 11:47 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I sometimes accidentally enter insert mode while navigating in the mini.files window. This causes the border color of the window to change (signalling a change to the file system) even though nothing changed (see below). The color stays like this even if I leave insert mode again.

 
![image](https://github.com/echasnovski/mini.nvim/assets/40792180/0b38bbc6-7fb2-46fc-8562-50afa7ff2b7a)

Would it be possible to only change the behavior so that the window border is only updated if the buffer contents changed? Currently, it seems to be triggered on InsertEnter.

**Comment by echasnovski** [comment] 2023-10-03 11:54
Thanks for creating this! This should already by the case.

I'd guess that you are using Neovim nightly, right? Coincidentally, I've discovered this today. The root cause here seems to be neovim/neovim#25490. I'll wait some time to see if this gets resolved, because I tried to fix it regardless but couldn't find anything quickly.

**Comment by smjonas** [comment] 2023-10-03 11:58
Thanks for the quick response!

> I'd guess that you are using Neovim nightly, right?

Yes, that's right (`v0.10.0-dev-9afbfb4`).

**Comment by echasnovski** [comment] 2023-10-04 11:33
Unfortunately, the issue seems to be stemming from Vim with behavior brought recently by merging a Vim patch. Needs to wait a little longer to see the resolution.

**Comment by echasnovski** [comment] 2023-10-17 17:58
This should be now fixed on latest Neovim nightly. Albeit, with introduction of a slightly different issue in the same space: simply pressing `o` or `O` now don't change border color. This seems like a regression introduced in upstream vim after fixing original `TextChangedI` issue. It is tracked in vim/vim#13367, so should be taken care of eventually.

**Closed by echasnovski** 2023-10-17 17:58 UTC
Labels: bug, mini.files

**Comment by echasnovski** [comment] 2023-10-28 08:03
After porting of 9.0.2075 Vim patch, it should now work as expected.
