### ISSUE TITLE
mini.animate: animation freezes at end of document when holding down movement key

### ISSUE THREAD

**Issue by Subjective** [echasnovski/mini.nvim#242] opened 2023-02-26 22:53 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

I just wanted to say I'm really enjoying using your plugins. I've used Nescroll for quite a while, but after finding out you made a plugin with the same capabilities plus more, I knew I had to switch over. However, one tiny thing that has been bothering me is how animations are held down movement bindings are handled compared to Neoscroll.

When holding down a cursor movement binding like `<C-d>`/`<C-u>` to scroll through a window, I've noticed that the movement will be animated until reaching nearly the top or bottom, at which point the animation freeze up until letting go of a the movement key.

### Neovim version

0.8.3

### Steps to reproduce

1. Open any page with more lines than are visible in the frame of a window.
2. Hold cursor movement binding like `<C-d>`/`<C-u>` or `<C-f>`/`<C-b>` to scroll until end of page. The animation will freeze before reaching the end. 
3. Let go of the key. The cursor will jump however amount specified by the movement binding.

### Expected behavior

I'm used to the behavior in Neoscroll where holding down a movement binding will continue scrolling until the end of a page.
![Screen Recording 2023-02-26 at 2 17 37 PM](https://user-images.githubusercontent.com/56745535/221441209-d1f43671-7666-48b3-b48c-3ef157ce951b.gif)

### Actual behavior

While holding down `<C-d>`, the window will continue scrolling down until line 266, at which point I need to let go of `<C-d>` before the cursor finally jumps to the end.

![Screen Recording 2023-02-26 at 2 17 37 PM](https://user-images.githubusercontent.com/56745535/221441151-45cdff0a-84cc-4eb1-96c5-6a6ad7239588.gif)

**Comment by echasnovski** [comment] 2023-02-27 09:42
Hi, thanks! Hope you keep enjoying them!

Hmm... Yes this is not ideal. Not critical, dare I say, but it would be better without this.

One thing I'd note right away is that it won't scroll past the end of buffer because built-in `<C-d>` doesn't. You can execute `:lua MiniAnimate.config.scroll.enable = false` and reproduce your steps.

Important thing to know about 'mini.animate' is that it is design to not rely on any mappings. This both allows animating more movements and restricts the quality for some of them. This is why it will never scroll past the end of buffer, because `<C-d>` doesn't. While 'neoscroll.nvim' can do that because it remaps `<C-d>` and friends.

Another important thing to know is that scroll animation is asynchronous and modifies current view (top line and cursor position). This also means that it allows other user scroll commands **while scroll is active** and **executes them right away forgetting about previous animation**.

It seems to be exactly what is happening here. When last buffer line becomes close (so one scroll step becomes relatively big) the "next" scroll command from holding `<C-d>` takes place when no movement due to animation step took place. This overrides previous command and tells 'mini.animate' to repeat the movement. Which gets overridden by next `<C-d>`, and so on.

I'll see what I can do here, but my hopes are not high at the moment.

**Comment by echasnovski** [comment] 2023-02-27 10:08
Yes, it indeed does seem like what is happening.

I can suggest trying different timing function. Something like this:
```lua
require('mini.animate').setup({
  scroll = {
    timing = function(_, n) return math.min(250 / n, 5) end,
  }
})
```

It basically says that if single default step (which makes any animation 250 milliseconds long) takes more than 5 milliseconds, use 5 milliseconds. To me it solves this issue. You might tweak number according to the right of how your OS treats holding key.

**Comment by Subjective** [comment] 2023-02-27 22:38
Thanks for the quick reply! The timing function you provided solved the scrolling issue. 

A bit off topic, but I've also noticed a bit of a ghosting/afterimage on the cursor while scrolling quickly. Is there any way to disable the animation specifically while scrolling?

**Comment by echasnovski** [comment] 2023-02-28 09:18
> Still, I've noticed that repeatedly hitting and results in way better performance compared to holding them down, probably because my key repeat rate is set to the max. I tried playing around with the timings a bit, but to no avail. Turning down my system key repeat rate made the scroll animation significantly smoother, but at the cost of slowing down h,j,k,l movement on key hold. Might it be possible to set a manual delay for when the plugin will register another key while scrolling?

Probably "no" on manual delay for key registering. Mostly because it will conflict with genuine user command to make two movements in a row. But also because how animation registering works is very fragile and is a result of painful tweaking process until got just about right for most cases. Besides, if lowering key repeat rate makes animation smoother and continuous hjkl worth, then it is a double win in my book :)

I did thing for a second that using throttling predicate for subscroll can solve the issue, but it makes it only worse. It is meant to decide if *animation* should be done, not if *movement* should be done. But nevertheless, here is my attempt for possible future reference:

```lua
local latest_timestamp = 0
local throttle_ms = 50
local throttle_scroll = function()
  local cur_time = vim.loop.hrtime()
  local res = 0.000001 * (cur_time - latest_timestamp) > throttle_ms
  if res then latest_timestamp = cur_time end
  return res
end

local animate = require('mini.animate')
animate.setup({
  scroll = {
    subscroll = animate.gen_subscroll.equal({ predicate = throttle_scroll }),
  },
})
```

------

> Is there any way to address the distance at which a cursor animation will trigger? Dashboards like stratify/alpha usually have menu options that are 2 lines apart, which causes the animation to trigger while switching between them. In these cases, the animation looks rather jarring.

Yes, via `cursor.path` option combined with `gen_path.line({ predicate = ... })` (or any other path you'd like):

```lua
local animate = require('mini.animate')
animate.setup({
  cursor = {
    path = animate.gen_path.line({
      predicate = function(destination) return destination[1] < -2 or 2 < destination[1] end,
    }),
  },
})
```

You can also set this predicate only for buffer via creating `vim.b.minianimate_config` inside autocommand.

------

> Also, there tends to be a ghosting/afterimage on the cursor while scrolling quickly. Is it possible to disable the cursor animation specifically while scrolling? And to disable scrolling during "G"/"gg" movements, as it's not as useful in those situations when the final movement location is apparent?

Well, it [tries not to animate during scroll](https://github.com/echasnovski/mini.nvim/blob/c3c8e950e81c7f941003e355146f669f087922ed/lua/mini/animate.lua#L1165-L1166). The problem is that cursor movement can trigger *just before* or *just after* scroll, which makes it hard to make perfect condition. I agree, it would be better without it, but don't think it has high priority.

**Comment by Subjective** [comment] 2023-03-01 01:03
Wow, thanks for providing such detailed responses to all my questions! 

> Probably "no" on manual delay for key registering. Mostly because it will conflict with genuine user command to make two movements in a row. But also because how animation registering works is very fragile and is a result of painful tweaking process until got just about right for most cases.

Hmmm... Maybe there's a way to external set the key repeat for `<C-d>` and `<C-u>`, though that does seem like quite the hassle beyond being system dependent. I think I'll just adjust to tapping instead of holding them down, it's probably more precise to do things that way anyways.

> The problem is that cursor movement can trigger just before or just after scroll, which makes it hard to make perfect condition.

Aww, well good to know. I've actually found that the scrolling animation alone is what's helping me track long distance movements, though the animation does provide a lot of nice eye-candy.

Thanks again for your insights, you've done so much for the community singlehandedly providing so many high-quality plugins!

**Comment by echasnovski** [comment] 2023-03-01 08:12
Glad you like them!

Closing this then, as it seems there is nothing more appropriate than already suggested can be done here.

**Closed by echasnovski** 2023-03-01 08:12 UTC
Labels: bug, mini.animate
