### ISSUE TITLE
mini.surround misinterprets surrounding characters

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#1223] opened 2024-09-16 21:44 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Surround

### Description

MiniSurround does not properly match surrounding characters when using the replace command. It seems to get confused with the next line. For example, when using sr"', the following issue occurs:

##### Initial content:

```diff
| vim.api.nvim_create_autocmd({ "VimEnter", "VimResume", "ColorScheme" }, 
  vim.api.nvim_create_autocmd({ "VimEnter", "VimResume", "ColorScheme" },
```

##### After using sr"':

```diff
vim.api.nvim_create_autocmd({ "VimEnter", "VimResume", "ColorScheme' }, 
vim.api.nvim_create_autocmd({ 'VimEnter", "VimResume", "ColorScheme" },
```

### Neovim version

NVIM v0.10.1 Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### Steps to reproduce

Here’s the corrected and formatted version:

1. `nvim -u minimal.lua`
2. `lua require("mini.surround").setup()`
3. Open empty files and write the following:
    ```lua
    vim.api.nvim_create_autocmd({ "VimEnter", "VimResume", "ColorScheme" },
    vim.api.nvim_create_autocmd({ "VimEnter", "VimResume", "ColorScheme" },
    ```

4. Move the cursor to the beginning and try to replace `"` with `'`.
5. Notice the broken behavior.

### Expected behavior

The surrounding characters should be replaced correctly, so `"VimEnter"` should become `'VimEnter'`.

### Actual behavior

https://github.com/user-attachments/assets/06c76d9d-2d58-4c4c-8db3-53d24998fbae

**Comment by echasnovski** [comment] 2024-09-17 09:59
Thanks for the issue!

This works as intended. The default `search_method` [is `'cover'`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-surround.txt#L526) which means that surrounding is searched in a way that left part is before and right part is after the cursor (or more precisely: left part is before left edge of reference region and right part is after right edge).

When called from the first line, it doesn't find any surrounding (as it mentions in the message below) and in the second line it correctly identifies last `"` on previous line and first `"` on current line as covering surrounding.

To surround "next"/"previous" surrounding I'd recommend explicitly use `srn` / `srl` variants. Or set different default search method, like this: `require('mini.surround').setup({ search_method = 'cover_or_next' })`.

Closing as everything working as expected.

**Closed by echasnovski** 2024-09-17 09:59 UTC
Labels: mini.surround

**Comment by wroyca** [comment] 2024-09-17 11:00
> Thanks for the issue!
> 
> This works as intended. The default `search_method` [is `'cover'`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-surround.txt#L526) which means that surrounding is searched in a way that left part is before and right part is after the cursor (or more precisely: left part is before left edge of reference region and right part is after right edge).
> 
> When called from the first line, it doesn't find any surrounding (as it mentions in the message below) and in the second line it correctly identifies last `"` on previous line and first `"` on current line as covering surrounding.
> 
> To surround "next"/"previous" surrounding I'd recommend explicitly use `srn` / `srl` variants. Or set different default search method, like this: `require('mini.surround').setup({ search_method = 'cover_or_next' })`.
> 
> Closing as everything working as expected.

This actually also happen with `cover_or_next`

**Comment by echasnovski** [comment] 2024-09-17 11:11
> This actually also happen with `cover_or_next`

I can not reproduce. The search is [first performed in current line and only then in neighborhood](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-surround.txt#L522-L523). It means that with `"cover_or_next"` search method, it first tries to find covering surrounding inside current line and fails which is followed by next surrounding and succeeds.

**Comment by wroyca** [comment] 2024-09-17 11:16
> > This actually also happen with `cover_or_next`
> 
> I can not reproduce. The search is [first performed in current line and only then in neighborhood](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-surround.txt#L522-L523). It means that with `"cover_or_next"` search method, it first tries to find covering surrounding inside current line and fails which is followed by next surrounding and succeeds.

Interesting, I can reproduce with the above example but also with more complex ones e.g.:

https://github.com/user-attachments/assets/832be835-27fa-4505-9018-7ada2a6b6d88

**Comment by echasnovski** [comment] 2024-09-17 11:28
> Interesting, I can reproduce with the above example but also with more complex ones e.g.:

The initial issue was "Move the cursor to the beginning and try to replace `"` with `'`.". It explicitly works in demo the way you described as expected behavior.

All other cases work as expected and [as documented](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-surround.txt#L522-L525). Searching is performed in these steps until the first success:
- Try finding covering surrounding in current line.
- Try finding next surrounding in current line.
- Try finding covering surrounding in the whole neighborhood (current line plus `config.n_lines` before and after0.
- Try finding next surrounding in the whole neighborhood.
- Say that nothing can be found.

Each example in the demo works like this. The quotes are not checked for being balanced before/after, they are just another surrounding pair (same as `(` / `)`, etc.).
