### ISSUE TITLE
(mini.ai) Incorrect selection between pairs

### ISSUE THREAD

**Issue by mehalter** [echasnovski/mini.nvim#392] opened 2023-06-27 17:09 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

When doing a selection of something with pairs like `i{` it is selecting the incorrect level if there is a more nested pair on the current line. Here are a few examples (where `|` indicates the cursor location):

### Working Examples

```lua
local test1 = {
  "He|llo",
  "World",
}
```

`vi{` highlights all of the `{}` block

```lua
local test2 = {
  "He|llo",
  "World",
  { "Testing" },
}
```

`vi{` highlights all of the outermost `{}` block

```lua
local test3 = { "He|llo", "World", { "Testing" } }
```

`vi{` highlights all of the outermost `{}` block

### Failing Examples

```lua
local test_fail = {
  "He|llo", "World", { "Testing" },
}
```

`vi{` highlights `{ "Testing" }`

```lua
local test_fail2 = {
| { "Hello" },
  { "World" },
  { "Testing" },
}
```

`vi{` highlights `{ "Hello" }`. This case is particularly frustrating because code written in this manner leaves exactly 2 characters in which I can place my cursor and successfully highlight the outermost `{}`. I have to be exactly on the opening or the closing `{` and I have nowhere inside the `{}` in which I can use the text object successfully

### Neovim version

0.9.1

### Steps to reproduce

1. `nvim -nu minimal.lua` (you can use as minimal of a configuration as you can with just `mini.ai` enabled)
2. See the above examples and try to replicate the behavior
3. Here is a concrete example that demonstrates different behavior from default vim. Open a buffer with the following content:

```lua
local test1 = {
  "F|oo", { "Hello" },
  { "World" },
}
```

4. Put your cursor somewhere in the `"Foo"` string (as indicated above by `|`)
5. Run `vi{`
6. Without `mini.ai` it will highlight within the outside `{}`, with `mini.ai` it will highlight `"Hello"`

### Expected behavior

If I am trying to use a text object within a pair of things like `{}`, it would be nice to validate if I am currently in a pair before looking for the next pair within the line. If there is no outer pair that I am currently in, then look for the next one in the line. This is how the default behavior of `vi{` or `va{` works as well which `mini.ai` is replacing.

### Actual behavior

This is described above, but I will copy/paste it again in a details tag:

<details><summary>Copy/Paste of behavior from description</summary>

### Working Examples

```lua
local test1 = {
  "He|llo",
  "World",
}
```

`vi{` highlights all of the `{}` block

```lua
local test2 = {
  "He|llo",
  "World",
  { "Testing" },
}
```

`vi{` highlights all of the outermost `{}` block

```lua
local test3 = { "He|llo", "World", { "Testing" } }
```

`vi{` highlights all of the outermost `{}` block

### Failing Examples

```lua
local test_fail = {
  "He|llo", "World", { "Testing" },
}
```

`vi{` highlights `{ "Testing" }`

```lua
local test_fail2 = {
| { "Hello" },
  { "World" },
  { "Testing" },
}
```

`vi{` highlights `{ "Hello" }`. This case is particularly frustrating because code written in this manner leaves exactly 2 characters in which I can place my cursor and successfully highlight the outermost `{}`. I have to be exactly on the opening or the closing `{` and I have nowhere inside the `{}` in which I can use the text object successfully
</details>

**Comment by echasnovski** [comment] 2023-06-27 17:24
Thanks for a such detailed issue!

This is intentional and [is described in documentation](https://github.com/echasnovski/mini.nvim/blob/a4241b6f51393d5e4d91a12d94e386bae287dae5/doc/mini-ai.txt#L415-L418) ([here](https://github.com/echasnovski/mini.nvim/blob/a4241b6f51393d5e4d91a12d94e386bae287dae5/doc/mini-ai.txt#L492-L498) with a bit more details). Main motivation is that performing operation inside current line (or, rather, lines of current selection) is more common than across multiple lines. When there is covering pair within 1-2 lines, then it might seem not intuitive, but selecting pair which is outside of visible text is frustrating.

To always select only covering pair, use `search_method = 'cover'`. This means if you want to select next/previous match, use `an`/`in`/`al`/`il` explicitly. Presence of this workflow change is also the reason for such choice of default behavior.

Closing as not a bug, but feature :)

**Closed by echasnovski** 2023-06-27 17:24 UTC
Labels: mini.ai

**Comment by mehalter** [comment] 2023-06-27 17:34
Thanks for the quick response! Yeah I guess this is coming from being very used to the default vim behavior after decades of muscle memory 😅 I can definitely understand the methodology you are using. I think the other thing is that even in the case where things are much further away, it's much easier to move into the pairs within a line than to jump outward into the outermost `{` in this case.

Also `cover` doesn't work in this case because this breaks the simple case of:

```lua
local foo, bar = "He|llo", { "World" }
```

doing `vi{` with the cursor in the `"Hello"` doesn't select `"World"` as the default vim behavior does.

Would it be possible then for this to be a feature request to change the priority of `line` over `neighborhood`? It would be nice to be able to achieve the default vim behavior rather than disrupting that sort of workflow.

I would really like to use this plugin and the feature of selecting balanced pairs is truly a killer feature, but definitely being able to be compatible with the default vim behavior as well I think.

**Comment by echasnovski** [comment] 2023-06-27 18:00
> Also `cover` doesn't work in this case because this breaks the simple case of:
> 
> ```lua
> local foo, bar = "He|llo", { "World" }
> ```
> 
> doing `vi{` with the cursor in the `"Hello"` doesn't select `"World"` as the default vim behavior does.

Yes, it does not. But making conscious decision that you want to select "next textobject" and type `vin{` (or `vin}` which is slightly different) is something to get used to quite quickly. At least, for me it was. But otherwise having occasional hiccups when want to select covering textobject in presence of the one in the same line is also acceptable to me.

> Would it be possible then for this to be a feature request to change the priority of `line` over `neighborhood`? It would be nice to be able to achieve the default vim behavior rather than disrupting that sort of workflow.

At the moment I don't think this part of 'mini.ai' design will change. Having it behind a config option is also not really good for "features/maintenance" balance.

**Comment by mehalter** [comment] 2023-06-27 18:05
Ok, thank you for your time. I guess the only question is just out of curiosity how you would do a selection task given a starting point. If I have the current situation:

```lua
local x = {
  "Hello", { "Foo" },
  "W|orld", { "Bar" },
  "Welp", { "Zoom" },
}
```

How would you go about selecting the outermost `{}` with the default `cover_or_next` selector? Other than cases such as this, the `cover_or_next` is nearly what I want each time so I would rather have a way to maybe rethink this one single case?

**Comment by mehalter** [comment] 2023-06-27 18:32
ah that's perfect :) thank you so much!
