### ISSUE TITLE
[feat] add ignore filetype setting to config

### ISSUE THREAD

**Issue by kaiphat** [echasnovski/mini.nvim#423] opened 2023-07-18 10:52 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

trailspace

### Description

I have highlighted trailspace in Lazy buffer, when updating plugins. How can i disable this behaviour?

**Comment by kaiphat** [comment] 2023-07-18 10:53
![Uploading image.png…]()

**Comment by kaiphat** [comment] 2023-07-18 10:53
![image](https://github.com/echasnovski/mini.nvim/assets/53742299/42c0a380-8755-4942-9bdd-44621735dd9e)
Red color

**Comment by echasnovski** [comment] 2023-07-18 11:19
This is already possible via buffer-local variables. See [this section in help file](https://github.com/echasnovski/mini.nvim/blob/34acb9bd6d2f88c57d21f6a261ddba6a740651f7/doc/mini-trailspace.txt#L35-L43).

Adding something like this should remove highlighting in 'lazy.nvim' buffer:
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'lazy',
  callback = function(data)
    vim.b[data.buf].minitrailspace_disable = true
    vim.api.nvim_buf_call(data.buf, MiniTrailspace.unhighlight)
  end,
})
```

Somewhat a duplicate of #52 and others.

**Closed by echasnovski** 2023-07-18 11:19 UTC
Labels: duplicate, question, mini.trailspace
