### ISSUE TITLE
`init.lua` gets neovim icon, even if it is not a nvim project

### ISSUE THREAD

**Issue by chrisgrieser** [echasnovski/mini.nvim#1384] opened 2024-12-06 15:01 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.icon

### Description

`mini.icons` assigns the neovim glyph to a file named `init.lua`. However, the name is not unique to neovim configs/plugins, but a standard for the lua language itself for the file of a module. As such, the filename `init.lua` is used in many non-nvim projects, and files such as `~/.config/hammerspoon/init.lua` also get the nvim icon, even though they have nothing to do with neovim.

### Neovim version

NVIM v0.10.2

### Steps to reproduce

Run `MiniIcons.get("file", "~/.config/hammerspoon/init.lua")`

### Expected behavior

Only use neovim glyph when in an nvim project.

### Actual behavior

always uses neovim glyph for `init.lua` files

**Comment by echasnovski** [comment] 2024-12-06 15:17
Thanks for the issue!

This is a deliberate design choice, I'd imagine majority of 'mini.icons' users will see file named 'init.lua' only when dealing with Neovim config or plugins.

You can disable it with the following config:

```lua
require('mini.icons').setup({
  file = {
    ['init.lua'] = { glyph = '󰢱', hl = 'MiniIconsAzure' },
  },
})
```

Closing as working as intended.

**Closed by echasnovski** 2024-12-06 15:17 UTC
Labels: wontfix, mini.icons

**Comment by chrisgrieser** [comment] 2024-12-06 15:28
> I'd imagine majority of 'mini.icons' users will see file named 'init.lua' only when dealing with Neovim

That may be true, but for the rest of us, the plugin will by default show a completely wrong icon.

Wouldn't it simply be possible to add an extra condition, e.g., requiring that the path of the `init.lua` must have the string `nvim` somewhere?

**Comment by echasnovski** [comment] 2024-12-06 15:59
> Wouldn't it simply be possible to add an extra condition, e.g., requiring that the path of the `init.lua` must have the string `nvim` somewhere?

Nope, for several reasons:
- Customizing icons for `'file'` category can be done only based on file name. Including default values. Any more than that would require setting custom filetype for files which are named 'init.lua' and are descendants of 'nvim' directory.
- For it to be more useful, users/plugins should supply full path to `MiniIcons.get('file', path)`. This is currently not the case in general (aside 'mini.nvim' modules) due to most plugins using 'nvim-web-devicons' interface only uses file basenames.

> That may be true, but for the rest of us, the plugin will by default show a completely wrong icon.

My hope is that either adjusting custom config or not caring much about this little Easter egg would not be a big burden.
