### ISSUE TITLE
[mini.files] Failed to switch to window 1001, not working well with tabfind

### ISSUE THREAD

**Issue by towry** [echasnovski/mini.nvim#425] opened 2023-07-21 01:05 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Setting the mini.files as default explorer, got errors when using with `tabfind` command.

### Neovim version

0.9.1

### Steps to reproduce

init.lua:

```lua
vim.g.mapleader = ' '

local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { 'nvim-lua/plenary.nvim' },
  { 'stevearc/dressing.nvim', opts = {} },
  {
    "echasnovski/mini.files",
    enabled = true,
    opts = {
      options = {
        -- Whether to use for editing directories
        -- Disabled by default in LazyVim because neo-tree is used for that
        use_as_default_explorer = true,
      },
    },
  },
  {
    enabled = true,
    'echasnovski/mini.bufremove',
    keys = {
      {
        '<S-q>',
        function()
          require('mini.bufremove').wipeout(0)
          vim.cmd('q')
        end,
        desc = 'Close',
      }
    },
  }
  -- add any other pugins here
}

require('lazy').setup({
  spec = plugins,
  root = root .. '/plugins',
  defaults = {
    lazy = false,
  },
  state = root .. '/lazy/state.json',
  performance = {
    cache = {
      enabled = false,
    }
  }
})

-- add anything else here
vim.opt.termguicolors = true
vim.cmd([[colorscheme default]])
```

## Steps to reproduce

1. nvim -u init.lua
2. wait for the plugins to be installed and ready.
3. quit and run `nvim -u init.lua` again.
4. run `:tabfind .`, it will create a new tab with directory `.` as cwd, and `mini.files` is opened because have set it as default.
5. presss `q` to trying to quit `mini.files`.

### Expected behavior

Should work as the same as run `nvim -u init.lua .` which has no errors when quitting mini.files.

### Actual behavior

error happened.

**Comment by echasnovski** [comment] 2023-07-21 07:26
Thanks for the issue!

I can reproduce. Seems to be because in this case during execution of `MiniFiles.close()` doesn't properly verify that target window is valid.
I'll look into the best way of fixing this.

**Comment by echasnovski** [comment] 2023-07-22 08:28
Should be fixed on latest `main` branch.

Didn't find a better solution than just using `pcall()` to not throw an error in this case.

**Closed** 2023-07-22 08:27 UTC
Labels: bug, mini.files
