### ISSUE TITLE
Enable mini.splitjoin toggle for next match on the line

### ISSUE THREAD

**Issue by vandalt** [echasnovski/mini.nvim#496] opened 2023-09-30 02:56 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.splitjoin

### Description

Hi,

I was not able to figure if it was possible to do this already based on the docs and help. If I have a function like this:

```python
def something(a, b, c):
    pass
```

and my cursor is on `something`, pressing `gS` does not split or join the arguments. The cursor has to be within the brackets. Is there a way to match the next (or previous) bracket on the line and use this for the split/join?

Thank you!

**Comment by echasnovski** [comment] 2023-09-30 05:00
Hi!

Yes, only supporting split/join arguments under cursor [is by design](https://github.com/echasnovski/mini.nvim/blob/1fdbb864e2015eb6f501394d593630f825154385/doc/mini-splitjoin.txt#L10). This is mostly because finding next/previous brackets is not trivial and is already possible [with 'mini.ai'](https://github.com/echasnovski/mini.nvim/blob/1fdbb864e2015eb6f501394d593630f825154385/doc/mini-ai.txt#L133) (with default or compatible `search_method`).

Closing as not planned.

**Closed by echasnovski** 2023-09-30 05:00 UTC
Labels: feature-request, mini.splitjoin
