### ISSUE TITLE
Opening a Telescope window while the mini.files file explorer is opened closes both windows

### ISSUE THREAD

**Issue by nikololiahim** [echasnovski/mini.nvim#1292] opened 2024-10-18 22:35 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Opening a Telescope window while the mini.files file explorer is opened closes both windows. However, opening the file explorer when the Telescope window is opened behaves as expected - closing the Telescope window and opening the file explorer.

### Neovim version

NVIM v0.11.0-nightly+82b02ae

### Steps to reproduce

1. `nvim -nu minimal.lua`
1. Press `<space>fm` to open the mini.files file explorer.
1. Press `<space>/` to open the Telescope window

```lua
---@diagnostic disable: undefined-global
-- DO NOT change the paths and don't remove the colorscheme
vim.g.mapleader = " "
vim.g.maplocalleader = " "
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "echasnovski/mini.files",
    version = "*",
    keys = {
      {
        "<leader>fm",
        function()
          require("mini.files").open(vim.api.nvim_buf_get_name(0), true)
        end,
        desc = "Open mini.files (Directory of Current File)",
      },
    },
  },
  {
    "nvim-telescope/telescope.nvim",
    keys = function()
      local builtin = require("telescope.builtin")
      return {
        {
          "<leader>/",
          function()
            builtin.live_grep({})
          end,
          desc = "Live grep",
        },
      }
    end,
    dependencies = { "nvim-lua/plenary.nvim" },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

```
![demo](https://github.com/user-attachments/assets/0c44a04a-6154-4f82-8b24-f6e7a6ecf3c3)

### Expected behavior

The file explorer should stay opened, when the Telescope window is opened.

### Actual behavior

Both windows disappear after a significant delay.

**Comment by echasnovski** [comment] 2024-10-19 13:05
Thanks for the issue!

This is an expected behavior. The reason for this is to detect whether the user left the explorer windows (accidentally, or via mouse) and autoclose explorer. Opening a Telescope window is treated in the same way: as it is not a 'mini.files' buffer, explorer is closed (via `MiniFiles.close()`) and focus is returned to its original target window.

Couple of extra notes:
- It is recommended to first close an explorer and only then use any other functionality which changes buffer/window.
- There is no such problem with 'mini.pick' :)

Closing as working as expected.

**Closed by echasnovski** 2024-10-19 13:05 UTC
Labels: mini.files

**Comment by drowning-cat** [comment] 2025-01-04 16:27
```lua
vim.api.nvim_create_autocmd('User', {
  pattern = 'TelescopeFindPre',
  -- stylua: ignore
  callback = function() require('mini.files').close() end,
})
```

**Comment by drowning-cat** [comment] 2025-01-04 20:16
Mason, Lazy, Telescope:
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = { 'lazy', 'mason', 'TelescopePrompt' },
  callback = function()
    local win = vim.api.nvim_get_current_win()
    MiniFiles.close()
    vim.fn.win_gotoid(win)
  end,
})
```

**Comment by ananyo141** [comment] 2025-02-02 08:21
For anyone using the new `Snacks.picker`, use `snacks_picker_preview` instead of `TelescopePrompt`.

**Comment by drowning-cat** [comment] 2025-02-08 19:17
Thanks to @ananyo141, I discovered [Snacks](https://github.com/folke/snacks.nvim/tree/main) and smoothly transitioned from [Telescope](https://github.com/nvim-telescope/telescope.nvim) to [Snacks.picker](https://github.com/folke/snacks.nvim/blob/main/docs/picker.md).

```lua
---@module 'snacks'

local snacks_picker_lines = Snacks.picker.lines
Snacks.picker.lines = function(...)
  MiniFiles.close()
  snacks_picker_lines(...)
end

vim.api.nvim_create_autocmd('FileType', {
  pattern = { 'snacks_picker_preview', 'mason', 'lazy' },
  callback = function()
    local win = vim.fn.win_getid()
    files.close()
    vim.fn.win_gotoid(win)
  end,
})
```

```lua
return {
  'folke/snacks.nvim',
  priority = 1000,
  lazy = false,
  -- ...
}
```
