### ISSUE TITLE
Mini-completion issues with Ansiblels

### ISSUE THREAD

**Issue by GNOMES** [echasnovski/mini.nvim#1282] opened 2024-10-15 20:38 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

I have found that mini.completion is not allowing me to auto complete module names like "ansible.builtin.*" where star is a string that doesn't start with an "a".

Typing the following yaml file:

```
- name: Test
  ansible.builtin.
```
    
I am presented with a very long 100+ list of auto complete options while auto completing the last line, ranging from ansible.builtin.add_host to ansible.builtin.azure_rm_webappslot. 
 
 If I try to type "ansible.builtin.dnf" (class I found this problem with), no auto complete options are available.
 
 I found that typing any class name that doesn't start with "a" does not appear (like ansible.builtin.systemd).
 
 
Ansible has a large variety of modules available. Is there a limit to the number of items that can appear in auto completion list?
 
I have verified that I am able to autocomplete modules such as ansible.builtin.dnf and ansible.builtin.systemd using CMP. 

-- with ansible.builtin.
![Screenshot 2024-10-15 at 15 21 46](https://github.com/user-attachments/assets/df13959f-96bc-43a3-9a33-4826712cf469)

-- after adding "d" to string
![Screenshot 2024-10-15 at 15 21 53](https://github.com/user-attachments/assets/ed2f0cc6-faa4-471d-bc91-32e91e339a17)

### Neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Steps to reproduce

```
return {
    {
        'echasnovski/mini.completion',
        event = 'InsertEnter',
        version = false,
        config = function()
            require('mini.completion').setup {
                lsp_completion = { source_func = 'omnifunc', auto_setup = false },
                window = {
                    info = { height = 25, width = 80, border = 'single' },
                    signature = { height = 25, width = 80, border = 'single' },
                },
            }
        end,
    },
    {
        'neovim/nvim-lspconfig',
        cmd = { 'LspInfo', 'LspInstall', 'LspStart' },
        ft = { 'yaml' },
        config = function()
            local capabilities = vim.lsp.protocol.make_client_capabilities()
            capabilities.textDocument.completion.completionItem.snippetSupport = false

            local servers = {
                ansiblels = {},
            }

            for server, config in pairs(servers) do
                require('lspconfig')[server].setup(vim.tbl_deep_extend('force', config, {
                    capabilities = capabilities,
                    on_attach = function(_, buf)
                        vim.api.nvim_set_option_value('omnifunc', 'v:lua.MiniCompletion.completefunc_lsp', { buf = buf })
                    end,
                }))
            end
        end,
    },
}

```
### Expected behavior

I should be able to do complete any module in the LSP

### Actual behavior

Currently auto completion fails to provide options that do not match modules matching "ansible.builtin.a*"

**Comment by echasnovski** [comment] 2024-10-16 08:04
Thanks for the issue!

I can not reproduce this *exact* case (I have installed `ansible-language-server`, but I guess I also need Ansible installed). My initial guess was that this is due to intentional limit of completion candidates number by the server, in which case it should supply `isIncomplete` field in the response. However, quick searching of 'ansible/vscode-ansible' doesn't show any usage of `isIncomplete` string.

If it *is* a case of positive `isIncomplete`, then 'mini.completion' doesn't support it, as it only makes request once. *Maybe* this might change in the (hopefully not so distant) future, but I'd need to confirm that this is the case here.

One implicit confirmation would be if pressing `<C-Space>` (to force two stage completion) at the stage of `ansible.builtin.d` (when there should be no completion shown) shows more relevant completion list.

Another, more definitive, way is to intercept the LSP's response and post it here (behind a spoiler, please). Here is how to do it:

- In your 'mini.completion' installed code, put [here](https://github.com/echasnovski/mini.nvim/blob/d4ce7d025f9c7bb4d55ebc4fd88987651e632893/lua/mini/completion.lua#L411) the line  `_G.request_result = H.completion.lsp.result`.
- Try reproducing the issue *up until typing `ansible.builtin.`*, i.e. when it shows an incomplete list.
- Exit Insert mode and execute the following command: `:lua vim.fn.append('.', vim.split(vim.inspect(_G.request_result), '\n'))`. This will insert LSP server response as lines below the cursor.
- Copy lines resulted from previous step and post it here behind a spoiler (`<details> ... </details>`).

**Comment by GNOMES** [comment] 2024-10-16 16:00
Using <C-Space> did not work:
    When line was "ansible.builtin" nothing was suggested.
    When line was "ansible.builtin." , options were to auto complete "ansible, builtin, name". 
    When line was "ansible.builtin.d" nothing was suggested.

Running your LSP logic dump gave 100k lines of json. Is there anything specific I can grep for you?

**Comment by echasnovski** [comment] 2024-10-16 16:13
> When line was "ansible.builtin.d" nothing was suggested.

If pressing `<C-Space>` in this scenario did not produce any completion suggestions, it is likely the issue is on the side of LSP server.

> Running your LSP logic dump gave 100k lines of json. Is there anything specific I can grep for you?

Yeah, pasting 100k lines is not good, thanks for spotting this. Although it should not be json, but a Lua table.

If the output has the structure of `result = { {...}, ..., {...} }` (i.e. an array of tables), then it is definitely an issue with LSP server: it basically says that these are the only valid candidates and *there are no more valid candidates*.

If the output has [this kind of structure](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#completionList), then could you remove all but first and last entries in `items` and paste the rest of the response?

**Comment by GNOMES** [comment] 2024-10-17 03:00
Apologies it looked like Json at first glance to me. The format matches the `result = { {` format you mentioned. Here are the top 50 lines:

<details>
<pre><code>
{ {
    result = { {
        documentation = "The ‘action’ to execute for a task, it normally translates into a C(module) or action plugin.",
        kind = 10,
        label = "action",
        sortText = "4_action",
        textEdit = {
          newText = "action",
          range = {
            ["end"] = {
              character = 2,
              line = 3
            },
            start = {
              character = 1,
              line = 3
            }
          }
        }
      }, {
        documentation = "Force any un-handled task errors on any host to propagate to all hosts and end the play.",
        kind = 10,
        label = "any_errors_fatal",
        sortText = "4_any_errors_fatal",
</code></pre>
</details>

**Comment by echasnovski** [comment] 2024-10-17 08:23
Yeah, this sort of response doesn't contain any information that there can possibly be any other completion candidates that server did not provide for performance reasons. So as far as 'mini.completion' knows, these are all possible candidates in that context.

I am completely not sure why 'nvim-cmp' works. Two possible explanations I can think about are 1) it makes separate request after every key (which doesn't seem to work in this case as forced `<C-Space>` doesn't work); or 2) it implements some mechanism that is present in VS Code, but not in LSP (and for which this particular LSP server is designed for). Both of these types of behavior will not be implemented in 'mini.completion' (1) for performance, 2) because it is not present in LSP specification).

There reason that there are too many possible completion candidates for built-in completion pop-up to handle seems to also be not true: there are about 2832 modules in total (according to [this](https://docs.ansible.com/ansible/2.8/modules/list_of_all_modules.html)) and built-in completion can work at least up to 10000 items.

------

All in all, I am afraid I don't see how this can be a 'mini.completion' issue. Closing for now, but if there are any additional info, please comment it here.

**Closed by echasnovski** 2024-10-17 08:23 UTC
Labels: mini.completion, needs-repro
