### ISSUE TITLE
mini.deps: Load local plugins

### ISSUE THREAD

**Issue by TheLazyLemur** [echasnovski/mini.nvim#1326] opened 2024-11-06 03:41 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Deps

### Description

It would be cool to be able to load local pluginsbin a similar way to Lazy. 

I believe the way Lazy does it is by specifying a dir.

**Comment by echasnovski** [comment] 2024-11-06 08:48
Thanks for the suggestion!

There are several way of using local plugins with 'mini.deps':
- Put plugin along the others in target 'pack/deps/opt' directory and add it in the 'init.lua' with `add({ name = 'plugin-dir-name', checkout = 'HEAD' })`. For example, this is the way [I personally manage 'mini.nvim'](https://github.com/echasnovski/nvim/blob/4064584ccf637eb08f6fa5684302883123996101/init.lua#L31).
- Have plugin into some directory and add it with `add({ name = '/full/path/to/plugin-dir-name', checkout = 'HEAD' })`.
- Assuming it is local and doesn't require updating, manage it as any other plugin with built-in packages. For example, along the 'pack/deps' directory create 'pack/local' directory and put either 'start/plugin-dir-name' or 'opt/plugin-dir-name' (with later explicit `vim.cmd('packadd plugin-dir-name')`).

Note that first two approaches require plugin to be a Git repository.

Closing as not planned.

**Closed by echasnovski** 2024-11-06 08:48 UTC
Labels: feature-request, mini.deps

**Comment by aidancz** [comment] 2024-11-28 05:24
@echasnovski

the second approach

```
Have plugin into some directory and add it with add({ name = '/full/path/to/plugin-dir-name', checkout = 'HEAD' })
```

doesn't seem to work

with these lines:

```
MiniDeps.add({
	name = "~/sync_git/nofrils",
	checkout = "HEAD",
})
```

i got:

```
E5113: Error while calling lua chunk: (mini.deps) `name` in plugin spec should not contain "/".
stack traceback:
        [C]: in function 'error'
        ...re/nvim/site/pack/deps/start/mini.deps/lua/mini/deps.lua:1591: in function 'error'
        ...re/nvim/site/pack/deps/start/mini.deps/lua/mini/deps.lua:992: in function 'expand_spec'
        ...re/nvim/site/pack/deps/start/mini.deps/lua/mini/deps.lua:475: in function 'add'
        /home/aidan/.config/nvim/lua/nofrils.lua:3: in main chunk
        [C]: in function 'require'
        /home/aidan/sync_git/arch_config/.config/nvim/init.lua:53: in main chunk
```

**Comment by echasnovski** [comment] 2024-11-28 08:51
> the second approach
> 
> ```
> Have plugin into some directory and add it with add({ name = '/full/path/to/plugin-dir-name', checkout = 'HEAD' })
> ```
> 
> doesn't seem to work

My bad, it should have been `source = ` instead of `name = `. But for local plugins I'd strongly recommend the third approach:

> * Assuming it is local and doesn't require updating, manage it as any other plugin with built-in packages. For example, along the 'pack/deps' directory create 'pack/local' directory and put either 'start/plugin-dir-name' or 'opt/plugin-dir-name' (with later explicit `vim.cmd('packadd plugin-dir-name')`).

**Comment by aidancz** [comment] 2024-11-28 13:15
> it should have been `source = ` instead of `name = `

thank you for your reply!

`source = "~/abc/def"` does not work, seems that tilde expansion is not supported, is this by design?

`source = "/home/aidan/abc/def"` does work, but a warning message will appear when i run nvim for the first time:

```
(mini.deps) Warnings in `nofrils` during installing plugin
warning: --filter is ignored in local clones; use file:// instead.
```

do i need to make any adjustments?
