### ISSUE TITLE
Rename through blockwise selection triggers a move operation.

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#1068] opened 2024-07-17 18:39 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

files

### Description

As per title, renaming file(s) and/or folder(s) through blockwise selection triggers a move operation.

### Neovim version

NVIM v0.10.0

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `lua require ("mini.files").setup()`
3. `lua MiniFiles.open()`
4. Create `hello/` and sync
6. With blockwise selection, rename `hello` to `world` and sync *(broken state)*

Additional notes:

Where I say to use blockwise selection, using operator instead (e.g., `d` as in `dw`) also leads to the same issue

### Expected behavior

With blockwise selection, renaming `hello/` to `world/` should work as intended.

### Actual behavior

With blockwise selection, renaming `hello/` to `world/` triggers a move operation.

![image](https://github.com/user-attachments/assets/545ce04e-e63b-490d-b21a-fc828cf4d32c)
![image](https://github.com/user-attachments/assets/ce48b8f3-1ed0-4a26-9957-1b25c94dd6ee)

https://github.com/user-attachments/assets/f8479897-443b-4bea-a5a2-db28ef0d7189

**Comment by echasnovski** [comment] 2024-07-18 06:42
Thanks for the issue!

I believe there is some misalignment about terminology. Blockwise selection is a selection with `<C-v>`, which results in a rectangular block of text being modified. From video demo it *looks like* the following steps are done:
- Delete name with `d$`. The reproduction will work with `<C-v>$d` also, but I don't think it is done in video.
- Insert new name with `i` followed by `world`.

In this case it indeed won't work because this sequence of steps modify concealed information 'mini.files' uses to track its entries. It is described [here](https://github.com/echasnovski/mini.nvim/blob/f20d8cd3a116ef65f022797de064a044b217ff53/doc/mini-files.txt#L235-L246) with [extra note in "Rename" section](https://github.com/echasnovski/mini.nvim/blob/f20d8cd3a116ef65f022797de064a044b217ff53/doc/mini-files.txt#L270-L271).

You can see why this doesn't work if after `d$` execute `:set conceallevel=0`: pressing `i` puts cursor *inside* region where it is not supposed to be. Typing `world` leads to modifying it (you can again execute `:set conceallevel=0` after typing it).

The suggested solution is to *not* use `d$` or `D` followed by `i`. Instead use either `C` directly or use `a` to start Insert mode.

Closing as "yes, it is a little confusing, but is documented as thoroughly as is reasonable".

**Closed by echasnovski** 2024-07-18 06:42 UTC
Labels: mini.files

**Comment by wroyca** [comment] 2024-07-18 11:16
> Thanks for the issue!
> 
> I believe there is some misalignment about terminology. Blockwise selection is a selection with `<C-v>`, which results in a rectangular block of text being modified. From video demo it _looks like_ the following steps are done:
> 
>     * Delete name with `d$`. The reproduction will work with `<C-v>$d` also, but I don't think it is done in video.
> 
>     * Insert new name with `i` followed by `world`.
> 
> 
> In this case it indeed won't work because this sequence of steps modify concealed information 'mini.files' uses to track its entries. It is described [here](https://github.com/echasnovski/mini.nvim/blob/f20d8cd3a116ef65f022797de064a044b217ff53/doc/mini-files.txt#L235-L246) with [extra note in "Rename" section](https://github.com/echasnovski/mini.nvim/blob/f20d8cd3a116ef65f022797de064a044b217ff53/doc/mini-files.txt#L270-L271).
> 
> You can see why this doesn't work if after `d$` execute `:set conceallevel=0`: pressing `i` puts cursor _inside_ region where it is not supposed to be. Typing `world` leads to modifying it (you can again execute `:set conceallevel=0` after typing it).
> 
> The suggested solution is to _not_ use `d$` or `D` followed by `i`. Instead use either `C` directly or use `a` to start Insert mode.
> 
> Closing as "yes, it is a little confusing, but is documented as thoroughly as is reasonable".

Thank for replying!

> Closing as "yes, it is a little confusing, but is documented as thoroughly as is reasonable".

That's odd, I don't remember it being the case before, but maybe some false memories are at play here; that said, this is currently severely impacting our work (it basically goes against the whole premise of mini.files) - so much that we end up opening an external file explorer (e.g., Nautilus) to rename folders - is there any kind of workaround we could apply to teach d$ or D? Otherwise I'm thinking that perhaps we can remap the key to C when mini.files is open and reset it once closed

**Comment by wroyca** [comment] 2024-07-18 17:38
> > That's odd, I don't remember it being the case before, but maybe some false memories are at play here;
> 
> I don't think there was a commit that changed this behavior after [3f267f8](https://github.com/echasnovski/mini.nvim/commit/3f267f87cc47a2630ee64583e136174b04cea34a) (which introduced the concept of "prefix").
> 
> > is there any kind of workaround we could apply to teach d$ or D?
> 
> As was suggested earlier, you can use `a` (or `A` to be extra safe) instead of `i` to start Insert mode.
> 
> > Otherwise I'm thinking that perhaps we can remap the key to C when mini.files is open and reset it once closed
> 
> Yes, this might also be doable by following similar [example of adding custom buffer-local mapping](https://github.com/echasnovski/mini.nvim/blob/db52ea9a1fd5183bb15f557db3fd6e504099bf06/doc/mini-files.txt#L407).

What I did in the end is a quick PoC patch to address invalid regions on best-effort basis:

```lua
H.buffer_compute_fs_diff = function(buf_id, ref_path_ids)
  if not H.is_modified_buffer(buf_id) then return {} end

  local path = H.opened_buffers[buf_id].path
  local lines = vim.api.nvim_buf_get_lines(buf_id, 0, -1, false)
  local res, present_path_ids = {}, {}

  -- Mini.nvim uses concealed information to track its entries, typically
  -- represented as id/icon/name, each serving as its own distinct "region." An
  -- issue arises when deleting a region, such as the name, which results in
  -- id/icon/ without any safeguard for the expected separation. For example,
  -- pressing i in this scenario places the cursor incorrectly inside id/iconX/
  -- instead of id/icon/X.
  --
  -- The strategy here involves filtering out situations where users might attempt
  -- to synchronize such input and then automatically correcting said region. This
  -- is possible as icons add one extra whitespace to account for their width,
  -- which we use as a rule to capture the input we need.
  --
  local function parse (string)
    -- We use the trailing slash as a marker.
    --
    local mark = string:find("/[^/]*%s*$")

    --
    --
    if mark then
      -- Capture the substring before and after the trailing slash marker.
      --
      local capture = {
        b = string:sub(1, mark - 1),
        a = string:sub(   mark + 1)
      }

      -- Sanitize the (after) substring following the marker to ensure it does not
      -- end with a trailing slash.
      --
      if capture.a:sub(-1) == "/" then
        capture.a = capture.a:sub(1, -2)
      end

      -- Find (and transform) the last whitespace occurence to a trailing slash.
      --
      mark = capture.a:find("%s[^%s]*$")
      if mark then
        capture.a = capture.a:sub(1, mark - 1) .. "/" .. capture.a:sub(mark + 1)
      end

      -- Lastly, capture the last whitespace occurence and add the region separator. NOTE:
      -- Preserve the existing whitespace.
      --
      return capture.b:gsub(" ", " /") .. capture.a
    end

    return string -- should be unreachable.
  end

  -- Process present file system entries
  for _, l in ipairs(lines) do
    -- TODO: Sanitization is not (yet) implemented, so be mindful of potential edge
    -- cases.
    l = (l and l:sub(1, 1) == '/') and parse(l) or l

    local path_id = H.match_line_path_id(l)
    local path_from = H.path_index[path_id]

    -- Use whole line as name if no path id is detected
    local name_to = path_id ~= nil and l:sub(H.match_line_offset(l)) or l

    -- Preserve trailing '/' to distinguish between creating file or directory
    local path_to = H.fs_child_path(path, name_to) .. (vim.endswith(name_to, '/') and '/' or '')

    -- Ignore blank lines and already synced entries (even several user-copied)
    if l:find('^%s*$') == nil and path_from ~= path_to then
      table.insert(res, { from = path_from, to = path_to })
    elseif path_id ~= nil then
      present_path_ids[path_id] = true
    end
  end

  -- Detect missing file system entries
  for _, ref_id in ipairs(ref_path_ids) do
    if not present_path_ids[ref_id] then table.insert(res, { from = H.path_index[ref_id], to = nil }) end
  end

  return res
end
```

```diff
From b686476a63fc3bdc96d15c5982969950be49fbaf Mon Sep 17 00:00:00 2001
From: William Roy <wroy@proton.me>
Date: Thu, 18 Jul 2024 13:36:36 -0400
Subject: [PATCH] fix!(files): try to handle invalid region input

---
 lua/mini/files.lua | 54 ++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 54 insertions(+)

diff --git a/lua/mini/files.lua b/lua/mini/files.lua
index 8b86480..c153528 100644
--- a/lua/mini/files.lua
+++ b/lua/mini/files.lua
@@ -2066,8 +2066,62 @@ H.buffer_compute_fs_diff = function(buf_id, ref_path_ids)
   local lines = vim.api.nvim_buf_get_lines(buf_id, 0, -1, false)
   local res, present_path_ids = {}, {}
 
+  -- Mini.nvim uses concealed information to track its entries, typically
+  -- represented as id/icon/name, each serving as its own distinct "region." An
+  -- issue arises when deleting a region, such as the name, which results in
+  -- id/icon/ without any safeguard for the expected separation. For example,
+  -- pressing i in this scenario places the cursor incorrectly inside id/iconX/
+  -- instead of id/icon/X.
+  --
+  -- The strategy here involves filtering out situations where users might attempt
+  -- to synchronize such input and then automatically correcting said region. That
+  -- is possible as icons add one extra whitespace to account for their width,
+  -- which we use as a rule to capture the input we need.
+  --
+  local function parse (string)
+    -- We use the trailing slash as a marker.
+    --
+    local mark = string:find("/[^/]*%s*$")
+
+    --
+    --
+    if mark then
+      -- Capture the substring before and after the trailing slash marker.
+      --
+      local capture = {
+        b = string:sub(1, mark - 1),
+        a = string:sub(   mark + 1)
+      }
+
+      -- Sanitize the (after) substring following the marker to ensure it does not
+      -- end with a trailing slash.
+      --
+      if capture.a:sub(-1) == "/" then
+        capture.a = capture.a:sub(1, -2)
+      end
+
+      -- Find (and transform) the last whitespace occurence to a trailing slash.
+      --
+      mark = capture.a:find("%s[^%s]*$")
+      if mark then
+        capture.a = capture.a:sub(1, mark - 1) .. "/" .. capture.a:sub(mark + 1)
+      end
+
+      -- Lastly, capture the last whitespace occurence and add the region separator. NOTE:
+      -- Preserve the existing whitespace.
+      --
+      return capture.b:gsub(" ", " /") .. capture.a
+    end
+
+    return string -- should be unreachable.
+  end
+
   -- Process present file system entries
   for _, l in ipairs(lines) do
+    -- TODO: Sanitization is not (yet) implemented, so be mindful of potential edge
+    -- cases.
+    l = (l and l:sub(1, 1) == '/') and parse(l) or l
+
     local path_id = H.match_line_path_id(l)
     local path_from = H.path_index[path_id]
```

**Comment by echasnovski** [comment] 2024-07-18 18:17
>   -- The strategy here involves filtering out situations where users might attempt
>   -- to synchronize such input and then automatically correcting said region. This
>   -- is possible as icons add one extra whitespace to account for their width,
>   -- which we use as a rule to capture the input we need.

Unfortunately, this does not generalize well because users can override prefix with `content.prefix`. It is more a coincidence that there is a space after an icon because this is a result of `default_prefix()`.

**Comment by wroyca** [comment] 2024-07-18 18:32
> > -- The strategy here involves filtering out situations where users might attempt
> > -- to synchronize such input and then automatically correcting said region. This
> > -- is possible as icons add one extra whitespace to account for their width,
> > -- which we use as a rule to capture the input we need.
> 
> Unfortunately, this does not generalize well because users can override prefix with `content.prefix`. It is more a coincidence that there is a space after an icon because this is a result of `default_prefix()`.

Correct. Still, it's definitely better than nothing (namely as it meets my needs) - there's potentially a different (more robust) approach that could be taken here, such as creating an additional (empty) region that doesn't represent anything (/id/icon/(whitespace)/name)

**Comment by wroyca** [comment] 2024-07-19 13:28
> > -- The strategy here involves filtering out situations where users might attempt
> > -- to synchronize such input and then automatically correcting said region. This
> > -- is possible as icons add one extra whitespace to account for their width,
> > -- which we use as a rule to capture the input we need.
> 
> Unfortunately, this does not generalize well because users can override prefix with `content.prefix`. It is more a coincidence that there is a space after an icon because this is a result of `default_prefix()`.

@echasnovski Do you think it'd be worth exploring further and coming up with a solution that actually generalizes well? I wouldn't mind taking on the work and walking with you toward such;

**Comment by echasnovski** [comment] 2024-07-19 13:33
> @echasnovski Do you think it'd be worth exploring further and coming up with a solution that actually generalizes well? I wouldn't mind taking on the work and walking with you toward such;

I think I'd be OK with the solution if it is concise, universal, and efficient enough. However, I am not sure there is a good way to satisfy all three.

The best idea I have in mind for this is a 'TextChanged'/'TextChangedI' autocommand (or `nvim_buf_attach()` with `on_lines`) that verifies that all buffer lines have proper structure. Possibly even fixing fixable lines like after `d$` by appending extra space. But at the moment I don't think the problem is bad enough to justify adding this (there are at least *two* reasonable ways to go around this).
