### ISSUE TITLE
`MiniBufremove.wipeout()` crashes nVim 

### ISSUE THREAD

**Issue by savchenko** [echasnovski/mini.nvim#1331] opened 2024-11-10 08:59 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

MiniBufremove

### Description

nVim crashes when trying to wipeout a particular type of a buffer.

### Neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Steps to reproduce

1. Install Ansible language server and `lspconfig.ansiblels.setup({})`
2. Execute `<S-k>` on any keyword
3. Observe documentation opened in a split
4. **important** move mouse cursor from pseudo command-line to anywhere in the buffer
4. Execute `MiniBufremove.wipeout()`

### Expected behavior

Buffer is closed, split is closed.

### Actual behavior

```
E315: ml_get: Invalid lnum: 1
Error detected while processing CursorMoved Autocommands for "*":
E16: Invalid range: call s:Highlight_Matching_Pair()
Error detected while processing WinScrolled Autocommands for "*":
E16: Invalid range: call s:Highlight_Matching_Pair()
Error detected while processing SafeState Autocommands for "*":
E16: Invalid range: call s:Highlight_Matching_Pair()
E315: ml_get: Invalid lnum: 1
Error detected while processing function <SNR>67_RunDeferred: line    5:
E16: Invalid range:   call timer_start(0, function('s:RunDeferred'))
E16: Invalid range:   call call(Fn, [])
Error executing vim.schedule lua callback: Vim:E158: Invalid buffer name: 1349103392
stack traceback:
        [C]: in function 'sign_unplace'
        ...er/.local/share/nvim/lazy/marks.nvim/lua/marks/utils.lua:27: in function 'remove_buf_signs'
        ....local/share/nvim/lazy/marks.nvim/lua/marks/bookmark.lua:297: in function 'refresh'
        ...user/.local/share/nvim/lazy/marks.nvim/lua/marks/init.lua:79: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

nVim crashes.

**Comment by echasnovski** [comment] 2024-11-10 12:18
Thanks for the issue!

I can not reproduce, mostly because `<C-k>` doesn't open anything for me. If you mean `K` (or `<Shift>`+`k`) for documentation, it opens information in a floating window for me, not a split.

Moreover, there is no indication that this error comes from 'mini.bufremove'. More likely it is 'marks.nvim' that stumbles after wiped out buffer. Can you reproduce the same error if you executed plain `:bwipeout` (and *not* `:lua MiniBufremove.wipeout()`)?

**Comment by echasnovski** [comment] 2024-11-10 12:45
> `:bwipeout` results in this:

Does `:lua MiniBufremove.wipeout()` result in the same error?

My point is that if `MiniBufremove.wipeout()` and `:bwipeout` result in the same error, then it is not a 'mini.bufremove' issue: [`wipeout()` is a thin wrapper around `:bwipeout`](https://github.com/echasnovski/mini.nvim/blob/998cfcf1fdd0a6830d0fc35f1c054a6f55de1e7f/doc/mini-bufremove.txt#L89). All errors (so far) come from plugins that can not handle the wiped out buffer.

**Comment by echasnovski** [comment] 2024-11-10 13:04
Judging by the same `E315: ml_get: Invalid lnum: 1`, I'd say this is not an issue with 'mini.buremove'.

Closing as working as expected. If you find reproduction steps that throw error with `:lua MiniBufremove.wipeout()` but don't throw error with `:bwipeout`, please post a comment here.

**Closed by echasnovski** 2024-11-10 13:04 UTC
Labels: mini.bufremove, needs-repro
