### ISSUE TITLE
mini.clue submode not working with postkeys

### ISSUE THREAD

**Issue by domsch1988** [echasnovski/mini.nvim#561] opened 2023-11-08 15:27 UTC
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

I have setup two hotkeys to increase or decrease GuiFont. I want to use those as a submode. This is the basic setup:

### Neovim version

0.10.0

### Steps to reproduce

The Keybinds:
```
local keymap = vim.keymap.set

function increase_font()
  local current_size = tonumber(string.match(vim.o.guifont, 'h(%d+)'))
  if current_size then
    local new_size = current_size + 1
    vim.o.guifont = string.gsub(vim.o.guifont, 'h%d+', 'h' .. new_size)
  end
end

function decrease_font()
  local current_size = tonumber(string.match(vim.o.guifont, 'h(%d+)'))
  if current_size then
    local new_size = current_size - 1
    if new_size >= 5 then -- To prevent the font size from becoming too small
      vim.o.guifont = string.gsub(vim.o.guifont, 'h%d+', 'h' .. new_size)
    end
  end
end

keymap("n", "<leader>uk", function() increase_font() end, { noremap = true, silent = true, desc = 'Increase Font Size' })
keymap("n", "<leader>uj", function() decrease_font() end, { noremap = true, silent = true, desc = 'Decrease Font Size' })
keymap("x", "<leader>uk", function() increase_font() end, { noremap = true, silent = true, desc = 'Increase Font Size' })
keymap("x", "<leader>uj", function() decrease_font() end, { noremap = true, silent = true, desc = 'Decrease Font Size' })
```

And the mini.clue Setup:
```
      require('mini.clue').setup({
        window = {
          delay = 200
        },
        triggers = {
          { mode = 'n', keys = '<Leader>' },
          { mode = 'n', keys = '<Leader>u' },
          { mode = 'x', keys = '<Leader>' },
          { mode = 'x', keys = '<Leader>u' },
        },
        clues = {
          { mode = 'n', keys = '<Leader>u',  desc = '+UI' },
          { mode = 'n', keys = '<Leader>uj', postkeys = '<leader>u' },
          { mode = 'n', keys = '<Leader>uk', postkeys = '<leader>u' },
          { mode = 'x', keys = '<Leader>u',  desc = '+UI' },
          { mode = 'x', keys = '<Leader>uj', postkeys = '<leader>u' },
          { mode = 'x', keys = '<Leader>uk', postkeys = '<leader>u' },
          require('mini.clue').gen_clues.builtin_completion(),
          require('mini.clue').gen_clues.g(),
          require('mini.clue').gen_clues.marks(),
          require('mini.clue').gen_clues.registers(),
          require('mini.clue').gen_clues.windows(),
          require('mini.clue').gen_clues.z(),
        },
      })
```

### Actual behavior

From the Notes in clue.lua it reads as this should work. The first execution of the hotkey does work. It also reopens mini.clue to the same spot, but the highlighting on "j" and "k" are missing and pressing the button again doesn't result in the action being performed, or mini.clue getting triggered. It just closes the popup and does nothing.

**Comment by echasnovski** [comment] 2023-11-08 15:37
I can not reproduce this with generic mappings for `"<leader>uk"` and `"<leader>uj"`. Submode can be initiated and repeated as expected.

What I would suggest trying:
- Remove `'<Leader>u'` as trigger in both Normal and Visual modes. As there is `'<Leader>'` for both of them, it will already be triggered.
- If the first one didn't work, could you try with a more generic `increase_font` and `decrease_font` functions? I mean the ones which are guarantee to not throw an error. The behavior you describe *might* be the one if there was an error in running mappings.

**Comment by domsch1988** [comment] 2023-11-08 15:43
You are, as always, correct. It seems the functions are the problem. I changes the keymaps to this:
```
keymap("n", "<leader>uk", "k", { desc = 'Increase Font Size' })
keymap("n", "<leader>uj", "j", { desc = 'Decrease Font Size' })
```
And these repeat as expected. Though i'm not sure where exactly the issue with my functions would be. I can triggern them rapidly with a direct keymap and they don't seem to produce any obvious errors.

**Comment by echasnovski** [comment] 2023-11-08 15:57
I've just tried it with `increase_font` / `decrease_font` and `vim.o.guifont = 'Monaco:h10'` (as taken from the help). It also works as expected.

Couple more possible debug directions:
- What value of 'guifont' do you use when that 'mini.clue' behavior happens?
- Do you have any other `<Leader>u` mappings?
- Do you have any other `increase_font` / `decrease_font` functions somewhere else? Because in issue config those functions are global (there is not `local` before `function`). So maybe there is a conflict somewhere?

**Comment by domsch1988** [comment] 2023-11-09 07:29
So, i did a couple more tests:

- My Regular GuiFont is "RobotoMono Nerd Font:h12". But i also Testet Consolas, a non-Nerd Font
- Yes, i do have other <leader>u mappings, but i disabled them for testing. No change.
- No other functions like that are declared. I also tried declaring the as local, without change.

It might have to do with neovim-qt or with the fact i'm running on windows. I don't know why it would, but who knows.

For obvious Reasons i only wrote up the configuration parts that i thought where relevant, but if you want to take a look the entire configuration in question is hostet here: https://gitlab.com/domsch1988/domvim

**Comment by echasnovski** [comment] 2023-11-10 10:40
> It might have to do with neovim-qt or with the fact i'm running on windows. I don't know why it would, but who knows.

Yes, something like that seems possible.

I've cloned the whole config and could not reproduce the issue (while having increase/decrease font working). So I'll close this one as it doesn't seem to be an issue with 'mini.clue' and its postkeys. If you'll be able to make a reliable reproduction steps, feel free to comment here.

**Closed by echasnovski** 2023-11-10 10:40 UTC
Labels: bug, mini.clue

**Comment by domsch1988** [comment] 2023-11-10 11:34
Quick Update: In Neovide on Windows this works fine. I'll see if i open a bug against Neovim-qt.
